### ISSUE TITLE
Request: Update PacketEvents to use newer compressor library

### ISSUE THREAD

**Issue by ghost** [retrooper/packetevents#1010]
Right now im stuck between choosing Flamecord or using PLHidePro, both I have paid money for - and now I can only choose between one.

- Flamecord is no longer compatible with PacketEvents because "PacketEvents requires old compressor libraries", while Flamecord is more modernized **according to the developer of Flamecord**.

- The Flamecord developer has already made an attempt at [FlameCord Changelogs](https://builtbybit.com/resources/flamecord-ultimate-anti-bot-solution.13492/updates) but said its not possible without PacketEvents being updated.
- My request: Update PacketEvents with new compressor library to make it compatible with modern things.

Flamecord Developer:
![image](https://github.com/user-attachments/assets/20299c93-d60b-4928-908a-5b1e1e279bf0)
![image](https://github.com/user-attachments/assets/29aa538d-ab2b-4b4a-bd75-13f7df192696)

**Comment by booky10** [comment]
Flamecords issue is not that they are changing compression libraries, but still use the "old" bungee compression handler, which is no longer supported by packetevents
Packetevents doesn't care what compression is used by bungee/flamecord, it cares about _how_ the compression gets applied

If you've paid money for flamecord, they should at least try to fix your issues. It's not complicated, but the developer doesn't respond to mentions on Discord

**Comment by linsaftw** [comment]
> Flamecords issue is not that they are changing compression libraries, but still use the "old" bungee compression handler, which is no longer supported by packetevents Packetevents doesn't care what compression is used by bungee/flamecord, it cares about _how_ the compression gets applied
> 
> If you've paid money for flamecord, they should at least try to fix your issues. It's not complicated, but the developer doesn't respond to mentions on Discord

We don't use the old compression handler.
