### ISSUE TITLE
A BUG WITH DISPLAYING AN OBJECT WHEN IT IS LYING ON THE FLOOR

### ISSUE THREAD

**Issue by Vinrey123** [retrooper/packetevents#1011]
**Describe the bug**
When I throw away an item from the Oraxen plugin made according to a template, an error appears https://github.com/user-attachments/assets/b592f976-5905-4b79-b445-6405dc623d2c

**Software brand**
Paper 1.21.1

**Plugins**
packetevents-spigot-2.5.1-SNAPSHOT
oraxen-1.182.0
PlaceholderAPI-2.11.6
ProtocolLib726

**How To Reproduce**
1. Make an item in Oraxen using this template https://github.com/user-attachments/assets/b592f976-5905-4b79-b445-6405dc623d2c
2. Throw the object on the floor 
3. Error in console

**Expected behavior**
I would like to see the object when it lies on the floor without errors in the console

**Screenshots**
https://github.com/user-attachments/assets/66f37d00-fb0a-4010-a8ff-98b005c3769e
https://github.com/user-attachments/assets/4eef5d9d-acef-43b3-9fac-4cb84673f692
https://github.com/user-attachments/assets/744b5c0e-fa3e-416d-be5c-8b4222400dc8
https://github.com/user-attachments/assets/afee6dc0-55ac-4e72-ae33-faf61a369e1d

**Additional context**
I noticed that if you remove this, the item will start working again, so that's the problem. https://github.com/user-attachments/assets/785390b4-0f0d-4a61-a69a-99be4328f825

**Comment by booky10** [comment]
could you send the output of `/paper dumpitem` while holding the problematic item in your main hand?

**Comment by Vinrey123** [comment]
I don't understand your question a bit, I'm holding an object in my hand, I'm writing a command, but there's nothing like that. It's just that when I hold an item in my hand, nothing happens, but as it turns out, other players don't see it if I hold it, but I can eat it.
