### ISSUE TITLE
PacketEvents IndexOutOfBoundsException

### ISSUE THREAD

**Issue by KinczeK** [retrooper/packetevents#1030]
**Describe the bug**
Basically server randomly crashes every few hours, before the actual crash there are few exceptions from PacketEvents (LPX & GrimAC).

**Software brand**
Paper 1.16.5

**Plugins**
ViaVersion, LPX, GrimAC, DecentHolograms, Vulcan

**How To Reproduce**
It's completely random, we couldn't reproduce it. It happens every few hours and then crashes whole server.

**Expected behavior**
Removal of this issue, so server could work flawlessly.

**Screenshots**
...

**Additional context**
Logs: https://paste.gg/p/anonymous/d1b1ffc5b02e4dd58c73a9899368915f

**Comment by booky10** [comment]
Could you please send all errors on shutdown?
The error you've sent doesn't really make sense, it would mean some plugin would be sending invalid data

**Comment by booky10** [comment]
Closing as author didn't respond
