### ISSUE TITLE
conflict between excellentenchants, oraxen, packetevents and protocollib

### ISSUE THREAD

**Issue by thatpris** [retrooper/packetevents#1033]
**Describe the bug**
When BOTH packetevents and protocolib are present, enchants from excellentnenchants cannot be applied to items. Removing either packetevents or protocolib seems to fix the error, so this seems like a conflict between those two. 

**Software brand**
Paper 1.21.1

**Plugins**
ExcellentEnchants, Oraxen, PacketEvents and Protocolib.

**How To Reproduce**
1. Join with Paper 1.21.1 and all aforementioned plugins
2. Get an enchantment book from ExcellentEnchants
3. Apply it to an item in anvil
4. Bug occurs

**Expected behavior**
The item should be enchanted normally.

**Screenshots**
https://github.com/user-attachments/assets/ab1e492a-9914-4b26-b50c-a50d884675f8

**Additional context**
I have tried asking both ExcellentEnchants and Oraxen, and they have concluded that this is a conflict between packetevents and protocolib.

**Comment by jtJava** [comment]
What version of PacketEvents did you try?

**Comment by thatpris** [comment]
> What version of PacketEvents did you try?

I am using latest spigot release, but I tested with dev builds and same result

**Comment by booky10** [comment]
Seems to be a conflict between packetevents and oraxen, still doesn't work for me when removing protocollib (and removing protocollib usage from oraxen)

**Comment by booky10** [comment]
@thatpris after further testing, this issue isn't related to packetevents

ExcellentEnchants and Oraxen don't work together - regardless of whether PacketEvents/ProtocolLib are installed or not

https://github.com/user-attachments/assets/41d54385-5233-4e04-ad1a-2dc9aab428bb

**Comment by retrooper** [comment]
Thank you @booky10.
