### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by RootException** [retrooper/packetevents#1038]
**Describe the bug**
NullPointerException when pinging/joining server

**Software brand**
Flamecord LATEST

**Plugins**
- PacketEvents-Bungeecord
- Pl-Hide-Pro

**How To Reproduce**
1) Startup Proxy
2) Ping/Join Server

**Expected behavior**
No NullPointer

**Screenshots**
<img width="1677" alt="image" src="https://github.com/user-attachments/assets/a49b9d55-9f4a-446f-93a0-f20cac5aa668">

**Additional context**
NaN

**Comment by retrooper** [comment]
Could you show us some of your code?

**Comment by retrooper** [comment]
Is this consistent? What version are you joining on?

**Comment by booky10** [comment]
@RootException did you solve this already? have you contacted flamecord about this? we can't fix issues with proprietary software

**Comment by RootException** [comment]
Flamecord Dev didnt know how to fix this... Switched to Velocity. Now all works fine :)

**Comment by Xefreh** [comment]
> Flamecord Dev didnt know how to fix this... Switched to Velocity. Now all works fine :)

there is a velocity fork that add nice features if you want. https://github.com/GemstoneGG/Velocity-CTD
