### ISSUE TITLE
1.21.3 Velocity doesn't work

### ISSUE THREAD

**Issue by NoltoxGit** [retrooper/packetevents#1039]
**Describe the bug**
When a client try to connect with the latest Java version (1.21.3), i've a lot of errors in my console.
> Errors: https://mclo.gs/MikgEO5

**Software brand**
Velocity 3.4.0-SNAPSHOT (git-9da52f04)

**Plugins**
ajqueue, azlink, commandforward, litebans, luckperms, maintenance, maintenanceaddon, packetevents, novpn, pl-hide-pro, plan, premiumvanish, signedvelocity, spark, ultrastaffchatpro

**How To Reproduce**
1. Use the latest velocity version
2. Use the latest packetevents devbuild (https://ci.codemc.io/job/retrooper/job/packetevents/585/)
3. Use the latest client version
4. See the errors

**Expected behavior**
Client can connect with the 1.21.3 version.

**Screenshots**
![image](https://github.com/user-attachments/assets/5f3964b3-3f82-4ab0-aa45-bf561a6997f6)

**Comment by booky10** [comment]
Packetevents doesn't support 1.21.3 yet, use the update PR #975 if you want to test

**Comment by NoltoxGit** [comment]
> Packetevents doesn't support 1.21.3 yet, use the update PR #975 if you want to test

On velocity, it's seem to work good! Thank you :)
