### ISSUE TITLE
All NPC objects share same unique scoreboard team name.

### ISSUE THREAD

**Issue by ShreyasAyyengar** [retrooper/packetevents#1040]
**Describe the bug**
All instances of the NPC class share the same scoreboard team name, which, in effect, means all NPC's share the same metadata of that team. (prefix/suffix). 

https://github.com/retrooper/packetevents/blob/d8a44fe8b6143578afd969c1eb192d782377e2b5/api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java#L439

**Software brand**
Please let us know what software you are using.
Paper version 1.21.1-105-master@b7ab22d (2024-09-27T18:16:58Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

**Expected behavior**
Instances of NPCs should have unique and independent team names.

**Screenshots**
<img width="1122" alt="Screenshot 2024-10-24 at 9 10 45 pm" src="https://github.com/user-attachments/assets/83f68810-fcca-4214-aa1f-8cfe7582b0b1">
<img width="339" alt="Screenshot 2024-10-24 at 9 10 51 pm" src="https://github.com/user-attachments/assets/5e9c2262-f7f6-490b-9d80-3e9faac36e1d">
![Screenshot 2024-10-24 at 9 11 12 pm](https://github.com/user-attachments/assets/83714345-0329-4965-b95c-d41eed4f840c)

**Comment by jtJava** [comment]
Entity ID could be added to the team name

**Comment by retrooper** [comment]
Seems resolved?

**Comment by ShreyasAyyengar** [comment]
> Seems resolved?

I don't think so. jtJava's suggestion, I think, was a suggestion for a potential commit.

**Comment by retrooper** [comment]
Ah, dang. We wanted to discourage the reliance on the NPC API. But sure if someone wishes to make a PR for it, we'll accept it.

**Comment by ShreyasAyyengar** [comment]
> Ah, dang. We wanted to discourage the reliance on the NPC API. But sure if someone wishes to make a PR for it, we'll accept it.

It seems simple enough to implement what jtJava was suggesting. Is there any chance you'd be able to commit that one line in? 

I know you've mentioned in the past that NPC API is not a priority, but since this seems more of a bugfix than API expansion, I think it should be alright.

**Comment by ShreyasAyyengar** [comment]
> Ah, dang. We wanted to discourage the reliance on the NPC API. But sure if someone wishes to make a PR for it, we'll accept it.

[Here it is](https://github.com/retrooper/packetevents/pull/1044)!
