### ISSUE TITLE
1.21.3 - LoginServerLoginSuccess IndexOutOfBoundsException

### ISSUE THREAD

**Issue by TechnicallyCoded** [retrooper/packetevents#1046]
**Describe the bug**
IOB exception on login success due to the internal packetevents listener

**Software brand**
Paper 1.21.3

**Plugins**
NoChatReports (packetevents shaded)

**How To Reproduce**
*Example:*
1. Run 1.21.3, in this case paper
4. Login

**Expected behavior**
Be able to join

**Additional context**
Full server log
[https://api.mclo.gs/1/raw/zKewOL9](https://api.mclo.gs/1/raw/zKewOL9)

**Comment by booky10** [comment]
1.21.3 is not supported on the packetevents version which is used by NoChatReports
they either need to update to snapshot builds or wait until 2.6.0 is released
