### ISSUE TITLE
Setter method for prompt component in WrapperPlayServerResourcePackSend

### ISSUE THREAD

**Issue by SuperMax8** [retrooper/packetevents#1061]
In the WrapperPlayServerResourcePackSend wrapper
I can get the Component prompt
but I can't set it

I would like just a setter method like that

```
public void setPrompt(Component prompt) {
        this.prompt = prompt;
}
```

 com.github.retrooper.packetevents.wrapper.play.server
WrapperPlayServerResourcePackSend

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/d4b4b24e3ca01becb5485b3d0235d65a1c5b0e0a
