### ISSUE TITLE
Use Component Instead of String in WrapperPlayServerUpdateScore

### ISSUE THREAD

**Issue by PytacMnieMozesz** [retrooper/packetevents#1067]
Description:
Currently, WrapperPlayServerUpdateScore uses a String for objectiveName:
[Code Link](https://github.com/retrooper/packetevents/blob/a0fc7f69781504fa94b44aa77685a18a97ee1770/api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerUpdateScore.java#L34)

Replacing it with a Component would enable RGB colors and advanced formatting (e.g., with Kyori).

Proposal:
Switch objectiveName to a Component for modern text support and formatting flexibility.

Benefits:
Enables RGB colors.
Supports advanced text formatting.
Future-proof API.

**Comment by booky10** [comment]
The `objectiveName` isn't a name shown to players, its just the internal identifier for specific objectives. This isn't a component on the network level and we sadly can't change how the Minecraft network protocol works.

If you want to change the scoreboard title, see `WrapperPlayServerScoreboardObjective#displayName`.
If you want to change the score name (available for 1.20.3+), see `WrapperPlayServerUpdateScore#entityDisplayName`
