### ISSUE TITLE
Wither Effect Kick

### ISSUE THREAD

**Issue by lightfishyy** [retrooper/packetevents#1079]
**Describe the bug**
I get kicked when applying wither effect to a mob via commands (tested on an iron golem)

**Software brand**
Please let us know what software you are using.
Eg. Spigot 1.18.2, Paper 1.18.2, Tuinity 1.18.2, Pufferfish 1.18.2, etc...
Make sure to mention the version of the software.
Paper 1.21.1 PacketEvents API 2.6.0
1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z)

**Plugins**
Please give us a list of your plugins. Sometimes we run into incompatibilities. Having an overview of the plugins on your server can really help identify the problem quicker.
Eg. ViaVersion, ProtocolLib, HolographicDisplays
You may also provide a screenshot.
![image](https://github.com/user-attachments/assets/4706e3c0-e477-4dc6-9882-0df8614beec3)

**How To Reproduce**
Join 1.21.1 server with packetevents api 2.6.0
Type /effect give [any mobs uuid] wither 1 1 true

**Expected behavior**
I shouldn't get kicked

**Screenshots**

**Additional context**

**Comment by booky10** [comment]
Which kick message are you getting? Are there any other errors in the logs? If yes, please attach them

**Comment by lightfishyy** [comment]
> Which kick message are you getting? Are there any other errors in the logs? If yes, please attach them

![image](https://github.com/user-attachments/assets/3e6e656d-01e1-415f-a85e-a1955d3fc920)
there are no other errors in the logs

**Comment by lightfishyy** [comment]
this is also happening when throwing a wind charge at a mob

**Comment by lightfishyy** [comment]
seems to be fixed after updating libsdisguises

**Comment by lightfishyy** [comment]
nevermind still happening its a incompatibility with libs disguises
