### ISSUE TITLE
Kick on 1.21.4 when Opening Chests (Using Viaversion)

### ISSUE THREAD

**Issue by 0x484** [retrooper/packetevents#1082]
**Describe the bug**
When opening a chest on a 1.21.4 Client, you get kicked from the server.
Note that the kick happens on velocity.

**Software brand**
Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
Velocity 3.4.0 (latest)

**Plugins**
Viaversion 5.2.0 + Packetevents 2.6.0 + Pl-Hide-Pro 2.11.2 (On bukkit level) 
Packetevents 2.6.0 + Pl-Hide-Pro 2.11.2 (On Velocity)

**How To Reproduce**
1. Join with the 1.21.4 vanilla minecraft client.
2. Open chest/any container
3. get kicked

**Comment by booky10** [comment]
Please update packetevents - if this issue still occurs, provide the actual error and stacktrace
