### ISSUE TITLE
Error on Place a Block on Server, newest Versions (Spigot, PackEvents, BungeeCord)

### ISSUE THREAD

**Issue by Robin-Arnhardt** [retrooper/packetevents#1084]
PackEvents Version: 2.6.0 on newest BungeeCord (https://prnt.sc/mZXJe1Y1ekuP)

Error: https://prnt.sc/zGWwME4ZzHmP

i get this error (ON BUNGEECORD) if i wanna place a block on my Server. Server has newest spigot version (https://prnt.sc/SQOb6F55i0fc)

On the Spigot Console i get this error, IF I DEINSTALLED PackEvents on BungeeCord): https://prnt.sc/AjqXLBD6khUN and this Kick message: https://prnt.sc/f7FCsWH7FWGL

Please fix it,
Thanks!

**Comment by booky10** [comment]
If you want 1.21.4, use the latest packetevents snapshot buidls from https://ci.codemc.io/job/retrooper/job/packetevents/
