### ISSUE TITLE
Can't join the server with version 1.21.3

### ISSUE THREAD

**Issue by KidTechnical** [retrooper/packetevents#1091]
**Describe the bug**
I can't join my Paper 1.21.3 server because of a packet event error.

**Software brand**
Paper 1.21.3, latest build 81

**Plugins**
AdvancedBan (2.3.0), ArmorStandEditor (1.21.1-47.2), AuraSkills (2.2.7), Badword (1.0), BestTools (2.3.0), BetterChairs (1.12.0), BetterRTP (3.6.13), BetterTeams (4.10.0), BlockParticles (1.12), BlueSlimeCore (2.9.6.431), CMILib (1.5.2.4), ChatEmojis (2.4.1), ChatGames (1.2.1), Citizens (2.0.35-SNAPSHOT (build 3585)), Codex (1.18.1), CoinsEngine (2.4.1), CombatLogX (11.5.0.0.1242), CommandTimer (8.11.0), CoreProtect (22.4), CrazyEnvoys (1.12.2), CrazyVouchers (3.7.4), DecentHolograms (2.8.12), DeluxeMenus (1.14.0-Release), DeluxeTags (1.8.2-Release), DiceFurniture (3.9.3), EasyCommandBlocker (1.12.1), EpicRename (3.12), Essentials (2.21.0-dev+151-f2af952), EssentialsDiscord (2.21.0-dev+151-f2af952), EssentialsDiscordLink (2.21.0-dev+151-f2af952), EssentialsSpawn (2.21.0-dev+151-f2af952), ExcellentCrates (5.3.5), ExcellentEnchants (4.3.2), FastAsyncWorldEdit (2.12.3-SNAPSHOT-996;7427665), ForcePack (1.3.6), FurnitureLib (3.2.5), Geyser-Spigot (2.6.0-SNAPSHOT), GriefPrevention (16.18.1), Infiniteannouncements (2.5.0), InteractiveChat (4.2.14.0), InvSeePlusPlus (0.29.11), InvSeePlusPlus_Clear (0.29.11), InvSeePlusPlus_Give (0.29.11), Jobs (5.2.4.5), KoTH (2.0.8), LPC (3.6.0), LibsDisguises (10.0.44-SNAPSHOT), Lottery (1.4.9), LuckPerms (5.4.150), Multiverse-Core (4.3.1-b861), MythicMobs (5.7.2-${CI_COMMIT_SHORT_SHA}), ODailyQuests (2.3.0-SNAPSHOT-16), PermSk (2.0.0), PlaceholderAPI (2.11.6), PlayerAuctions (1.30.2), PlayerLimitBypass (1.0.1), PlayerVaults (4.4.0-SNAPSHOT), PlayerWarps (7.6.1), ProtocolLib (5.3.0), Quests (3.15.2-b216e2b), SetModelData (1.0.0), SilkSpawners_v2 (2.3.2), SkBee (3.6.5), Skript (2.9.5), SuperbVote (0.5.5), TAB (5.0.3), Tebex (2.1.0), Themis (0.16.1), UltraCosmetics (3.9-RELEASE), VariableEnderChests (1.11.2.1), Vault (1.7.3-b131), ViaBackwards (5.2.1-SNAPSHOT), ViaRewind (4.0.4), ViaRewind-Legacy-Support (1.5.2-SNAPSHOT), ViaVersion (5.2.1-SNAPSHOT), Votifier (2.7.3), WorldGuard (7.0.12+829a4a4), WorldGuardExtraFlags (4.2.4-SNAPSHOT), ajLeaderboards (2.9.0), floodgate (2.2.3-SNAPSHOT (b114-83fbd6e)), nightcore (2.7.3), packetevents (2.7.0), skRayFall (1.9.28), skUtilities (0.9.2), skript-placeholders (1.6.0), sleep-most (5.5.1)

**How To Reproduce**

1. Join my server polyplex.sparked.host:25565 using the vanilla 1.21.3 launcher
2. See java.net.SocketException error in Minecraft
3. I would be able to see this error in console: https://pastebin.com/snizRDch

**Expected behavior**
You would be able to join the server normally.

**Additional context**
I use packetevents as a dependency for some other plugins. I'm not sure if the VariableEnderChest error has anything to do with this, but removing the plugin doesn't fix the issue.

**Comment by HaHaWTH** [comment]
https://github.com/SamB440/ForcePack/actions/runs/12360777747

Update your ForcePack plugin
