### ISSUE TITLE
WrappedPacketInUseEntity

### ISSUE THREAD

**Issue by Godl1nk** [retrooper/packetevents#117]
so basically the problem is, my Plugin will only receive this packet if it right click a player/entity, spoiler of the code
can be found below. It will not broadcast any message if i hit a player, it would only broadcast a message "one" if i right click a player

    @Override
    public void onPacketReceive(Player player, NMSPacket packet, byte id) {
        if (VoidAC.getInstance().getConfigs().getBoolean("Checks." + "Reach" + ".TypeA" + ".state")) {
            if (id == PacketType.Play.Client.USE_ENTITY) {
                WrappedPacketInUseEntity wrappedPacketInUseEntity = new WrappedPacketInUseEntity(packet);

                Bukkit.broadcastMessage("one");

                if (wrappedPacketInUseEntity.getAction() == WrappedPacketInUseEntity.EntityUseAction.ATTACK) {

                    Bukkit.broadcastMessage("two");

**Comment by Godl1nk** [comment]
and im using latest dev version

**Comment by Godl1nk** [comment]
also tried 1.7.9, same issue, did i set it up wrongly

**Comment by retrooper** [comment]
It should work, if possible can I get to view as much code as possible. If you don’t want to share it publicly you can contact me on Discord. retrooper#1646 is my tag. By latest dev version, do you mean latest pre-release? Do you mean latest commit?

**Comment by retrooper** [comment]
What Spigot are you using?

**Comment by retrooper** [comment]
Any feedback?

**Comment by Godl1nk** [comment]
sry for late reply, it was my code's issue, tysm for replying

**Comment by retrooper** [comment]
👍
