### ISSUE TITLE
1.16.5 getPacketId() breaking with recent commit

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#130]
First commit with this issue: https://github.com/retrooper/packetevents/commit/015038c9b61a71ca63b4b78a5a4ff527a93e05e2

It keeps returning a value of -128 for all position packets.  Issue occurs on 1.16.5.  It also occurs on 1.17.  Some packets such as transactions return the correct value on 1.16.

**Comment by retrooper** [comment]
Thank you for reporting this, I will attempt to reproduce.

**Comment by retrooper** [comment]
Have you tested the most recent commit?

**Comment by retrooper** [comment]
I've been able to reproduce, working on fixing.

**Comment by retrooper** [comment]
#9de94b7 fixed this

**Comment by retrooper** [comment]
This fixed your issue https://github.com/retrooper/packetevents/commit/9de94b79be4d608a16ee1baaa0ab9be68f9be777

**Comment by MWHunter** [comment]
Issue has been fixed
