### ISSUE TITLE
WrappedPacketOutMapChunk getX() and getZ() 1.17 support

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#131]
In 1.16 and below:
- int 0 is X
- int 1 is Z

In 1.17:
- int 0 is the size of 2 megabytes
- int 1 is X
- int 2 is Z

**Comment by retrooper** [comment]
True, I don't know how I missed this. Thank you.

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/f09617b2c2ac74499e6a1cc1b107e80efc5fcbf5
