### ISSUE TITLE
WrappedPacketOutEntityLiving getEntityType broken

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#133]

**Comment by retrooper** [comment]
This might take a bit of time.

**Comment by retrooper** [comment]
If I'm not mistaken, you said you were working on a PR for this at some point. Are you still working on it, or should I start dealing with it?

**Comment by MWHunter** [comment]
I am no longer working on it

**Comment by retrooper** [comment]
Will be supported in 2.0.
