### ISSUE TITLE
1.17 getPrimaryBitMap() for WrappedPacketOutMapChunk not supported

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#135]

**Comment by retrooper** [comment]
Working on it, its been a known issue.

**Comment by retrooper** [comment]
WrappedPacketOutMapChunk#getPrimaryBitMaskBitSet created for 1.17, I haven't fully understood how they work so I couldn't find a common form for 1.17 and 1.16 or older bit masks. But WrappedPacketOutMapChunk#getPrimaryBitMask should work on 1.17, just might be missing some data.
