### ISSUE TITLE
PacketType.Play.Client.FLYING ID broken on 1.17

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#136]
This packet is the position packet with onGround status only.  You can get this packet by towering upwards only pressing space and right click, not looking or moving in any other way.  The packet works on 1.16 but on 1.17, the ID is -128.

if (packetID == PacketType.Play.Client.FLYING) {

**Comment by MWHunter** [comment]
Broken on both spigot and paper 1.17

**Comment by retrooper** [comment]
?

**Comment by retrooper** [comment]
PacketType.Play.Client.FLYING isn't broken.

**Comment by retrooper** [comment]
-128 Packet ID means its an undocumented/unknown Packet ID. I have double-checked, I see no issue with FLYING.

**Comment by MWHunter** [comment]
The problem is that this is a packet ID that exists on 1.17.  For some reason, I can check when the packet arrives with this code:

if (event.getPacketName().equalsIgnoreCase("d")) {
}

In here, when you get the packet ID, it will be -128.  This is wrong because the packet exists but the packet ID believes it does not exist.
