### ISSUE TITLE
BoundingBox Util

### ISSUE THREAD

**Issue by SquareCodeFX** [retrooper/packetevents#147]
It needs a Util to get the BoundingBox of a player. If it works for all versions in one method

Best regards

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/blob/ebe782c0b1087c185932568461ac750ba0b52fd4/src/main/java/ac/grim/grimac/utils/enums/Pose.java

https://github.com/MWHunter/Grim/blob/ebe782c0b1087c185932568461ac750ba0b52fd4/src/main/java/ac/grim/grimac/predictionengine/PlayerBaseTick.java#L74

https://github.com/MWHunter/Grim/blob/ebe782c0b1087c185932568461ac750ba0b52fd4/src/main/java/ac/grim/grimac/utils/nmsImplementations/GetBoundingBox.java#L13

**Comment by retrooper** [comment]
I've created PacketEvents.get().getServerUtils().getEntityBoundingBox(Entity)
