### ISSUE TITLE
WrappedPacketOutChat setMessage

### ISSUE THREAD

**Issue by Jochyoua** [retrooper/packetevents#155]
WrappedPacketOutChat's setMessage appears to only factor in the first letter of the message I give it, I am attempting to match and replace words based on a regex string and whenever I debugged the string it shows correctly but when I attempt to set the message it only outputs the first letter of the string when I am trying to modify the message in chat

**Comment by retrooper** [comment]
Can you actually show me how you use the wrapper? Looking at the code, it should be fine.

**Comment by retrooper** [comment]
I think the string needs to be in JSON format and thats why.

**Comment by retrooper** [comment]
Can you try this for now:
wrapper.setMessage(NMSUtils.fromStringToJSON("your string"));

**Comment by Jochyoua** [comment]
Works just fine thank you very much, is it possible to get the JSON from the packet, though? I haven't figured out a method yet
