### ISSUE TITLE
Problem sending Login packets to player.

### ISSUE THREAD

**Issue by Sportkanone123** [retrooper/packetevents#159]
Hey, I'm trying to send a WrappedPacketLoginOutCustomPayload to a player, after the Login process started (PacketType.Login.Client.START was received by the server). The problem is that I can't find a way to send the packet to the player because the player dosn't exist yet (And you can only use 'PacketEvents.get().getPlayerUtils().sendPacket(<player>, <packet>);' or 'PacketEvents.get().getPlayerUtils().sendPacket(<channel>, <packet>);' .

**Comment by retrooper** [comment]
https://github.com/retrooper/packetevents/commit/51af277d4862705d2f8f10627876cf11b860ea13 should fix your issue. You can now access the netty channel through the NMS packet events.
```java
Object channel = event.getChannel();
PacketEvents.get().getPlayerUtils().sendPacket(channel, wrapper);
```
