### ISSUE TITLE
Event fails to cancel

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#161]
**Describe the bug**
PacketPlayReceiveEvent.cancelled can desync from NMSPacketEvent.cancelled causing strange behavior in terms of packets not cancelling.

![receiveevent](https://user-images.githubusercontent.com/49797025/132620675-5af22c0d-959d-425b-bc6f-4dfea405e419.png)

**Comment by retrooper** [comment]
That is weird, I noticed that the NMSPacketEvent#cancelled variable shouldn’t exist, I have a CancellableNMSPacketEvent which extends NMSPacketEvent and has the cancelled variable.

**Comment by retrooper** [comment]
I’ll look into this when I’m home.

**Comment by retrooper** [comment]
Afaik NMSPacketEvent#cancelled isn’t used

**Comment by MWHunter** [comment]
Oh, I found the bug:
- If there are multiple listeners listening on the same priority, only the first one will be able to cancel the event because https://github.com/retrooper/packetevents/blob/0595fb6e03cef9bf25715b9d9339b05d217aeee7/src/main/java/io/github/retrooper/packetevents/event/manager/EventManagerModern.java#L65 checking to see if the current priority is greater than the highest reached priority.  As a previous listener with the same priority set this, only the first listener is able to cancel this packet.

I'm not sure what this code does

**Comment by MWHunter** [comment]
Also, yes NMSPacketEvent#cancelled isn't used anywhere and could be removed.

**Comment by retrooper** [comment]
> Oh, I found the bug:
> 
> * If there are multiple listeners listening on the same priority, only the first one will be able to cancel the event because https://github.com/retrooper/packetevents/blob/0595fb6e03cef9bf25715b9d9339b05d217aeee7/src/main/java/io/github/retrooper/packetevents/event/manager/EventManagerModern.java#L65
>    checking to see if the current priority is greater than the highest reached priority.  As a previous listener with the same priority set this, only the first listener is able to cancel this packet.
> 
> I'm not sure what this code does

You're right, I will quickly fix this for 1.8, I wasn't sure what I was thinking when I initially wrote the code. I fixed this long ago in 2.0 already.

**Comment by retrooper** [comment]
Fixed in 1.8-pre-18
