### ISSUE TITLE
Player client version getting stuck as UNRESOLVED

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#162]
The player's client version gets stuck as UNRESOLVED as it is in the clientVersionsMap.  This causes an issue where it will never be resolved.

![unresolved](https://user-images.githubusercontent.com/49797025/133292787-ee29c933-4555-4465-aad5-5ca0fc0fea9b.png)

**Comment by Izibane** [comment]
config issue

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/934d5378e509cae32705cc76e82b1d5a3097e342
