### ISSUE TITLE
[BUG REPORT] WrappedPacketOutPlayerInfo issue

### ISSUE THREAD

**Issue by HakanGulgen** [retrooper/packetevents#166]
Spigot version: PaperSpigot 1.8.8
PacketEvents version: 1.8-pre-18
Plugins: 1 plugin (packetevents shaded)

BUG: I'm trying to edit player's player info data list on join. It doesn't change the player's name and also i got this error:

Error:
![error](https://user-images.githubusercontent.com/20889640/135141047-3970eb18-6903-4d0c-84bb-fc7214ff1a8a.png)

Code:
![code](https://user-images.githubusercontent.com/20889640/135141107-d365405c-4ca7-4ff5-b15a-88f0f2ac655f.png)

**Comment by retrooper** [comment]
This commit solved this https://github.com/retrooper/packetevents/commit/935c9782a13981d9e8a120fd3fc2de186196b1b1
