### ISSUE TITLE
1.7 player injection is unreliable

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#167]
**Describe the bug**
Sometimes, on player login, the player's state fails to enter GAME, resulting in none of their packets being processed

**To Reproduce**
*Example:*
1. Login to a spigot 1.7 server and hope for the best that it doesn't inject.  I can't consistently reproduce this.

**Expected behavior**
All players who join 1.7 and are playing should be in the game state

**Screenshots**
![badstate](https://user-images.githubusercontent.com/49797025/136066457-1be36aee-b4f0-4290-9d00-ed4f4631f153.png)

**About your server (please complete the following information):**
My test server with only one plugin, grimac.  I did not hotswap anything when this error occured.
 
- Server Version: [eg. 1.16.4]
Spigot 1.7.10

- Plugins List if possible: [eg. ViaVersion, ProtocolLib, HolographicDisplays]
GrimAC

**Additional context**
Using PacketEvents version https://github.com/retrooper/packetevents/tree/1ea4880dede42be46d4b23cfcc306ac48bb131a2

**Comment by retrooper** [comment]
What makes you sure this isn’t possible on 1.8?

**Comment by MWHunter** [comment]
I'm not sure, I just noticed that this has happened a few times out of a few hundred logins on 1.7.

**Comment by MWHunter** [comment]
Closing because I was the only one with this issue - and it no longer affects me now that I've moved on to 2.0
