### ISSUE TITLE
Enchantments type ID is broken

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#191]
I don't know where it is used though, but ViaVersion translates it so I think it's important somewhere

**Comment by retrooper** [comment]
I don’t understand the issue?

**Comment by MWHunter** [comment]
I looked at the wiki and it is used in the WINDOW_PROPERTY packet

**Comment by Izibane** [comment]
­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­


























































































































­

**Comment by retrooper** [comment]
@MWHunter ?

**Comment by retrooper** [comment]
After a quick glance, the mappings look fine.

**Comment by retrooper** [comment]
We don't have a window property wrapper yet.

**Comment by retrooper** [comment]
???
