### ISSUE TITLE
Allow packet wrappers to be reusable

### ISSUE THREAD

**Issue by retrooper** [retrooper/packetevents#192]

**Comment by retrooper** [comment]
Idea: duplicate the encoded buffer in the send method implementation

**Comment by retrooper** [comment]
They need to retain the buffer themselves, but find out why this doesn't work with the chat message packet last time I tried.

**Comment by retrooper** [comment]
Essentially we likely need to do some buffer retain duplication.

**Comment by retrooper** [comment]
We should make a method called makeResuable() or so in the wrapper to simplify this task. So users dont need to interact with netty directly.

**Comment by terrarier2111** [comment]
Should the user call makeReusable before every use of the Wrapper, or only once and let them clean up the buffer's memory once they don't need it anymore or we just leave the buffer's memory lingering (this would probably be pretty bad)

**Comment by retrooper** [comment]
Idek, you tell me how we do it. Just sometimes people want to send one packet wrapper to a set of users without re-encoding it each time. You know?

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/16f9eb32c9fddb911b296c33de28ac229be88eaf

It does have to re-encode it every time, but I don't trust users enough to not memory leak to give them that ability.
