### ISSUE TITLE
getEnchantments doesn't work for enchanted books

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#195]
It uses the StoredEnchantments tag instead of the Enchantments tag, except on maybe 1.7?

**Comment by retrooper** [comment]
1.7 does too

**Comment by retrooper** [comment]
Update on this?

**Comment by MWHunter** [comment]
I finally felt like fixing this with https://github.com/retrooper/packetevents/commit/12bd685fe79d0a1e44523d9816b7ed954ec96100
