### ISSUE TITLE
Packet type mappings for 1.18 not working? Possibly packet id = -1

### ISSUE THREAD

**Issue by retrooper** [retrooper/packetevents#196]

**Comment by retrooper** [comment]
Need to confirm if this is still a bug.

**Comment by MWHunter** [comment]
[16:49:27] [Netty Epoll Server IO #1/INFO]: [GrimAC] [STDOUT] Packet sent type is null

I can confirm that this is still an issue.

        if (event.getPacketType() == null) {
            System.out.println("Packet sent type is null");
        }

**Comment by retrooper** [comment]
Is the event.getPacketId() == -1 though? But yea I'll look into mappings. What version?

**Comment by MWHunter** [comment]
This would be 1.18, I searched for this string on the grim test server

**Comment by retrooper** [comment]
event.getPacketId() is the literal ID in the buffer, that honestly should never be null, if it is, its an injector issue. If its just PacketType  object, then mappings are broken.

**Comment by MWHunter** [comment]
I haven't tested for packet ID being -1 only for packet type being null, but I'll add that debug to check for this scenario

**Comment by retrooper** [comment]
Why can't I reproduce this on my 1.18 server?

**Comment by retrooper** [comment]
Someone please re-open this issue once this re-occurs. New commits should provide a more detailed stacktrace with more information.
