### ISSUE TITLE
When a playee joins while the server is starting packetevents stop working.

### ISSUE THREAD

**Issue by Tecnio** [retrooper/packetevents#2]
https://hastebin.com/jumajewamu.cs

**Comment by retrooper** [comment]
Thank you for opening this issue, it will be fixed in the next commit!
I will close this issue once I push out a fix!

**Comment by retrooper** [comment]
The only solution would be to block joins while the server is starting 🤷‍♂️

**Comment by retrooper** [comment]
What I am going to do is kick the online players while the server is reloading, to support reloads!
I also will block joins while the server is reloading.
Doing this should fix this bug, expect the fix probably in the next release.

**Comment by retrooper** [comment]
resolved, use 1.3.5.2
