### ISSUE TITLE
Add velocity proxy support

### ISSUE THREAD

**Issue by SkyLicks** [retrooper/packetevents#208]
**Is your feature request related to a problem? Please describe.**
There is no PacketListener API that I know of for Velocity-based Proxies. Plz add <3. I saw you added Bungee support, so Im wondering if you could also add Velocity support?

**Describe the solution you'd like**
Simply extend PacketEvents to be able to hook into Velocity.

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
So I need to listen to packets to edit a tab completion for an obfuscated plugin in velocity that I didn't write. I've considered directly Modifying my Velocity jar but that's probs a terrible idea.

**Additional context**

**Comment by retrooper** [comment]
No bungee support/implementation of the API yet

**Comment by retrooper** [comment]
Eventually I will add Velocity support, course, that's been on my list, I just want to complete the API module, make sure PacketEvents is stable on spigot, potentially push out a first pre-release of 2.0. Then from then on, start working on Velocity/Bungee/etc support. Porting to other platforms (especially if not Spigot) is actually quite easy.

**Comment by SkyLicks** [comment]
Awesome! Looking forward to it.

**Comment by retrooper** [comment]
Managed to push out fabric support in a day. Kind of just as a dummy project, Velocity could be coming out quite soon.

**Comment by retrooper** [comment]
Little reminder that velocity hasn't been forgotten, once some other critical issues on spigot have been fixed and some performance improvements(for all platforms) are dealt with, velocity is on its way.

**Comment by retrooper** [comment]
First foot steps: https://github.com/retrooper/packetevents/commit/474a2c9e2eb2a455016c87d79e6d6713b30223cf

**Comment by SkyLicks** [comment]
Good to see!

**Comment by retrooper** [comment]
I'd say pretty much done!

**Comment by retrooper** [comment]
Oh yea, have to add. If you want to use it already, check our version-dynamic branch!

**Comment by retrooper** [comment]
as a dependency, you can do
```gradle
compileOnly 'com.github.retrooper.packetevents:velocity:version-dnyamic-SNAPSHOT'
```
I suggest you to use the pre-built JAR via GitHub Actions and not attempt shading yet...
https://github.com/retrooper/packetevents/suites/5913317445/artifacts/201829437
It is in that .zip
