### ISSUE TITLE
Join game wrapper

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#213]
The join game packet doesn't exist as a wrapper.  This contains registries such as a dimension's minimum and maximum height, and also the player's entity ID.

**Comment by retrooper** [comment]
Already created in my project called Graphene, but there it only supports 1.18. I will work on making it cross-version and then slide it into packetevents.

**Comment by retrooper** [comment]
Done https://github.com/retrooper/packetevents/commit/af0faf6436f805575f75b784c0c21e3c958bac04 https://github.com/retrooper/packetevents/commit/313d2f956c69db3a60c6dadea54011e2b3887340
