### ISSUE TITLE
WrapperPlayClientPlayerBlockPlacement negative Y does not work

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#214]
The Y value is a few thousand off because negative values on the Y doesn't seem to be supported

**Comment by retrooper** [comment]
I believe this has been fixed.

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/c6f7d4d4f9a60b286d031dbd0ffeeea451a072dc
