### ISSUE TITLE
Every single packet's ID is TELEPORT_CONFIRM

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#216]
The current latest 2.0 commit isn't usable because every single packet maps to TELEPORT_CONFIRM on the client side (id 0 on 1.18).  The ID's for sending packets do not appear to be broken.  I'm not using any plugins other than packetevents.

**Comment by MWHunter** [comment]
Issue appeared with https://github.com/retrooper/packetevents/commit/b52f8d5ce9b900a1737181b1c1ffb9526d1e3f2c 

The issue does not occur when ViaVersion is installed.  It only occurs if ViaVersion is not installed.

**Comment by retrooper** [comment]
What is odd is this worked on 1.8 without Via

**Comment by retrooper** [comment]
I don't think that commit specificalty caused it, but its been fixed in https://github.com/retrooper/packetevents/commit/86fc6bb452cc5b216334181df49123e358eea06a
