### ISSUE TITLE
Cancelling packets with ViaVersion broken.

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#217]
Likely related to https://github.com/retrooper/packetevents/issues/216

Sending a player a PONG packet causes ViaVersion to error and disconnect the user with an out of bounds exception.  Many other packets are likely affected but PONG was the easiest to test.

**Comment by retrooper** [comment]
Can you confirm whether it is reproducable on https://github.com/retrooper/packetevents/commit/86fc6bb452cc5b216334181df49123e358eea06a

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/a52a35755b6369db22de08ccdae65c860a22d10c
