### ISSUE TITLE
[BUG REPORT] PacketPlayOutWindowItems(1.8.x)

### ISSUE THREAD

**Issue by huanmeng-qwq** [retrooper/packetevents#223]
**Describe the bug**
PacketPlayOutWindowItems not carriedItem field(com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerWindowItems#carriedItem)

**To Reproduce**
*Example:*
1. com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerWindowItems#carriedItem

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/4fde212445c489644300b8c6bdd6a25b614732a4
