### ISSUE TITLE
Only inject NioSocketChannels and EpollSocketChannels. So we can avoid injecting random NPCs.

### ISSUE THREAD

**Issue by retrooper** [retrooper/packetevents#230]

**Comment by MWHunter** [comment]
Issue still relevant

**Comment by retrooper** [comment]
Ahhh thats the cause of that citizens thing.

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/e92f1c8e16d4b3142c5830ce5eaa19bf0e76c1ee
