### ISSUE TITLE
packetevents + ViaVersion + ProtocolLib messes with ViaVersions's version detection

### ISSUE THREAD

**Issue by Jaren8r** [retrooper/packetevents#233]
Doing /viaver list on a server with all 3 plugins shows the player's version as `UNKNOWN`. Removing ProtocolLib fixes this.

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/03a5f8ec906a42987d7b505085f45ac10ba343de and https://github.com/retrooper/packetevents/commit/dd1c35dfb31250481d883560918eb08fc4af368f
