### ISSUE TITLE
Keeping JSON maps in memory wastes 10 MB

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#238]
class Main {
  private static int x = 123;

  static {
    x = 0;
  }
  
  public static void main(String[] args) {
    System.out.println(x);
  }
}

output: prints 0

Static blocks after static variables can set the MAP to null

**Comment by retrooper** [comment]
With my entity types, the static block runs first. then the allocation. Probably cause the allocation calls a method.

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/cddf378b51611d9e76ee645edd0e9adb566aceb5
