### ISSUE TITLE
Outgoing event is null? User is in HANDSHAKING state, but the server already wants to send a packet to them?

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#240]
https://gist.githubusercontent.com/MWHunter/a32e9f80ba8caa7da1d61c9dc650ee38/raw/8959e87ebd7df6c02cf993d472529b90717c9f4b/gistfile1.txt

I don't know why this happened.

**Comment by retrooper** [comment]
Still?

**Comment by MWHunter** [comment]
Yes

**Comment by retrooper** [comment]
Any consistency?

**Comment by MWHunter** [comment]
not really.  It happens on the test server a lot when no one is online.

**Comment by retrooper** [comment]
I worked around with some stuff, lets see if this fixes itself.

**Comment by MWHunter** [comment]
this isn't fixed

**Comment by Izibane** [comment]
event != null
easy fix?

**Comment by retrooper** [comment]
I don't want to risk losing early packets.

**Comment by retrooper** [comment]
Trying to understand the underlying cause.

**Comment by MWHunter** [comment]
My guess is that it has something to do with the query protocol.  There's no debug messages from a player ever handshaking and there is no one online.  This is just a wild guess though.

**Comment by MWHunter** [comment]
Connecting with beta 1.7.3 will cause event to be null.  This reproduces consistently 100% of the time.

**Comment by retrooper** [comment]
Perfect, will help me look into this. My assumption is it has something to do with the LEGACY SERVER LIST PING packet.

**Comment by retrooper** [comment]
Are you still testing with 1.7.3?

**Comment by MWHunter** [comment]
Minecraft release 1.6.4 also causes the exception to be thrown

**Comment by MWHunter** [comment]
This seems to be fixed after ignoring the legacy ping packets and waiting until play state before allowing transactions to be sent.  Perhaps add a warning so other packetevents user's don't make the same mistake I did

**Comment by MWHunter** [comment]
Still an issue when a pre-1.7 player tries to connect

**Comment by MWHunter** [comment]
Finally got annoyed enough to add a handshake send event
Fixed in https://github.com/retrooper/packetevents/commit/70dc93cd09d6314143a17740bd251ad74c52987c

The server sends a raw byte buffer in the old format during the handshaking state to respond to the ping, and then kills the client's connection.  So this isn't a hack and is actually correct.
