### ISSUE TITLE
Accessing User by channel throws NPE (via ProtocolManager)

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#242]
I have a reference to the User, but I can't go from channel -> user immediately due to some race condition making some methods like PlayerManager::getClientVersion(channel) throw a null pointer

![user](https://user-images.githubusercontent.com/49797025/153982767-319cb780-6de7-48ad-882a-e9d17a1a1ff0.png)
a

**Comment by MWHunter** [comment]
Okay, now I'm in the state where the map simply doesn't have the player even though the player is online.  There's another race condition in this map.

**Comment by MWHunter** [comment]
I was also in the map twice at once point.

**Comment by retrooper** [comment]
Where are you running this?

**Comment by retrooper** [comment]
The player name is mapped with the channel once the server sends out the LOGIN_SUCCESS packet.

**Comment by retrooper** [comment]
Before that, the user has no useful data. No player name, uuid, Why not just use the channel passed to you by the event. event.getChannel() or just use user.getChannel() from the user that is passed to you in the event. The channel reference is already inside each user.

**Comment by retrooper** [comment]
And why do you want to interact with a netty channel directly anyway?

**Comment by retrooper** [comment]
getUser in PlayerManager is expecting a Player, not a Channel!
