### ISSUE TITLE
1.8 crash when injecting

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#243]
https://gist.githubusercontent.com/MWHunter/3794ef85f7fce7781f593585d3c48b30/raw/011cdc342c121cde74fdec638e1e17042a1af82f/gistfile1.txt

**Comment by MWHunter** [comment]
For reference I am joining extremely early on 1.8

**Comment by MWHunter** [comment]
Stacktrace with up to date packetevents: https://gist.githubusercontent.com/MWHunter/d727805db60784e490f0ce6b262812c9/raw/197e7902df38e14724f5afea262277ac39685924/gistfile1.txt

**Comment by retrooper** [comment]
Spigot?

**Comment by MWHunter** [comment]
[14:13:01 ERROR]: PaperSpigot version: git-PaperSpigot-445 (MC: 1.8.8)

**Comment by retrooper** [comment]
Related to NPCs?

**Comment by MWHunter** [comment]
No, this was on my test server without plugins.  Might be related to not having late bind on

**Comment by retrooper** [comment]
Was it?

**Comment by MWHunter** [comment]
no reported issues in months for this
