### ISSUE TITLE
Sychronization in injector accomplishes nothing

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#246]
https://github.com/retrooper/packetevents/blob/bb2e9902c9173f67dc37636ffe9fa600f250abc7/spigot/src/main/java/io/github/retrooper/packetevents/handlers/modern/early/EarlyChannelInjectorModern.java#L130

This does nothing, synchronizing a local variable doesn't synchronize to the object it is pointing to

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/6123ae9744eabddf681063b5f2036e308ee2364b
