### ISSUE TITLE
Profile is null while in play state

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#252]
![nullprofile](https://user-images.githubusercontent.com/49797025/154786743-8102062b-7c8b-488a-8e79-78fd6834bfe8.png)

Affects 1.8.  Reproduce by joining extremely early in the join process.

**Comment by MWHunter** [comment]
For reference, I start my connection before packetevents initializes.  I don't know how this could be fixed.

**Comment by retrooper** [comment]
Perhaps working with late-bind option? I haven't tested that in a long time, hopefully it works. If it ends up working, we can suggest legacy version users to always enable it.

**Comment by retrooper** [comment]
Check what I stated in https://github.com/retrooper/packetevents/issues/253
In summary, late-bind option fixes this, for legacy versions.
