### ISSUE TITLE
Failed to inject on NachoSpigot

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#254]
https://cdn.discordapp.com/attachments/898925977219006494/945318226210992208/unknown.png

**Comment by retrooper** [comment]
You later mentioned this is on NachoSpigot. I've added a debug in https://github.com/retrooper/packetevents/commit/74751c77c659c1a89e90e54eca6eeeaf7e539a7a to give us more information to work with and find out why this is occuring.

**Comment by MWHunter** [comment]
https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/dev/cobblesword/nachospigot/protocol/MinecraftPipeline.java

I would blame this change.

**Comment by retrooper** [comment]
I have an idea.

**Comment by retrooper** [comment]
Scheduled to be fixed in https://github.com/retrooper/packetevents/commit/275638339fe288b087dabacbeebb1d575335be59 (AKA This fix will be pushed once ProtocolLib pushes their dev builds)
