### ISSUE TITLE
InvocationTargetException when cancelling packets

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#256]
https://gist.githubusercontent.com/MWHunter/547fe371c2f1808b985cf03ecf6cb426/raw/502931252935782bbc7c1bec86504fb6a22bdaf0/gistfile1.txt

Paper 1.8.  This error occurs with ViaVersion and Grim.  Java 8

**Comment by MWHunter** [comment]
Affects 1.18 with ViaVersion and Grim with Java 17, although much less consistent

**Comment by retrooper** [comment]
Can't recreate this anymore, maybe latest commit fixed this?

**Comment by MWHunter** [comment]
Still an issue on 1.8 with ViaVersion + Grim

**Comment by retrooper** [comment]
Works perfectly fine on Spigot 1.8 with ViaVersion & packetevents.

**Comment by MWHunter** [comment]
Test with a client other than your server's version.  On 1.18 with a 1.8 client and Via*, I'm able to still reproduce

**Comment by retrooper** [comment]
Cancelling outgoing or incoming packets?

**Comment by retrooper** [comment]
I assume outgoing packets, I tested cancelling incoming ones to work.

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/2639c615e89899eb440acef1031e60a8fa32f238

**Comment by MWHunter** [comment]
This seems to occur when sending PONG packets to pre-1.17 players on a 1.18 server with ViaVersion.  ViaVersion seems to be unable to cancel the PONG packet, that's my guess at least.

**Comment by retrooper** [comment]
Does https://github.com/retrooper/packetevents/commit/87b58f2ab84b0b885819ceb66c371f25bb8921d3 fix this?

**Comment by MWHunter** [comment]
No

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/afe5bed6fc61b673bc76ef4c209790fa5bfd7427 
New issue is https://github.com/retrooper/packetevents/issues/262
