### ISSUE TITLE
WIth ViaVersion on a Velocity proxy, client versions are wrong

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#257]
https://gist.githubusercontent.com/MWHunter/1a845169e4a28df2c21b75a898de73d2/raw/2b11c4c4add520db691481ecb01b3614e79892e5/gistfile1.txt

I am using a 1.17.1 client.  PacketEvents is reading the client as a 1.18 client

**Comment by MWHunter** [comment]
This also affects PacketEvents 1.8.

**Comment by retrooper** [comment]
Yes since ViaVersion is modifying it in the packet and isn’t present on the spigot server. From the backend alone there’s nothing we can do.

**Comment by MWHunter** [comment]
Wish ViaVersion would send a plugin message at the very least...

**Comment by retrooper** [comment]
Its velocity

**Comment by Izibane** [comment]
> Its velocity
Its this ratio

**Comment by retrooper** [comment]
Can we close this? We'd honestly have to run Grim on the proxy to get the client-version correct, or have an additional plugin on velocity sending plugin messages to backend. We have no control on the backend, so this can be the downside of proxies.

**Comment by MWHunter** [comment]
Yeah, you can close it.  I'll likely write a plugin to forward this information with a generic name like "ViaFetcher", and then any anticheat can listen to the plugin message sent by this standardized name.
