### ISSUE TITLE
[BUG REPORT] Some thing with wrappers giving errors

### ISSUE THREAD

**Issue by JustDoom** [retrooper/packetevents#258]
**Describe the bug**
I try to get the packet wrapper but it gives off errors.

**To Reproduce**
*Example:*
1. Login on the 1.18.1 minecraft client.
2. Join the server
3. See error

**Expected behavior**
That not to give errors

**About your server (please complete the following information):**
 - Using latest purpur and happened on latest paper. Maybe errors because it was behind a velocity proxy? I think the proxy had viaversion and the other 2 actually installed
 
- Server Version: 1.18.1

- Plugins List if possible: only my plugin

**Additional context**
https://discord.com/channels/721686193061888071/755472595096174873/945178806682017802

**Comment by retrooper** [comment]
Can you use pastebin?

**Comment by JustDoom** [comment]
https://pastebin.com/0dEwkNuy
not spamming like it was atm anymore

**Comment by JustDoom** [comment]
never mind spammed again https://pastebin.com/zU6bBmd7

**Comment by retrooper** [comment]
Can we see some of your code?

**Comment by JustDoom** [comment]
i think some lines are different. ill test it again to get the lines correct again 
but here is the code https://github.com/JustDoom/FlappyAC/blob/full-release/plugin/src/main/java/com/imjustdoom/flappyanticheat/packet/processor/ReceivingPacketProcessor.java

**Comment by JustDoom** [comment]
@retrooper ok here https://bin.birdflop.com/oxeweyazup.md
just inore the boat? thing. was testing something

**Comment by retrooper** [comment]
Its cause you arre running threads while not on netty thread.

**Comment by retrooper** [comment]
Working with async listeners has become a bit tougher in 2.0, but I support it now.
You basically need to clone the event. event = event.clone() and make sure you use the cloned version. BUT as soon as you are doing with the event(after cloning), you must run event.cleanUp() or else you will end up with a memory leak.

**Comment by retrooper** [comment]
PS. You need to clone the event while you are inside the packet listener's thread obviously. Then the rest of the processing can be done later.
