### ISSUE TITLE
Overhead issues from native bytebuffers

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#259]
I am getting reports of users running out of native memory because of byte buffers in memory.  This was likely introduced in https://github.com/retrooper/packetevents/commit/8378b9265ae20e3c28f2e703a25ff6a21ed8f8b5

Hosts generally don't give enough overhead as most hosts are incompetent and don't understand java memory usage, but is there any way to eat into java memory instead of native memory without significant performance loss?

**Comment by retrooper** [comment]
Doubt there is a leak, according to netty developers, 
"There is no better between direct and heap, at least for most use cases"

**Comment by retrooper** [comment]
Maybe its a buffer in our encoder, I'll try look into it further.

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/2e660714aa9c47f24dc7a897100da24a2062163d
