### ISSUE TITLE
Entity Properties(attributes) wrapper broken for 1.7 clients with ViaRewind.

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#264]
01.03 04:14:26 [Server]  PacketEvents caught an unhandled exception while calling your listener.
01.03 04:14:26 [Server] INFO java.lang.IndexOutOfBoundsException: readerIndex(66) + length(8) exceeds writerIndex(69): UnpooledUnsafeDirectByteBuf(ridx: 66, widx: 69, cap: 256)
01.03 04:14:26 [Server] INFO at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
01.03 04:14:26 [Server] INFO at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:632) ~[paper-1.8.8.jar:git-PaperSpigot-"4c7641d19"]
01.03 04:14:26 [Server] INFO at ac.grim.grimac.shaded.io.github.retrooper.packetevents.utils.netty.buffer.ByteBufOperatorModernImpl.readLong(ByteBufOperatorModernImpl.java:84) ~[?:?]
01.03 04:14:26 [Server] INFO at ac.grim.grimac.shaded.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readLong(ByteBufHelper.java:111) ~[?:?]
01.03 04:14:26 [Server] INFO at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readLong(PacketWrapper.java:461) ~[?:?]
01.03 04:14:26 [Server] INFO at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readUUID(PacketWrapper.java:611) ~[?:?]
01.03 04:14:26 [Server] INFO at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityProperties.readData(WrapperPlayServerEntityProperties.java:71) ~[?:?]
01.03 04:14:26 [Server] INFO at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:112) ~[?:?]
01.03 04:14:26 [Server] INFO at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityProperties.<init>(WrapperPlayServerEntityProperties.java:35) ~[?:?]
01.03 04:14:26 [Server] INFO at ac.grim.grimac.events.packets.PacketEntityReplication.onPacketSend(PacketEntityReplication.java:134) ~[?:?]

Works fine for 1.8 clients on 1.8 servers, but 1.7 clients with ViaLegacy on a 1.8 server causes issues

**Comment by retrooper** [comment]
Looks like it is EntityProperties not EntityMetadata

**Comment by retrooper** [comment]
Please say ViaRewind and ViaBackwards instead of ViaLegacy.

**Comment by retrooper** [comment]
I don't think is is an issue on our end, but we might have to look into this deeper.

**Comment by MWHunter** [comment]
will reopen if this is reported again, but looking at where it failed, something else was going on and this bug report doesn't make sense and isn't useful.
