### ISSUE TITLE
Sending packets async

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#266]
**Is your feature request related to a problem? Please describe.**
let me send packets async

**Describe the solution you'd like**
sendAsync() and writeAsync()

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
Manually switching off the main thread to send packets

**Additional context**
PI filled out this request form for once.

**Comment by retrooper** [comment]
Done in https://github.com/retrooper/packetevents/commit/06b4607769230a9a3b8279677f348ec80aa4c1a3
