### ISSUE TITLE
Impossible to use old version in build.gradle

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#275]
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not resolve com.github.retrooper.packetevents:spigot:2.0-f6bce0d41b-1.
     Required by:
         project :
      > Could not resolve com.github.retrooper.packetevents:spigot:2.0-f6bce0d41b-1.
         > inconsistent module metadata found. Descriptor: com.github.retrooper.packetevents:spigot:2.0-SNAPSHOT Errors: bad version: expected='2.0-f6bce0d41b-1' found='2.0-SNAPSHOT'

**Comment by retrooper** [comment]
? Old version of what? and why use an old version

**Comment by MWHunter** [comment]
An old version of packetevents 2.0, such as 2.0-f6bce0d41b-1

I'm trying to use the old version because https://github.com/retrooper/packetevents/issues/274

**Comment by retrooper** [comment]
If it worked before, it would  not just dissapear.
