### ISSUE TITLE
2.0 doesn't work with ViaVersion and ProtocolLib

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#286]
Paper 1.17.1
ViaVersion 4.2.1
ProtocolLib 4.8.0
1.18.2 client
Commit 3a53fa88cbac31c4f988483c352fc4e6ce22b69a

**Comment by MWHunter** [comment]
Also affects 424f18e52b0c1525f3d28267dc04b29198bba10b

**Comment by retrooper** [comment]
Use ProtocolLib dev builds.

**Comment by retrooper** [comment]
And ViaVersion dev builds.
