### ISSUE TITLE
Chunk_Data packet broken on 1.18

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#288]
[18:16:02 INFO]: [PacketEventsTest] [STDOUT] Sending CHUNK_DATA
[18:16:02 INFO]: DefineOutside lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

**Comment by retrooper** [comment]
Try reproduce it again, thing is on older commits than https://github.com/retrooper/packetevents/commit/a9fb68223a643c8bdc497f47b56e50f07ec7d916 exceptions in our internal api were sort of surpressed. Now you should get a detailed stacktrace hopefully.

**Comment by retrooper** [comment]
And https://github.com/retrooper/packetevents/commit/8dfbda5e35cc8de633440b1ec58d0289d9937ba9 can help produce more meaningful exceptions for issues like these. Update to that.

**Comment by retrooper** [comment]
You have some indexoutofboundsexception in the chunk data wrapper, update to the mentioned commit to find out what line.

**Comment by NoJokeFNA** [comment]
@MWHunter Any news on this? 🤔

**Comment by MWHunter** [comment]
Fixed by reverting 5bf2daa7 so don't blame me for having the wrapper be broken for 3 months.

Retrooper pushed a commit that broke this wrapper...  @retrooper stop pushing without testing your changes.
