### ISSUE TITLE
[BUG REPORT] WrapperPlayServerMultiBlockChange causes players to be kicked

### ISSUE THREAD

**Issue by XReioX** [retrooper/packetevents#292]
**Describe the bug**
So when you read a multiblockchange packet, it will kick you with EncoderException: NPE

**To Reproduce**
1. Start up a 1.8.8 server
2. Log into 1.8.8 server with a 1.8.9 client
3. Have a plugin ready what is reading the multiblockchange wrapper
4. Just log in, and walk around and try breaking block etc

**Expected behavior**
I expect that it will not kick me, and instead give me the data requested.

**Screenshots**
None

**About your server (please complete the following information):**
 - Spigot: [eg. Paper or Tuinity]
    Paper
 
- Server Version: [eg. 1.16.4]
    1.8.8

- Plugins List if possible: [eg. ViaVersion, ProtocolLib, HolographicDisplays]
     PacketEvents & The plugin that's listening to the multiblockchange wrapper

**Additional context**
None

**Comment by retrooper** [comment]
Was able to reproduce. Will be looked into.

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/a9fb68223a643c8bdc497f47b56e50f07ec7d916

**Comment by retrooper** [comment]
And https://github.com/retrooper/packetevents/commit/8dfbda5e35cc8de633440b1ec58d0289d9937ba9 has some better patches for catching exceptions
