### ISSUE TITLE
[BUG] ModelEngine incompatibility

### ISSUE THREAD

**Issue by Skyslycer** [retrooper/packetevents#297]
**Describe the bug**
When having ModelEngine as a plugin, no packets come through to the player.

**Software brand**
Pufferfish 1.18.1

**Plugins**
Our Plugin, ModelEngine, Oraxen

**How To Reproduce**
Put the plugins into the plugins folder.
Start the server.
Join and try it out.
See that it does not work.

**Expected behavior**
The player should receive the packets.

**Comment by lucian929** [comment]
I can confirm this issue using any plugin which implements PacketEvents 2.0 while having ModelEngine installed.

**Comment by Fisher2911** [comment]
I can also confirm it

**Comment by MWHunter** [comment]
I've told ModelEngine's author how to fix this so they should fix their incompatibility soon.
