### ISSUE TITLE
1.7.10 clients forced disconnect

### ISSUE THREAD

**Issue by zhusun890** [retrooper/packetevents#300]
**Describe the bug**
When the version 1.7.10 client joins the server, the player will be forcibly disconnected with the reason "Internal Exception: io.netty.handler.codec.DecoderException: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 21 to a PacketType constant. Connection state: LOGIN, Server version: 1.8.8"

**Software brand**
TacoSpigot 1.8.8 R3, FlameCord build 77

**Plugins**
ProtocolSupport-1.8, Frost (Practice Plugin), ProtocolLib latest

**How To Reproduce**
1. Join with 1.7.10 client (taking Lunar Client 1.7.10 as an example)
2. Error and forced disconnect

**Expected behavior**
Allow version 1.7.10 clients to join the server or give self-resolution advice. (e.g. multi-client version plugin alternatives)

**Screenshots**
None

**Additional context**
None

**The logs of when the error occurred*
[Error Logs.txt](https://github.com/retrooper/packetevents/files/8403715/Error.Logs.txt)

**Comment by retrooper** [comment]
Use ViaVersion & ViaBackwards. We don’t support ProtocolSupport **1.8** which isn’t supported by them.

**Comment by retrooper** [comment]
If you use ProtocolSupport, use the latest version of their plugin, which unfortunately must be on the current latest server version. So just use ViaRewind.
