### ISSUE TITLE
Packet ID: 12. Failed to encode WrapperPlayServerSpawnPlayer

### ISSUE THREAD

**Issue by zhusun890** [retrooper/packetevents#304]
**Describe the bug**
Sometimes, when the player shows up, an error occurs. For example. [20:50:18 INFO]: zhusun890 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.github.retrooper.packetevents.exception.PacketProcessException: PacketEvents failed to re-encode an outgoing packet with its packet wrapper. Packet ID: 12. Failed to encode WrapperPlayServerSpawnPlayer.

**Software brand**
TacoSpigot 1_8_R3, FlameCord Build #77

**Plugins**
ProtocolLib Latest Dev Build, Frost (Practice Core Plugin), ViaVersion and ViaRewind latest

**How To Reproduce**
1. Start a match with any practice plugin (e.g. StrikePractice, PotPvP-Si, etc.)
2. Other players are shown within your game
3. An error occurs and the player is disconnected.
(Contains some randomness)

**Expected behavior**
None

**Screenshots**
None

**Additional context**
None

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/2c83f6e5a5030c9de2612b30834cb53af1cd2375
