### ISSUE TITLE
FEATURE REQUEST: Add NachoSpigot support

### ISSUE THREAD

**Issue by zhusun890** [retrooper/packetevents#307]
**Is your feature request related to a problem? Please describe.**
When somebody joins a server with NachoSpigot and on pre-login state, it will be disconnected by reason "Exception Connecting: NativeIOException : readAddress(...) failed: Connection reset by peer"

**Describe the solution you'd like**
Add support for NachoSpigot

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**

**Additional context**

**Comment by amnoah** [comment]
Solution: don't use Spigot forks that mess with random stuff in order to make minuscule optimizations.

(ofc Retrooper/DefineOutside decide on outcomes for this stuff)

**Comment by Elierrr** [comment]
Not a PacketEvents issue. Issue tracked in CobbleSword/NachoSpigot#365.

**Comment by retrooper** [comment]
Tomorrow I will look into it, but something questionable is this works on any other server software.

**Comment by retrooper** [comment]
NachoSpigot now works. We recently added a Paper injector, which is more efficient on Paper software and luckily works on Nacho. https://github.com/retrooper/packetevents/commit/f9136dbf42158a924ebc29456b5e530afe5b4ff8
