### ISSUE TITLE
[2.0, MC 1.8] Reading vehicle steer packet causes errors

### ISSUE THREAD

**Issue by Izibane** [retrooper/packetevents#309]
**Describe the bug**
While entering a vehicle such as a minecart or boat, there is a chance that PacketEvents throws errors into the console.

**Software brand**
paperspigot 1.8.8  (CraftBukkit version git-PaperSpigot-"4c7641d19" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT))

PacketEvents version 2.0-417571fe8d-1

**Plugins**
Plugins (9): Atlas, PlugMan, spark, ViaVersion, Tora, LuckPerms, Essentials, EssentialsSpawn, EssentialsChat

**How To Reproduce**
1. Join a 1.8 server
2. Try and enter a minecart
3. Steer vehicle until error is thrown (A, D, W, S not sure which ones cause it)
 - Alternatively used a hacked client or mods to spam vehicle steer packets such and it will spam errors.

**Expected behavior**
NO ERROR 😱

**Screenshots**
https://www.toptal.com/developers/hastebin/sigijapino.yaml

**Additional context**
idk man help

**Comment by Izibane** [comment]
Happens when it reads the PacketPlayInSteerVehicle with seemingly different index and lengths
`Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(4) exceeds writerIndex(10): UnpooledUnsafeDirectByteBuf(ridx: 9, widx: 10, cap: 256) Caused by: java.lang.IndexOutOfBoundsException: readerIndex(10) + length(4) exceeds writerIndex(10): UnpooledUnsafeDirectByteBuf(ridx: 10, widx: 10, cap: 256)`

**Comment by Izibane** [comment]
https://www.toptal.com/developers/hastebin/zuxibicicu.yaml

**Comment by Izibane** [comment]
Huh?  No clue what you mean, happens in minecarts, I dont touch boats and
it happens in the nms steer vehicle packet

**Comment by retrooper** [comment]
Interesting I can't reproduce?

**Comment by retrooper** [comment]
Spamming so hard the CPU skipped cycles or what?

**Comment by retrooper** [comment]
Spamming so hard the CPU skipped instructions or what?

**Comment by retrooper** [comment]
(was a joke)

**Comment by retrooper** [comment]
Can't reproduce.

**Comment by Izibane** [comment]
warpping packet on seperate thread sadge
