### ISSUE TITLE
Offline mode WrapperLoginServerLoginSuccess out of bounds exception

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#318]
https://github.com/MWHunter/Grim/issues/363

**Comment by retrooper** [comment]
Works perfectly fine on my 1.8 spigot server with ViaVersion & ProtocolLib dev builds on 1.18.2 minecraft client.

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/fed8b95199f2b5daf401786245092f5446a258b5
