### ISSUE TITLE
Add BlockFace or Direction to vector

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#334]
Would be a nice shorthand to have

**Comment by Jaren8r** [comment]
How would this work?

**Comment by MWHunter** [comment]
you do .add(BlockFace.NORTH) and it adds the north vector to the vector.  Might need a helper method in BlockFace/Direction to generate the blockface vector.

new Vector3i(0,10,0).add(BlockFace.NORTH) = (0,10,-1)

**Comment by retrooper** [comment]
Im bed at meth, so you implement it

**Comment by Jaren8r** [comment]
While I agree having a helper method in BlockFace to turn it into an offset would be neat, I feel like the terminology of adding a blockface to a vector doesn't sound right. Maybe `new Vector3i(0, 10, 0).offset(BlockFace.NORTH)`?

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/7fde4a379a4cd15735a88ffc6187a593d6d48c5e
