### ISSUE TITLE
ProtocolSupport is broken

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#337]
On a paper 1.18.1 server, PacketEvents 2.0 breaks with ProtocolSupport

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/ab92d8bdd30054586d1c8f1fb4b94c5db19523b3

**Comment by retrooper** [comment]
and by https://github.com/retrooper/packetevents/commit/0e18040bee0306fdf380686e685d1b63e7a8d4bb
