### ISSUE TITLE
Failed to inject... Please rejoin!

### ISSUE THREAD

**Issue by Loudbooks** [retrooper/packetevents#338]
I'm getting this error when reloading my plugin with PlugmanX. Plugin list attached.
![image](https://user-images.githubusercontent.com/51384418/164321057-92dd871b-3965-4dd3-a8ab-dcebf8a3c52a.png)
![image](https://user-images.githubusercontent.com/51384418/164321083-c3ebe5bb-e46a-43a0-930c-32d30da0732f.png)

PacketEvents Version: 2.0-SNAPSHOT
Server Version: 1.18.2

Really annoying!

Thanks :D

**Comment by MWHunter** [comment]
what packetevents commit/version are you on?

**Comment by Loudbooks** [comment]
> what packetevents commit/version are you on?
@MWHunter 
Forgot to mention: I have 2.0-SNAPSHOT in my pom.xml

**Comment by MWHunter** [comment]
and what server version are you on?

**Comment by Loudbooks** [comment]
> and what server version are you on?

@MWHunter 
1.18.2

**Comment by NoJokeFNA** [comment]
You are just getting kicked if you reload the plugin while you are on the network, so you simply have to rejoin. In general, just don't reload stuff and just restart the server instead, causes less issues.

**Comment by MWHunter** [comment]
I think I could have broken something by avoiding injection into existing pipelines to avoid injecting before viaversion on 1.8.

**Comment by Loudbooks** [comment]
> You are just getting kicked if you reload the plugin while you are on the network, so you simply have to rejoin. In general, just don't reload stuff and just restart the server instead, causes less issues.

I guess, but it's really difficult to do that during testing.

**Comment by MWHunter** [comment]
You should attach a debugger and hot swap, then you won't have to constantly reload.  With something like DCEVM, you barely have to reload at all.

**Comment by Loudbooks** [comment]
That went _way_ over my head.

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/511b331735b275abc29ce7540736bd94c5b1c32f

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/6bf70f5b472c82e156416f3a96f7636f01333841
