### ISSUE TITLE
Fix joining early with late-bind off on legacy minecraft servers

### ISSUE THREAD

**Issue by retrooper** [retrooper/packetevents#341]
**Describe the bug**
Joining early with late-bind off on legacy minecraft servers can cause PacketEvents to not notice you joined the server.

**Software brand**
NachoSpigot 1.8.8 (but I assume it works the same on ordinary Spigot)

**Plugins**
ViaVersion 4.2.2

**How To Reproduce**
*Example:*
1. Join with the 1.8.8 vanilla minecraft client while the server starts
2. See error

**Expected behavior**
Be able to join servers that are still booting up without any issues.

**Comment by MWHunter** [comment]
![broken](https://user-images.githubusercontent.com/49797025/173238358-f823f606-9c6a-419c-aa28-6b9f886c2842.png)

Potentially related to this
