### ISSUE TITLE
WrapperPlayClientClickWindow bug with quick-move

### ISSUE THREAD

**Issue by NoJokeFNA** [retrooper/packetevents#344]
**Describe the bug**
The `ItemStack` is always null using `WrapperPlayClientClickWindow` with the `$getClickedItemStack()` method.

**Software brand**
Paper 1.18.2 (git-Paper-312)

**Plugins**
Only my testing plugin.

**How To Reproduce**
Steps to reproduce the behavior: (PacketEvents 2.0)
1. Check if the receiving packet is the `PacketType.Client.CLICK_WINDOW` packet
2. Check if the `WindowClickType` is `WindowClickType.QUICK_MOVE`
3. Use quick-move with some random items on e.g. a furnace
4. Check the output from the ItemStack

**Expected behavior**
The ItemStack which I quick-moved

**Screenshots**
Not needed ig as it's just null
`ItemStack[null]`

**Comment by MWHunter** [comment]
The protocol wiki here is wrong.  It shouldn't be clicked item, but should be carried item.  Carry an item on your cursor and shift click, it will work fine.

**Comment by MWHunter** [comment]
fixed the protocol wiki and changed packetevents mapping to be more accurate
