### ISSUE TITLE
IndexOutOfBoundsException with $readItemStack

### ISSUE THREAD

**Issue by NoJokeFNA** [retrooper/packetevents#345]
**Describe the bug**
The `$readItemStack` sometimes throws an IndexOutOfBoundsException.

**Code**
```java
final WrapperPlayClientUseItem wrapper = new WrapperPlayClientUseItem(event);
ItemStack itemStack;
try {
  itemStack = wrapper.readItemStack();
} catch (final IndexOutOfBoundsException exception) {
  exception.printStackTrace();
  return;
}
```

**Software brand**
Paper 1.18.2 (git-Paper-312)

**Plugins**
Only my testing plugin.

**How To Reproduce**
Steps to reproduce the behavior: (PacketEvents 2.0)
1. Check if the receiving packet is the `PacketType.Client.USE_ITEM` packet
2. Make sure that you have e.g. the item `Book and Quill` in your hand
3. Sneak and use `right-click` (place-action-click) in front of e.g. a furnace, beacon, dirt (doesn't matter ig)
4. See the exception in the console

**Expected behavior**
It should give me the given ItemStack as EMPTY, or, well, just the one I used in the moment

**Logs**
https://sourceb.in/ZztUL7GipY

## Little update
This happens generally with all wrappers, not just this one.

**Comment by MWHunter** [comment]
https://wiki.vg/Protocol#Use_Item

Use item and player block placement do not send the itemstack on 1.9 and above.  Therefore, there is nothing to read.
