### ISSUE TITLE
IndexOutOfBounds after joining the server

### ISSUE THREAD

**Issue by NoJokeFNA** [retrooper/packetevents#347]
**Describe the bug**
An `IndexOutOfBounds` exception is being thrown after joining the server.

**Software brand**
Paper 1.14.4 (git-Paper-245)

**Client brand**
LabyMod 1.16.5

**Plugins**
My testing plugin & ViaVersion-4.2.1

**How To Reproduce**
Steps to reproduce the behavior: (PacketEvents 2.0)
1. Join the server
2. See console for errors

**Expected behavior**
Well, the error shouldn't appear

**Logs**
https://sourceb.in/J2y7uKL9sJ

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/04e9e57dad34e1f9d8815c90a107ccc41fb05e7b.
The WrapperPlayServerJoinGame should be fixed on 1.14.x versions.
