### ISSUE TITLE
Force users to keep specific packet plugins up to date.

### ISSUE THREAD

**Issue by retrooper** [retrooper/packetevents#350]
Many packet plugins have had messy injectors in the past. So we have been going around informing them to clean it up or suggesting changes. We don't want to fall into the trap of also making a messy injector, so we will assume their modern injector is present.

* Enforce Protocollib 5.0.0 usage (if its present) ✔️ 
* Enforce ProtocolSupport 1.18.1-1 usage (if its present)
* Enforce ViaVersion 4.2.2 usage (if its present) ❌ (And once their next major update releases, that too)

**Comment by retrooper** [comment]
Need someone to tell me the oldest version of ProtocolSupport working with PacketEvents.

**Comment by retrooper** [comment]
Yeah the page to install old builds of it is down, so we'll enforce 1.18.1. On older server versions please just use ViaVersion.

**Comment by retrooper** [comment]
We now force users to use 1.18.1 or newer as the old builds page down.

**Comment by MWHunter** [comment]
considering old viaversion doesn't support protocollib 5.0 I don't see this as an issue.  Additionally, old ProtocolSupport no longer breaks PacketEvents, so this isn't an issue.
