### ISSUE TITLE
Paper injector breaks ProtocolSupport compatibility when reading early packets.

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#352]
![clientversion](https://user-images.githubusercontent.com/49797025/167315382-046be3d8-9250-457f-b572-ee7717c45ab1.png)

They get stuck to the server's version

**Comment by retrooper** [comment]
ProtocolSupport's handlers are added after us on the Paper injector and they end up being ahead of us.

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/3204527b6fc91f0df9640743a705a082ee2b64a9
