### ISSUE TITLE
Exceptions thrown in WrapperPlayServerSpawnLivingEntity

### ISSUE THREAD

**Issue by NoJokeFNA** [retrooper/packetevents#354]
**Describe the bug**
An `IndexOutOfBoundsException` and an `ArrayIndexOutOfBoundsException` exception is thrown randomly (?)
I just joined the server, pressed a few buttons and then there were some exceptions, although I didn't see them twice, just this once.

**Software brand**
Paper 1.13.2 (git-Paper-657)

**Client brand**
Normal 1.13.2 | Forge 1.18.2

**Plugins**
My testing plugin & ViaVersion-4.2.1

**How To Reproduce**
Steps to reproduce the behavior: (PacketEvents 2.0)
1. I have absolutely no clue

**Logs**
https://sourceb.in/BhQoHjHCXk

**Comment by MWHunter** [comment]
Does this happen on a 1.13.2 client, or only non-native client versions?

**Comment by NoJokeFNA** [comment]
Since I can't remember exactly which client version I was using, I'll try to get the exceptions again somehow and will let you know if I know anything new

**Comment by NoJokeFNA** [comment]
The client version doesn't matter, seems to be similiar to #373 and #374

**Comment by terrarier2111** [comment]
What is the type of entity which causes this?

**Comment by NoJokeFNA** [comment]
Well, I don't know as I have absolutely no clue how to reproduce it.

**Comment by MWHunter** [comment]
Metadata is included in the 1.13 spawn entity packet so it may be a metadata issue.

**Comment by MWHunter** [comment]
It was easy to fix, just mapping issues because metadata was written by hand: https://github.com/retrooper/packetevents/commit/b90920e63a64f6c007f04d4dfece8aa83749d97a

Don't know how POSE metadata got put into 1.13 mappings... it's obviously incorrect
