### ISSUE TITLE
InvalidKeyException after getting killed by a zombie

### ISSUE THREAD

**Issue by NoJokeFNA** [retrooper/packetevents#364]
**Describe the bug**
An `InvalidKeyException` exception is being thrown after getting killed by a zombie.

**Software brand**
NachoSpigot 1.8.8 (git-NachoSpigot-"0f63b63")

**Client brand**
MysteryMod 1.8.9

**Plugins**
My testing plugin & ViaVersion-4.2.1

**How To Reproduce**
Steps to reproduce the behavior: (PacketEvents 2.0)
1. Join the server
2. Get killed by a zombie
3. See error in console

**Expected behavior**
Well, the error shouldn't appear

**Logs**
https://sourceb.in/0W8hTxqp1c

**RegEx**
https://regex101.com/r/JYJPSk/1 | https://regex101.com/r/UrHbXX/1

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/a7a9ef52f002741fda0a3eb4f741b19ad2e2e86a
