### ISSUE TITLE
Switch to Google's Java Code Style

### ISSUE THREAD

**Issue by NoJokeFNA** [retrooper/packetevents#394]
I would like to change the Code-Style to [Google-Java-Style](https://google.github.io/styleguide/javaguide.html). It is very clear and easy to use.

#### Links
https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml
https://checkstyle.sourceforge.io/google_style.html
https://docs.gradle.org/current/userguide/checkstyle_plugin.html

#### Example
https://github.com/PaperMC/Velocity/tree/dev/3.0.0/config/checkstyle
https://github.com/PaperMC/Velocity/blob/dev/3.0.0/api/build.gradle

**Comment by MWHunter** [comment]
I don't like this style because tabs are objectively better than spaces

**Comment by retrooper** [comment]
Personally also rather a fan of tabs and most users wouldn't follow the requirements no matter how much you ask them.

**Comment by terrarier2111** [comment]
I agree that generally speaking tabs are better than spaces (although I personally adopted many of ther other google java style conventions). Also IMO style conventions should only be adopted if they actually help and make development easier
