### ISSUE TITLE
PacketEvents 2.0 memory leak

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#395]
**Describe the bug**
Occasionally, when a player disconnects, they will remain in the player hashmap

**Software brand**
Pufferfish 1.18.2

**Plugins**
Plugins (9): Essentials, LuckPerms, packetevents*, ProtocolLib, spark, TAB, ViaBackwards, ViaRewind, ViaVersion

**How To Reproduce**
*Example:*
Use lambdaattack to rapidly join users, and cancel the attack while users are joining.  Some players will be stuck in the hashmap.

**Expected behavior**
No memory leaks

**Screenshots**
[23:45:40 INFO]: [packetevents] [STDOUT] Users size (pre-add): 4

**Additional context**
This also affects GrimAC,, UserDisconnectEvent is not being called correctly

**Comment by MWHunter** [comment]
seems to be called by relying on the bukkit event to remove users, no other places are calling remove

**Comment by MWHunter** [comment]
I'll ask for forgiveness rather than permission, but after spamming my local server with bots, this commit seems to have fixed it: https://github.com/retrooper/packetevents/commit/a670961b991d050c2048e1634e61f7b941271f49

Will leave this issue open so you see it though

**Comment by MWHunter** [comment]
nevermind, it is still somehow leaking players, although this commit is better

**Comment by MWHunter** [comment]
nevermind, gradle caches were screwing with me.  After spamming start and stop on lambdaattack, with thousands of bots, I have found no leak.

**Comment by MWHunter** [comment]
Another memory leak was found with https://github.com/retrooper/packetevents/commit/0f061764e6ce2b32ba8f2b32ea58c028cfa9e70b

I will report back if there is still another memory leak.

**Comment by retrooper** [comment]
The handleDisconnection is already called on channel close in our encoder.

**Comment by retrooper** [comment]
I'll see what debugging I can do. How'd you get bots?

**Comment by MWHunter** [comment]
I used lambdaattack.  handleDisconnection  is not being called.  The two commits I have linked have fixed this, but there's likely something wrong with your handleDisconnection code if it isn't being called correctly

**Comment by retrooper** [comment]
Remove the call in the encoder.

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/96d8fc6d21f9d29d67f68ad3e9efb14e52d24717 https://github.com/retrooper/packetevents/commit/1868cee073b68bbbccdc6d699c3305ae00e3961e https://github.com/retrooper/packetevents/commit/351742e88e8f0ba878b7302c84ece4e15407183d https://github.com/retrooper/packetevents/commit/bd67caaeb8cb304f7851f8f43cb799485e7eddad and https://github.com/retrooper/packetevents/commit/16f9eb32c9fddb911b296c33de28ac229be88eaf
