### ISSUE TITLE
IllegalStateException on join with ViaVersions

### ISSUE THREAD

**Issue by iFlamingoz** [retrooper/packetevents#403]
**Describe the bug**
[IllegalStateException error](https://pastebin.com/UDMcVhB8) thrown on join with ViaVersion (latest dev) installed.
Most likely caused by 18b6ddca7080fc41ad5121cf67bcb65c53882b1b as the previous commit (e901b5dd64026be64490fb951a6c090a26e78460) works.

**Software brand**
1.8.8 PaperSpigot-445

**Plugins**
PacketEvents (2.0.0 - 18b6ddca7080fc41ad5121cf67bcb65c53882b1b)
ViaVersion (4.2.2-SNAPSHOT)

**How To Reproduce**
1. Use server version 1.8.8, 18b6ddca7080fc41ad5121cf67bcb65c53882b1b & ViaVersions
2. Join the server
3. https://pastebin.com/UDMcVhB8

**Comment by MWHunter** [comment]
The code isn't wrong... it's just that our encoder is named the same as ViaVersion's encoder.
