### ISSUE TITLE
Injector issues on KSpigot?

### ISSUE THREAD

**Issue by AVuTuVA** [retrooper/packetevents#406]
**Describe the bug**
Error at startup and during server operation.

**Software brand**
Latest kspigot 1.12.2(Fork Paper)

**Plugins**
[16:52:20 INFO]: Plugins (5): GrimAC, LuckPerms, ProtocolLib, spark, ViaVersion

**How To Reproduce**
Starting the server on 1.12.2

**Expected behavior**
The server will start without errors and will work stably.

**Screenshots**
I think an error message will do
https://pastebin.com/hFkyMt8L

**Additional context**
There was no such problem before

**Comment by NoJokeFNA** [comment]
["GrimAC is an open source anticheat designed for 1.18 and supporting 1.14-1.18 **with half working 1.8-1.13 support**"](https://github.com/MWHunter/Grim)

**Comment by retrooper** [comment]
Have you tested this on ordinary Paper or some open source paper fork to confirm if this is only occuring on KSpigot?

**Comment by AVuTuVA** [comment]
The problem was that I started the server on java 17)

**Comment by MWHunter** [comment]
Would injecting on main thread fix this?

**Comment by AVuTuVA** [comment]
I installed Java 11 and the problem went away

**Comment by AVuTuVA** [comment]
I don’t think it’s critical, because no one is running server 1.12.2 on Java 17

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/89cb93be670885562d04e04a3e4e04a10d983a09 probably.
