### ISSUE TITLE
PacketEvents injecting into NMS PacketDecoder, mistaking it for PacketEvent's decoder

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#408]
https://github.com/MWHunter/Grim/issues/518

**Comment by ilovefuud** [comment]
Same error with WindSpigot 1.8.8
https://github.com/Wind-Development/WindSpigot
https://pastebin.com/4GK0h6pb

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/bfe9aba3a8b4605e5c8183a0d9e2cef1c2b698e8
