### ISSUE TITLE
Fail to add decoder when there is no splitter

### ISSUE THREAD

**Issue by ilovefuud** [retrooper/packetevents#411]
**Describe the bug**
Some spigots have an updated netty and packetevents has issues adding a decoder.

**Software brand**
CarbonSpigot 1.8.8 https://discord.gg/h9uqn7xR

**How To Reproduce**
Load PacketEvents on a spigot with updated netty.

**Expected behavior**
No exception

**Additional context**
https://pastebin.com/raw/1JGWqSVi

**Comment by ilovefuud** [comment]
#406 has the same exception I believe.

**Comment by ilovefuud** [comment]
#406 Seems to have the same exception.

**Comment by amnoah** [comment]
That has to be the most desperate spigot fork I've ever seen.

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/89cb93be670885562d04e04a3e4e04a10d983a09
