### ISSUE TITLE
PacketEvents not working with network-compression-threshold set to -1

### ISSUE THREAD

**Issue by Boy0000** [retrooper/packetevents#412]
**Describe the bug**
In reference to [this convo](https://discord.com/channels/721686193061888071/844238390567370813/980572884533641237) in the Discord.
Found the issue stemming from network-threshold-compression being disabled.
Currently running all our servers under Velocity so it needs to be disabled on a per server basis.
Whenever it is set to -1 in server.properties, the issue from that convo happens. If it is set to something else, be that 64 or 2048 it works just fine.
Tried tweaking the velocity equivalent but it is purely to do with the subservers it seems

**Software brand**
Please let us know what software you are using.
Paper 1.18.2 release 351

**Plugins**
Plugins linked in the convo but are irrelevant to the issue

**How To Reproduce**
*Example:*
1. Put packetevents + protocollib 5 on any server
2. Set network-compression-treshold in server.properties to -1
3. Start up server and velocity proxy

**Expected behavior**
Should not need to have paper-servers network compression enabled

**Screenshots**

**Additional context**

**Comment by retrooper** [comment]
Oh, that issue.

**Comment by retrooper** [comment]
Let me see if i can get HMCCosmetics.

**Comment by Boy0000** [comment]
![image](https://user-images.githubusercontent.com/62521371/171427620-3d96f90e-e120-4c87-9ff1-74364727ef25.png)

Dont need HMCCosmetics. As long as PacketEvents is installed with ProtocolLib and network-compression-threshold on servers are set to -1 (disabled) it seems to just not work. Setting it to literally anything else works, even 204800000
Don't think it is an issue with our plugin since well it only happens when PacketEvents is installed and compression is at -1.
If PE is disabled (and -1 or anyhting else) no issue, if PE is enabled it cant be disabled.

Hope that helps abit

**Comment by retrooper** [comment]
Weird i wasn’t able to reproduce, i’ll try again tomorrow

**Comment by Boy0000** [comment]
Ping me on Discord if you want a JAR file for the plugin there for emotes.
Think i linked the source-code aswell if you rather wanna build it yourself
Dont think the issue is exclusive to it but not entirely sure 👍

**Comment by retrooper** [comment]
I've tested again on my 1.19 server with PacketEvents and ProtocolLib and Via and some more stuff, still can't reproduce?

**Comment by Boy0000** [comment]
Havent tested this on 1.19, but did you also have network compression disabled on the server?

**Comment by retrooper** [comment]
Yes, that is indeed the name of the issue?

**Comment by Boy0000** [comment]
seems to be fixed, thanks lol
