### ISSUE TITLE
Injection Issue

### ISSUE THREAD

**Issue by jtJava** [retrooper/packetevents#417]
**Describe the bug*
failure to inject

**Software brand**
Spigot 1.8.8 and NachoSpigot 1.8.8

**Plugins**

**How To Reproduce**
I was unable to reproduce, it is a user of my plugin having this issue. 
![ACD7D8A9-4DD2-43AB-8951-AB1E535FB4A5](https://user-images.githubusercontent.com/37258614/171983918-c37f3ae9-5e4f-48b9-ba98-9c8c62c63d72.png)
![F052A1A3-F3D2-4A76-9D14-7DA93E909EA6](https://user-images.githubusercontent.com/37258614/171984434-4dd05d22-17b2-476b-8354-954901418d18.png)

**Expected behavior**
no exception

**Additional context**
https://pastebin.com/AjpmR8k3

**Comment by retrooper** [comment]
Check the "late-bind" value in the config on both, what is it?

**Comment by ilovefuud** [comment]
I thought I responded but everything is the same in both @retrooper

**Comment by ilovefuud** [comment]
He left my discord server so I can't give anymore information on the error.

**Comment by MWHunter** [comment]
Closing due to rewritten injector
