### ISSUE TITLE
Give access to ItemStack#getEnchantmentsTagName

### ISSUE THREAD

**Issue by ilovefuud** [retrooper/packetevents#420]
**Is your feature request related to a problem? Please describe.**
In my plugin I have crasher checks that look at the NBT of creative items. One of them looks at enchants, which is different per version. It would be nice if I could use the getEnchantmentsTagName method.

**Describe the solution you'd like**
private -> public

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
Right now I am doing the following:
![image](https://user-images.githubusercontent.com/37258614/172076816-4d4e0904-1874-4b5e-a3e6-402331d89ef8.png)

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/055f473964fe443bf2c4117d2ac3c0a9adc47105
