### ISSUE TITLE
PEVersion NumberFormatException

### ISSUE THREAD

**Issue by ilovefuud** [retrooper/packetevents#421]
https://github.com/retrooper/packetevents/blob/b4ad4e831dd69a368ac9ccccc8edbf7026529347/spigot/src/main/java/io/github/retrooper/packetevents/factory/spigot/SpigotPacketEventsBuilder.java#L187

NumberFormatException when using the ProtocolSupport version for 1.8.8 because it contains "dev" in the version

![image](https://user-images.githubusercontent.com/37258614/172149443-0e468452-9fcc-4583-83f1-c950d8929675.png)

**Comment by Jaren8r** [comment]
Judging by the surrounding code, it doesn't look like packetevents is compatible with it anyways

**Comment by retrooper** [comment]
I know this isn't the ideal or cleanest solution, but hopefully works. https://github.com/retrooper/packetevents/commit/18a1d51c19e7d0578d8f90dad120cc959a8d7c55
