### ISSUE TITLE
Copyright update

### ISSUE THREAD

**Issue by NoJokeFNA** [retrooper/packetevents#426]
We should update the Copyrights year from `2021` to `2021-2022` as we are not always in year 2021.

**Comment by MWHunter** [comment]
Copyright statement's aren't technically required by GPL, only suggested  However, I like the idea of letting people credit themselves in classes they make.

I'd suggest putting the year that files were created as their copyright date, and not touching them after.  That way, in a while from now, we can know if any system is really out of date for modern coding standards as java improves as even current classes are terrible by coding standards.  PE 1.8 is worse, at least.
