### ISSUE TITLE
NoClassDefFoundError exception

### ISSUE THREAD

**Issue by NoJokeFNA** [retrooper/packetevents#430]
**Describe the bug**
After entering the Nether through the portal, an exception is thrown.

**Software brand**
Paper 1.19 (latest)

**Plugins**
Only PE 2.0 (using latest update from 2.0 branch)

**How To Reproduce**
1. Go through a Nether Portal

**Additional context**
Logs: https://paste.gg/p/anonymous/92a7222f6fc64eeeb77ebe6a13ad0d7d

Code:
```java
    public static PacketTypeCommon getById(PacketSide side, ConnectionState state, ClientVersion version, int packetID) {
        switch (state) {
            case HANDSHAKING:
                if (side == PacketSide.CLIENT) {
                    return PacketType.Handshaking.Client.getById(packetID);
                } else {
                    return PacketType.Handshaking.Server.getById(packetID);
                }
            case STATUS:
                if (side == PacketSide.CLIENT) {
                    return Status.Client.getById(packetID); <-----
                } else {
                    return Status.Server.getById(packetID);
                }
            case LOGIN:
                if (side == PacketSide.CLIENT) {
                    return Login.Client.getById(packetID);
                } else {
                    return Login.Server.getById(packetID);
                }
            case PLAY:
                if (side == PacketSide.CLIENT) {
                    return Play.Client.getById(version, packetID);
                } else {
                    return Play.Server.getById(version, packetID);
                }
            default:
                return null;
        }
    }
```

**Comment by MWHunter** [comment]
There's no clientside STATUS packets, although I don't know why PE is failing to transition into the PLAY state

**Comment by NoJokeFNA** [comment]
🤷‍♂️

**Comment by NoJokeFNA** [comment]
Same with end portal
https://paste.gg/p/anonymous/ce99949a9f804ee58e5fd24ce733e263

**Comment by MWHunter** [comment]
Did you delete or replace the jar when the server was running?

**Comment by NoJokeFNA** [comment]
Yea, I did replace it. Though it's somehow confusing why only this one thing is bugging but it's working after a clear restart.

**Comment by MWHunter** [comment]
All the other classes were already loaded into memory, while new classes that haven't been called before must be read from disk
