### ISSUE TITLE
Handshake IndexOutOfBoundsException

### ISSUE THREAD

**Issue by StrafeJT** [retrooper/packetevents#438]
**Describe the bug**
[07:10:38 WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex: 47 (expected: 0 <= readerIndex <= writerIndex(3))

**Software brand**
SportPaper 1.8.8

**Plugins**
ViaVersion ViaRewind

**How To Reproduce**
Person using my plugin has no idea how to reproduce it.

**Expected behavior**
No exception

**Additional context**
[Add any other context about the problem here.](https://pastebin.com/bRrrxvnM)
https://pastebin.com/eKhjSydE

**Comment by NoJokeFNA** [comment]
Well that's bad

**Comment by retrooper** [comment]
Fixed
