### ISSUE TITLE
Unable to join server

### ISSUE THREAD

**Issue by scarfacered** [retrooper/packetevents#440]
**Describe the bug**
https://pastebin.com/raw/TwXTj5qX

**Software brand**
Paper 1.19

**Plugins**
ViaVersion, ViaBackwards

**How To Reproduce**
Connect to 1.19 server

**Comment by scarfacered** [comment]
I believe this caused it
https://github.com/retrooper/packetevents/commit/5f49f63e8fad548ebeb5ef7a58a2bacb1d7644c5#diff-6e61ed83ab8d18aa7c13046c2cb4db8354217fb1ef7b1745b5f4f8227cbef7e9R55

**Comment by scarfacered** [comment]
> The size is complete different so it wouldn't make that much sense

https://github.com/retrooper/packetevents/blob/5f49f63e8fad548ebeb5ef7a58a2bacb1d7644c5/api/src/main/java/com/github/retrooper/packetevents/wrapper/PacketWrapper.java#L367

It's multiplied by 4 here? 255 * 4 = 1020, which is what you're seeing in that error log. I'm not sure how my serverAddress is longer than 255 letters, though. It's behind Velocity? I'd be curious to see the string it's trying to parse.

**Comment by retrooper** [comment]
So is this issue resolved?

**Comment by retrooper** [comment]
I'm gonna mark it as solved then...
