### ISSUE TITLE
Ability to alter chat verification popup

### ISSUE THREAD

**Issue by PikaMug** [retrooper/packetevents#454]
**Is your feature request related to a problem? Please describe.**
Curious if it's possible to change the text of the new 1.19.1 toast (on the 2.0 branch).

**Describe the solution you'd like**
Being able to replace the text from server.

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
Server mod (using packetevents): https://www.spigotmc.org/resources/103782/
Client mod: https://www.curseforge.com/minecraft/mc-mods/disable-insecure-chat-toast

Neither purports to be able to modify the toast, but I've seen no concrete evidence that either could not.

**Additional context**
![chat_verif](https://user-images.githubusercontent.com/2267126/181908144-88e6de21-5d68-4de7-aad0-7719966e9a17.png)

**Comment by KaspianDev** [comment]
@retrooper i will be also interested in that one

**Comment by retrooper** [comment]
This seems less like a feature request and more like a question which you could've asked in my discord.

**Comment by retrooper** [comment]
Anyway, uh according to my testing and debugging, I've noticed cancelling the PacketType.Play.Server.SERVER_DATA on 1.19.1 will prevent that popup from showing up. You can test on 1.19.0 if you want and if the protocol translation plugins like ViaVersion will handle it right.

**Comment by KaspianDev** [comment]
@retrooper OP wants to change text in the popup
