### ISSUE TITLE
WrapperPlayServerChatMessage Kicks Players

### ISSUE THREAD

**Issue by KaspianDev** [retrooper/packetevents#456]
### Observed/Actual behavior

Players get kicked with message below:
![image](https://user-images.githubusercontent.com/34658474/182598575-2e9ea527-f983-45ba-930c-896bb2326bee.png)

### Steps/models to reproduce

I made a plugin jar that reproduces the issue easily [here](https://github.com/KaspianDev/paper-issue)

so
1. Install plugin above
2. Install a chat plugin (tested on essentialxchat and LPC)
3. Start the server
4. Join and send a message, you will get kicked

### Plugin and Datapack List

[13:39:52 INFO]: Plugins (3): LPC, LuckPerms, PE

[13:40:03 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[13:40:03 INFO]: There are no more data packs available

### Software

[13:51:22 INFO]: This server is running Paper version git-Paper-104 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 7044a9c)
You are running the latest version

### Other

its related to this line https://github.com/KaspianDev/paper-issue/blob/master/src/main/java/paper/bug/pe/PacketEventsListener.java#L13

edit: only related to paper, and only if using a chat format plugin, like LPC for this example

**Comment by derklaro** [comment]
Is there no proper error message logged to the server console?

**Comment by KaspianDev** [comment]
> Is there no proper error message logged to the server console?

The same what player sees, 
Internal Exception: io.netty.handler.codec.EncoderException: screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to process outgoing packet

**Comment by KaspianDev** [comment]
Fixed in recent builds
