### ISSUE TITLE
Viaversion Incompability

### ISSUE THREAD

**Issue by KaspianDev** [retrooper/packetevents#457]
**Describe the bug**
Players get kicked when using packetevents on 1.19.1 combined with viaversion.

**Software brand**
Paper 1.19.1

**Plugins**
Eg. ViaVersion, ViaBackwards, LPC, Luckperms, AntiPopup

**How To Reproduce**

1. Create a 1.19.1 server with viaversion + backwards
2. Install AntiPopup
3. Try to join the server
4. You get kicked + error

**Screenshots**
![image](https://user-images.githubusercontent.com/34658474/182690484-a3a0b365-055c-4acf-863d-b9407fcdc6e1.png)

**Error**
https://paste.md-5.net/jabipoliso.cs

**Comment by retrooper** [comment]
I can join my 1.19.1 paper server with a 1.19.0 client just fine?

**Comment by retrooper** [comment]
Even with latest version of Antipopup, I can join.

**Comment by retrooper** [comment]
I see, if I combine latest packetevents 2.0 with antipopup it fails, but antipopup itself alone fails.

**Comment by retrooper** [comment]
Following step 4 fixed it: https://github.com/retrooper/packetevents/wiki/Shading-PacketEvents#step-4---only-applies-to-the-spigot-module
