### ISSUE TITLE
Unable to join

### ISSUE THREAD

**Issue by ChromMob** [retrooper/packetevents#458]
**Describe the bug**
On join:
https://pastes.dev/tn1XvhoOgL

**Software brand**
Paper 1.19

**Plugins**
Plugins (8): floodgate, Geyser-Spigot, LuckPerms, MyPlugin, spark, ViaBackwards, ViaRewind, ViaVersion

**How To Reproduce**
*Example:*
1. Join with the 1.18.2 vanilla client

**Expected behavior**
Being able to join

**Comment by KaspianDev** [comment]
@ChromMob is it good when you remove viaversion?

**Comment by KaspianDev** [comment]
Very possibly related to #457

**Comment by ChromMob** [comment]
> @ChromMob is it good when you remove viaversion?

Will try.

**Comment by ChromMob** [comment]
Just tested happens only with ViaVersion

**Comment by retrooper** [comment]
Follow step 4 and tell me if it fixes it: https://github.com/retrooper/packetevents/wiki/Shading-PacketEvents#step-4---only-applies-to-the-spigot-module

**Comment by ChromMob** [comment]
Solved by following guide https://github.com/retrooper/packetevents/wiki/Shading-PacketEvents#step-4---only-applies-to-the-spigot-module
