### ISSUE TITLE
Wrapper errors on 1.8

### ISSUE THREAD

**Issue by iTzLucky28** [retrooper/packetevents#460]
**Describe the bug**
An error which occur everytime a wrapper object is created from the event
For now only noticed WrapperPlayServerSpawnLivingEntity and WrapperPlayServerEntityMetadata

**Software brand**
Spigot 1.8.8, PacketEvent version: 2.0.0-SNAPSHOT

**Plugins**
ViaVersion 4.1.1
World Edit

**How To Reproduce**
*Example:*
1. Join with the 1.8.9 minecraft client.
2. Every time these packets will be sent (Spawn living entity and entity metadata) and you try to wrap them error happen

**Additional context**
[https://hastebin.com/cevugewuka.sql](url)

**Comment by retrooper** [comment]
This was very likely fixed.
