### ISSUE TITLE
Error joining 1.18.2 server with 1.8

### ISSUE THREAD

**Issue by iTzLucky28** [retrooper/packetevents#461]
**Describe the bug**
When joining a 1.18.2 server with 1.8.9 client an error occur and kick the player immediately.
This issue will hapen even if no packet listeners were registered, It happen even if you only build, load and init PacketEvents.

**Software brand**
Please let us know what software you are using.
Purpur-1587 (MC: 1.18.2)
Using PacketEvent 2.0.0-SNAPSHOT

**Plugins**
FAWE 2.0.2
ViaBackwards 4.4.1
ViaRewind 2.0.2
ViaVersion 4.4.1

**How To Reproduce**
1. Join with the 1.8.9 client on 1.18.2 server

**Additional context**
[https://hastebin.com/avajinewav.yaml](url)

**Comment by iTzLucky28** [comment]
Forgot to mention that i use 2.0.0-SNAPSHOT

**Comment by retrooper** [comment]
Follow step 4 in our newly written shading wiki and it should fix this: https://github.com/retrooper/packetevents/wiki/Shading-PacketEvents#step-4---only-applies-to-the-spigot-module
