### ISSUE TITLE
ServerVersion cleanup

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#462]
It resolved V_1_19_2 to V_1_19 instead of V_1_19_1 which didn't need to happen.  All the methods can also be constant time.  UNKNOWN also isn't a used enum value.

**Comment by retrooper** [comment]
“It resolved V_1_19_2 to V_1_19 instead of V_1_19_1 which didn't need to happen” What do you mean?

**Comment by retrooper** [comment]
Detecting server versions should be accurate and not say 1.19 on a 1.19.2 server if ai interpret your message correctly

**Comment by MWHunter** [comment]
I'm saying, if 1.19.3 is released with no protocol changes, it will resolve to 1.19 instead of 1.19.3 and break things.

It should resolve to 1.19.2 instead.

**Comment by retrooper** [comment]
That is true, and is something I considered
