### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by AVuTuVA** [retrooper/packetevents#463]
**Describe the bug**
Spam in console

**Software brand**
Pufferfish 1.18.2

**Plugins**
![image](https://user-images.githubusercontent.com/66278054/183289812-902804ee-3b95-4fcf-be51-6823f5f7eaa8.png)

**How To Reproduce**
I don't know

**Expected behavior**
I expect there will be no spam in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/66278054/183289982-a991e668-0110-4738-8033-4ec827dbe4e2.png)

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/dc614c96c3a40d97ec036112733a43b5d5ed8c39
