### ISSUE TITLE
Error when joining/playing with 1.8.9 client on 1.18.2 server

### ISSUE THREAD

**Issue by iTzLucky28** [retrooper/packetevents#464]
Describe the bug
When joining a 1.18.2 server with 1.8.9 client an error occur and kick the player, it can also happen sometimes when playing.
This issue will NOT hapen if no packet listeners were registered.

Software brand
Purpur-1587 (MC: 1.18.2)
Using PacketEvent 2.0.0-SNAPSHOT

Plugins
FAWE 2.0.2
ViaBackwards 4.4.1
ViaRewind 2.0.2
ViaVersion 4.4.1

Join with the 1.8.9 client on 1.18.2 server

Additional context
https://pastebin.com/x2uPGBma

**Comment by retrooper** [comment]
The hastebin expired.

**Comment by retrooper** [comment]
I think we resolved this, you weren't loading packetevents correctly.
