### ISSUE TITLE
Exception on player join and got kicked

### ISSUE THREAD

**Issue by caoli5288** [retrooper/packetevents#466]
**Describe the bug**
Exception on player join and got kicked

**Software brand**
Server: paper-1.8.8
Client: 1.12.2

**Plugins**
Plugins (3): ViaVersion, ProtocolLib, GrimAC

**How To Reproduce**
1. Join
2. Spam

**Additional context**
See logs file below

[latest.log](https://github.com/retrooper/packetevents/files/9286391/latest.log)

**Comment by retrooper** [comment]
I can not reproduce, so I assume this is not consistent?

**Comment by retrooper** [comment]
Have you tried updating all the ViaVersion plugins?

**Comment by retrooper** [comment]
I've made a commit attempting to fix the first exception, if you can inform Grim and tell them to update, and see if it fixes on your server. Or contact me on discord so we can test on your server. https://github.com/retrooper/packetevents/commit/c44e834c01ed06ef410ff56a72dbaf82fbecb7c0

**Comment by caoli5288** [comment]
👍
