### ISSUE TITLE
Errors on 1.12.2 on Tab Complete

### ISSUE THREAD

**Issue by SkyLicks** [retrooper/packetevents#467]
**Describe the bug**
Errors in console on Tab Completion

**Software brand**
Paper Spigot 1.12.2

**Plugins**
ProtocolLib 5.0, Viaversion 4.4.1 (with via Backwards), Karhu, SurveyPlus, Essentials+ bunch of custom plugins

Edit: The issue only happens when Karhu is enabled @LIWKK.

**How To Reproduce**
*Example:*
1. Setup a Paper Spigot 1.12.2 Server
2. Download latest versions of Protocol Lib and Viaversion
3. Login with a 1.12.2 client
4. Try to tab complete any command

**Expected behavior**
The error shouldn't happen

**Screenshots**
![image](https://user-images.githubusercontent.com/34877092/184550981-9f8cefb9-36fa-4389-884d-38983643aaed.png)

**Additional context**

**Comment by LIWKK** [comment]
![kuva](https://user-images.githubusercontent.com/35636315/184553597-9110f825-fcea-4b59-b09f-9e24b369102d.png)
And this is how the wrapper is used

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/4273bf65874626957bb264a78a948000a2ea5d82
