### ISSUE TITLE
Download link for 2.0

### ISSUE THREAD

**Issue by sujyrokimora** [retrooper/packetevents#470]
Hello
I cant find the download link for the beta version neither i cant compile it myself

**Comment by jtJava** [comment]
https://github.com/retrooper/packetevents/suites/7860329125/artifacts/333137994

**Comment by amnoah** [comment]
Also the download link; https://ci.codemc.io/job/retrooper/job/packetevents/lastBuild/

**Comment by sujyrokimora** [comment]
Thanks
