### ISSUE TITLE
PacketEvents doesn't load if getBukkitVersion returns "Unknown-Version"

### ISSUE THREAD

**Issue by jtJava** [retrooper/packetevents#471]
**Describe the bug**
The plugin does not load on server's where Bukkit.getBukkitVersion() returns "Unknown-Version"
![image](https://user-images.githubusercontent.com/37258614/185770238-6abdf9d9-3736-4654-b352-afcf88035788.png)

**Software brand**
Custom fork of Paper 1.8

**Plugins**
Not relevant

**How To Reproduce**
Not sure how to reproduce

**Expected behavior**
My plugin to load

**Screenshots**
@ top of issue.

**Additional context**

**Comment by MWHunter** [comment]
Who the fuck puts "Unknown" as the bukkit version?

**Comment by jtJava** [comment]
No one, it's just due to not changing this String when repackaging
![image](https://user-images.githubusercontent.com/37258614/185770630-f4bd0083-46a8-47cc-8389-104ced17d9cc.png)

**Comment by MWHunter** [comment]
PacketEvents has no chance at reading packets correctly when it is like this.  We could look at the protocol version with reflection though like via does to get a server version.

**Comment by retrooper** [comment]
With protocol version we lose accuracy at server version. Right now the intended behavior for such cases was to assume its 1.8 as it was more common on 1.8 forks.

**Comment by DevDrizzy** [comment]
> No one, it's just due to not changing this String when repackaging ![image](https://user-images.githubusercontent.com/37258614/185770630-f4bd0083-46a8-47cc-8389-104ced17d9cc.png)

If anyone is having that problem, that means they changed groupId and artifactId in pom.xml. They just have to replace it with their own. If they aren't, then that's just stupid, it shouldn't be the PacketEvents developer's fault.

**Comment by retrooper** [comment]
Although I have fixed the issue, you should definitely fix it on your end too as DevDrizzy is saying. To people questioning why I fixed it, it was already "fixed" on my end before just I broke that fix recently with another change.
https://github.com/retrooper/packetevents/commit/ea32d28d0b5e2855c497252459eaf4122d97e7fc
