### ISSUE TITLE
WrapperPlayServerSpawnEntity kicks players

### ISSUE THREAD

**Issue by KaspianDev** [retrooper/packetevents#475]
**Describe the bug**
WrapperPlayServerSpawnEntity kicks player on join

**Software brand**
Spigot 1.19.2

**Plugins**
My test plugin

**How To Reproduce**
1. Create new WrapperPlayServerSpawnEntity() in event handler
2. Try to join the server

**Screenshots**
![image](https://user-images.githubusercontent.com/34658474/187300602-cbe2dd58-ab16-4569-bd30-e61bf1efb2e0.png)

**Comment by MWHunter** [comment]
if (event.getPacketType() == PacketType.Play.Server.SPAWN_ENTITY) {
                    WrapperPlayServerSpawnEntity entity = new WrapperPlayServerSpawnEntity(event);\
               }

works fine for me
