### ISSUE TITLE
No packet mappings for 85, 98 (1.19.2 client -> 1.8.8 server)

### ISSUE THREAD

**Issue by GrowlyX** [retrooper/packetevents#478]
**Describe the bug**

**Software brand**
Custom 1.8.8.

**Plugins**
[Titanium](https://github.com/jtJava/Titanium)

**How To Reproduce**
*Example:*
1. Join with a 1.19.2 Minecraft client.

**Expected behavior**
Player is able to join.

**Screenshots**
```
io.netty.handler.codec.EncoderException: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 85 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.8.8
io.netty.handler.codec.EncoderException: com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 98 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.8.8
```

**Additional context**
N/A

**Comment by jtJava** [comment]
Works fine for me, try rebuilding the project for latest PacketEvents?
![image](https://user-images.githubusercontent.com/37258614/190931673-f2dd470a-cbc5-40d9-8754-8049285c2d1f.png)

**Comment by GrowlyX** [comment]
> Works fine for me, try rebuilding the project for latest PacketEvents? ![image](https://user-images.githubusercontent.com/37258614/190931673-f2dd470a-cbc5-40d9-8754-8049285c2d1f.png)

Thanks for the response, it seemed to be an issue with our server software rather than PacketEvents itself. PacketEvents works fine after reverting a change applied to our spigot fork.
