### ISSUE TITLE
Sporadic IndexOutOfBoundsException at ByteBufOperatorModernImpl.toString()

### ISSUE THREAD

**Issue by velnias75** [retrooper/packetevents#479]
**Describe the bug**
The developer of *AntiPopup* asked me to forward this bug https://github.com/KaspianDev/AntiPopup/issues/14#issuecomment-1253866989 to you.

**Software brand**
This server is running Paper version git-Paper-161 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 9e614e6)

**Plugins**
Plugins (23): **AntiPopup**, DiscordSRV, dynmap, EzHomes, Graves, Images, JoinMessage, LuckPerms, NoMobGriefing, PangaeaBlocks, PhatLoots, PinkBull, ProtocolLib, RainManNG, RHSignItem, SEC, ServerBackup, spark, TAB, TABWorldDate, ViewDistanceTweaks, VipSlot*, XItemsRemover

**How To Reproduce**
There is no clear way to reproduce.
I find the huge *staccktrace* in my logs at least once a day after the server being idle (no players) fpr some hours.

**Expected behavior**
No *stacktrace* (and what it may cause further, since I restart the server if I see it in the log)

**Screenshots**
Actually a Gist with the *stacktrace*: https://gist.github.com/velnias75/ea8bd4ad5de0aac3fddbb43604bf9369

**Additional context**

**Comment by c0dingnoobi** [comment]
Can confirm, same stacktrace on 1.19 when server is idling

- GrimAC
- Spark
- Server 1.19.2 Paper

**Comment by retrooper** [comment]
Probably been fixed
