### ISSUE TITLE
Error loading NBT world data on proxy platforms

### ISSUE THREAD

**Issue by sBwAeBeYt** [retrooper/packetevents#485]
**Describe the bug**
When connecting to Velocity and connecting to the destination server, an error occurs loading NBT world data.

**Software brand**
Velocity 3.1.2-SNAPSHOT and PacketEvents 2.0-SNAPSHOT.

**Plugins**
LuckPerms, Spark, PacketEvents.

**How To Reproduce**
1. Joining with vanilla Minecraft client from any version since 1.16

**Expected behavior**
Throws a DecoderException in the client: z: Loading NBT data and in console throws exception on screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/73953747/198455088-7e9f6897-3ff2-4ff4-929d-114be6fc7489.png)

**Comment by MWHunter** [comment]
I can't tell if the protocol requires you to set the dimension type registry, or if minecraft will put default values there for you

**Comment by MWHunter** [comment]
yeah, it's required.  My guess is that "effects" in dimensions attributes isn't a valid place to grab the dimension type

**Comment by MWHunter** [comment]
unable to reproduce.  works fine connecting from a 1.19.3 client onto a 1.8 server
