### ISSUE TITLE
java.lang.IndexOutOfBoundsException: readerIndex: 38 (expected: 0 <= readerIndex <= writerIndex(26))

### ISSUE THREAD

**Issue by Pvpgamerr** [retrooper/packetevents#487]
**Describe the bug**
When a player joins the server with 1.17 client the server throws an error then kicks the player with the reason "disconnected"

**Software brand**
Paper 1.8.8

**Plugins**

1v1 (custom), ActionBarAPI, AdvancedClansAntiAdvertiser, AntiDisconnectSpam, AntiWeather, AuthMe, AutoRespawnPlus, BlueSlimeCore, BountyHunters, ChatControl, Citizens, ClansAddon (custom), ClearLag, CombatTagAddon (custom), CommandNPC, CommandRewriter, commandspy, ConsoleSpamFix, CooldownsX, CraftingStore, CrazyCrates, CyberLevels, DeluxeMenus, Duels, Effect (custom), EnderBanV1, EssentialsX 2.18.2, EssentialsXChat 2.18.2, EssentialsXSpawn 2.18.2, FastAsyncWorldedit, gProtector, GrimAC, HolographicDisplays, HolographicExtension, NBTAPI, JoinSpawn, killStats, KnockbackMaster, LiteBans, LPX, LuckPerms, mTopKills, MultiverseCore, MultiverseInventories, MultiversePortals, NoDeathDrops, PAC, PlaceholderAPI, PlugMan, PluginHiderPlus, ProtocolLib 5.0, PvPManager, SimpleTrading, SkQuery, Skellett, SkinsRestorer, Skript, SpigotGuard 6.5.1, Suffix (custom), TAB, TitleManager, TuSKe, Vault, ViaChatFixer, ViaVersion 4.4.2, Void2Spawn, VoidGen, Vouchers, Vulcan, WorldEdit, WorldGuardExtraFlags, WorldGuard, zAuctionHouse

**How To Reproduce**
1. Join with the 1.17.x vanilla minecraft client.
2. player gets kicked 

**Expected behavior**
let 1.8 -  1.19 players join the server without any errors and kicks

**Screenshots**
https://pastebin.com/8b3y7CXt

**Additional context**

**Comment by MWHunter** [comment]
Reopen if still a problem with the rewritten injector
