### ISSUE TITLE
Add a way to get the raw nms packet object from event in 2.0

### ISSUE THREAD

**Issue by stonar96** [retrooper/packetevents#489]
**Is your feature request related to a problem? Please describe.**
It seems like there is no way in 2.0 to get the raw nms packet object from event (e.g. `PacketPlaySendEvent`). This is possible with previous versions of PacketEvents and also with ProtocolLib. Imho a "packet event" should provide a way to get the actual packet.

**Describe the solution you'd like**
A similar solution as in previous versions of PacketEvents or in ProtocolLib.

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
For the most part I understand that the raw nms packet object isn't necessary, e.g. for reading, modifying or canceling packets. If a raw nms packet object is needed, one could also simple recreate it. However, I think that there are some situations, where it can be useful to work with raw nms packet objects (without having to recreate them) and even situation where it's necessary (see below). For those situations the only alternative is to use either a previous version of PacketEvents or to use ProtocolLib.

**Additional context**
First of all, I have to admit that my use case is rather niche and maybe too complicated to fully describe it here. There are probably better examples, however, I'll try to explain it briefly. Basically I'm hooking into the chunk packet at two different stages. First when the chunk packet is created and modified by Anti-Xray. At this stage some context is created that I have to store into a weak key `Map<Packet, Context>` in order to be able to use this context in the second stage, the `PacketPlaySendEvent` listener, when the packet is ready to be sent to multiple players (unknown in the first stage). To uniquely identify the chunk packet and retrieve the context from the map in the second stage, I need the raw nms packet object.

**Comment by Tofaa2** [comment]
PacketEvents 2.0 strives to be a completely not spigot dependant service. I see no reason it should contain nms packets

**Comment by stonar96** [comment]
It can simple return an object (as it was in previous versions). This could still work completely platform independent.

**Comment by Tofaa2** [comment]
That doesnt sound like it would be simple, the spigot system would need to be rewritten alot and need a way to parse and create the nms packet's data

**Comment by stonar96** [comment]
I'm not sure why anything must be parsed or created. Why wouldn't it be possible to just pass `Object o` to the event [here](https://github.com/retrooper/packetevents/blob/2.0/spigot/src/main/java/io/github/retrooper/packetevents/injector/handlers/PacketEventsEncoder.java#L53). (Sorry, I'm not sure if this is even the right place to look at, since I'm not experienced with this project's code base.)

**Comment by AbhigyaKrishna** [comment]
2.0 creates its own packet system. Sending and receiving packets directly to netty channel without any interaction of the minecraft packet system. You could create a nms packet object by creating packet data serializer and passing it to nms packet constructor/method iirc.
```java
PacketDataSerializer serializer = new PacketDataSerializer(packet.getBuffer());

// Newer version
SomePacket nmsPacket = new SomePacket(serializer);

// Older version
SomePacket nmsPacket = new SomePacket();
nmsPacket.b(serializer);
```

**Comment by stonar96** [comment]
Yeah, as I said above, as an alternative:

> If a raw nms packet object is needed, one could also simple recreate it. However, ...

Thank's for providing an example for it. However, I still think there are good reasons to add a way to get the original packet object:

1. It's simpler than recreating it.
2. Making a copy can be avoided. Recreating many large packets (e.g. chunk packets) allocates memory and can get resource intensive.
3. A copy is just a copy and not the original. One can use the origianl object to uniquely identify a sent packet by reference equality. (For an example see my additional context above.)

**Comment by AbhigyaKrishna** [comment]
But the point here is that the raw nms packet object which you need was never created by packet events. Packet event always deserialized the packet data buffer to its own object. If you need raw nms object you need to deserialize the buffer into the nms object. Alternatively, getting it from minecraft packet injector.

**Comment by stonar96** [comment]
> Why wouldn't it be possible to just pass `Object o` to the event [here](https://github.com/retrooper/packetevents/blob/2.0/spigot/src/main/java/io/github/retrooper/packetevents/injector/handlers/PacketEventsEncoder.java#L53).

Okay, I've done some debugging here myself now and it turns out that I was under the wrong impression that `Object o` is always the raw nms packet object. For some reason this is only the case for the first few packets and then it's some byte buffer. Thus, as you said, it's probably not so easy.

Since I'm not familiar with the internals of this project I'll leave this issue open for someone to confirm that it's not that simple and close it.

**Comment by retrooper** [comment]
2.0 PacketEvents is a replacement for NMS and cannot give you the original NMS object since we were never handed it. We are given the buffer. 1.8 PacketEvents can give you that, although I don't recommend switching to an older version, if you urgently need that, go that way. I cannot guarantee how much longer 1.8 packetevents will stay alive.

**Comment by retrooper** [comment]
Since 2.0 can operate without this NMS object we are able to run on more platforms than just Spigot, allowing us to even write server/clients from scratch using packetevents. Or even proxy plugins or client mods.
