### ISSUE TITLE
PacketType.Play.Server.PARTICLE - Server kick

### ISSUE THREAD

**Issue by Aseeef** [retrooper/packetevents#490]
**Describe the bug**
The bug has something to do with PacketType.Play.Server.PARTICLE. The simple act to listening to this packet and invoking new WrapperPlayServerParticle(event) causes all clients whom this packet is being sent to, to be disconnected from the server when the sent packet is the block particle packet.
![image](https://user-images.githubusercontent.com/74121396/202881955-4c717695-c1db-4672-b9d7-8c82c1bd0139.png)
Perhaps this has something to do with that data field?

**Software brand**
Paper Spigot 1.12.2

**Plugins**
N/A - Private/Custom plugins, so giving this won't help.

**How To Reproduce**
1. Register a packet listener with the following code.
`
@Override
    //todo: bug, player can see vanish player on login
    public void onPacketSend(PacketSendEvent event) {
       if (event.getPacketType() == PacketType.Play.Server.PARTICLE) {
                WrapperPlayServerSoundEffect particle= new WrapperPlayServerParticle(event);
       }
    }
`
2. Get an alt on, and jump from really high up. When this happens, the alt should receive these particles
![image](https://user-images.githubusercontent.com/74121396/202882746-4ad82dbf-55c3-45f3-8d05-c09d1e9ddd62.png)
3. But... if the new WrapperPlayServerSoundEffect(event) line was executed from step 1, the alt will be kicked from the server. Attempting to print particle.getParticle() will show a null particle.

**Expected behavior**
The expected behavior is to not crash and to not have a null particle.

**Screenshots**

**Additional context**

**Comment by Aseeef** [comment]
The particle id with the bug is 38 and its called blockdust.
![image](https://user-images.githubusercontent.com/74121396/203863714-383ccce5-c9ec-4eb0-8129-c45319b6b2f2.png)
https://wiki.vg/index.php?title=Protocol&oldid=13488#Particle_2

**Comment by MWHunter** [comment]
I'm not willing to maintain Particle mappings for all these server versions.  Maybe someone else is willing to do this.

**Comment by booky10** [comment]
I can't reproduce this with a 1.12.2 server, has apparently been fixed
