### ISSUE TITLE
Crash with viaversion dev 100%

### ISSUE THREAD

**Issue by F3F5** [retrooper/packetevents#491]
### Stack trace

https://github.com/GrimAnticheat/Grim/issues/721

error https://pastebin.com/EpAaVxRr

### How to replicate it if known

Install
Join = kicks, not works anticheat

### Grim version

Grim:  2.3.24 dev version(today gradle shadowjar)
https://ci.viaversion.com/job/ViaVersion-DEV/757/
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by MWHunter** [comment]
Fixed on 2.0
