### ISSUE TITLE
PacketEvents error on connect

### ISSUE THREAD

**Issue by scarfacered** [retrooper/packetevents#495]
**Describe the bug**

PacketEvents failed to find a ByteToMessageDecoder indexed 0 by its type in the net.minecraft.network.PacketDecoder class!

Error connecting with latest ViaVersion 4.5.0 - https://pastebin.com/raw/fg6GkQjK

**Software brand**
Paper 1.19.2

**Plugins**
Grim, ViaVersion 4.5.0

**How To Reproduce**
1. Join with the 1.19.2 vanilla minecraft client.
2. See error

**Additional context**
Might be related? https://github.com/ViaVersion/ViaVersion/commit/c5738a2203cf29e3eff6ece1e881249a99782b10

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/2c756925a1056e721a563af1d981f27dde8e8eb3
