### ISSUE TITLE
Getting kicked on latest Packet Events Build (1.8.8 Server)

### ISSUE THREAD

**Issue by Bufferless** [retrooper/packetevents#500]
**Describe the bug**
Getting kicked for Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex: 18 (expected: 0 <= readerIndex <= writerIndex(11))

**Software brand**
Paper Spigot 1.8.8

**Plugins**
ViaVersion 4.5.0, and a PacketEvents plugin

**How To Reproduce**
1. Use the latest packet events 2.0 build
2. Join a 1.8 server 

**Expected behavior**
Join the server properly with the latest 2.0 Packet Events build.

**Comment by MWHunter** [comment]
which packetevents plugin?  How do you know it's latest?
