### ISSUE TITLE
Can't print WrapperPlayServerJoinGame#getDimensionCodec() via NBTCodec#nbtToJson

### ISSUE THREAD

**Issue by SoSeDiK** [retrooper/packetevents#501]
**Describe the bug**
Using the following code:
```java
@Override
public void onPacketSend(PacketSendEvent event) {
	if (event.getPacketType() != PacketType.Play.Server.JOIN_GAME) return;

	var packet = new WrapperPlayServerJoinGame(event);
	getLogger().info("Codec: " + NBTCodec.nbtToJson(packet.getDimensionCodec(), true));
}
```
Produces IllegalStateException: https://pastebin.com/720B0T7X

**Software brand**
Purpur 1.19.2, build 1858.

**Expected behavior**
NBTCompound should convert to JsonElement.

**Additional context**
Would be neat to make nbt -> json string convertation as default behaviour for NBT#toString :)

**Comment by retrooper** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/7899d8cb46228470fea442531b5b425907cf84fc
