### ISSUE TITLE
WrapperPlayClientChatMessage throws error on 1.19.3

### ISSUE THREAD

**Issue by Coops0** [retrooper/packetevents#503]
**Describe the bug**
When wrapping a chat message on 1.19.3, the PlayClientChatMessage wrapper throws an error.
![image](https://user-images.githubusercontent.com/51346812/208267644-a0f0aba4-3e37-49d3-8acf-404d412b6a83.png)

**Software brand**
Paper 1.19.3

**How To Reproduce**
1. Wrap a chat message with WrapperPlayClientChatMessage in a plugin on 1.19.3
2. Send a chat message

**Comment by MWHunter** [comment]
Still an issue

**Comment by MWHunter** [comment]
fixed by https://github.com/retrooper/packetevents/commit/12c01eb2faa83199d73eb43282392be76999f051
