### ISSUE TITLE
Restart / Shutdown exception with 2.0.0

### ISSUE THREAD

**Issue by Skyslycer** [retrooper/packetevents#506]
**Describe the bug**
This is just something a user has reported and I wasn't able to reproduce it, nor had any others the issue (although there aren't many people using this plugin).
When restarting and the plugin starts to disable, the following message appears: https://pastebin.com/sGFHYQPb
This doesn't really affect anything but still, some people may think it did.
I'm not sure if it only happens when restarting but my guess is when shutting down too.

**Software brand**
Paper 1.19.2

**Plugins**
![grafik](https://user-images.githubusercontent.com/73074974/208707623-92d54180-7059-448a-b31d-2612e4287c64.png)

**How To Reproduce**
Wasn't able yet, as a user reported the issue and I wasn't able to reproduce it, but in theory:
- /restart

**Expected behavior**
No exception I guess.

**Additional context**

**Comment by Skyslycer** [comment]
It's this going to be taken a look at or not? It's not really nice to have players get exceptions from just restarting their server.
Sorry for my impatience, but the release date is coming closer every day and I don't want packetevents to cause a bad reputation again.

**Comment by Skyslycer** [comment]
Okay, so it just fixed itself. I'll still leave it out there for investigation.

**Comment by MWHunter** [comment]
"fixed" by https://github.com/retrooper/packetevents/commit/eb42c1b4732d93f283fafaf906fa35cc68190fb3

most likely an incompatibility with another plugin, doesn't seem to be possible with packetevents alone
