### ISSUE TITLE
1.19.3 Chat Kick Issue

### ISSUE THREAD

**Issue by Bufferless** [retrooper/packetevents#511]
**Describe the bug**
Getting kicked on a 1.19.3 Paper Spigot server with a PacketEvents plugin that modifies the WrapperPlayClientChatMessage and sets the message which leads to a kick

**Software brand**
Paper Spigot 1.19.3

**Plugins**
ViaVersion, PacketEvents Plugin

**How To Reproduce**
1. Have a 1.19.3 server
2. Modify the WrapperPlayClientChatMessage
3. Type in chat.

**Expected behavior**
Able to chat

**Screenshots**
![image](https://user-images.githubusercontent.com/87252860/209198903-c0fa8fb4-cfaf-497c-9827-843c94170548.png)

**Comment by Bob72648** [comment]
Astro AntiCheat Incompetency Issue.
