### ISSUE TITLE
[Question] About reflection

### ISSUE THREAD

**Issue by DeltaLimit** [retrooper/packetevents#518]
When I inject packetevents as an external lib using reflection, this error occurs

~~~txt
[20:46:46] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[20:46:46] [Server thread/WARN]: 	at com.github.retrooper.packetevents.util.MappingHelper.getJSONObject(MappingHelper.java:33)
[20:46:46] [Server thread/WARN]: 	at com.github.retrooper.packetevents.util.TypesBuilder.define(TypesBuilder.java:85)
[20:46:46] [Server thread/WARN]: 	at com.github.retrooper.packetevents.protocol.item.type.ItemTypes.define(ItemTypes.java:1233)
[20:46:46] [Server thread/WARN]: 	at com.github.retrooper.packetevents.protocol.item.type.ItemTypes$Builder.build(ItemTypes.java:1336)
[20:46:46] [Server thread/WARN]: 	at com.github.retrooper.packetevents.protocol.item.type.ItemTypes.<clinit>(ItemTypes.java:50)
[20:46:46] [Server thread/WARN]: 	... 12 more
~~~

Where should I put the assest folder?

**Comment by Tofaa2** [comment]
How are you injecting it, also could you be more specific as to what you're trying to do?

**Comment by DeltaLimit** [comment]
> How are you injecting it, also could you be more specific as to what you're trying to do?

I used this method to load the lib downloaded from the outside, so that my plugin is not so bloated
~~~java
public static Map<String, Class<?>> loadJarFromAbsolute(JarFile jar) {
        Enumeration<JarEntry> entryEnumeration = jar.entries();
        Map<String, Class<?>> clazzMap = new HashMap<>(16);
        while (entryEnumeration.hasMoreElements()) {
            JarEntry entry = entryEnumeration.nextElement();
            String clazzName = entry.getName();
            if (clazzName.endsWith(".class")) {
                clazzName = clazzName.substring(0, clazzName.length() - 6);
                clazzName = clazzName.replace("/", ".");
                try {
                    Class<?> clazz = Class.forName(clazzName);
                    clazzMap.put(clazzName, clazz);
                } catch (Throwable e) {
                    e.printStackTrace();
                }
            }
        }
        return clazzMap;
    }
~~~

**Comment by Tofaa2** [comment]
PacketEvents on it's own is a plugin, simply compile it and put it in your plugins folder. Your method most likely is having issues with internals of packet events

**Comment by DeltaLimit** [comment]
> PacketEvents on it's own is a plugin, simply compile it and put it in your plugins folder. Your method most likely is having issues with internals of packet events

It looks like this, I am also thinking about dynamically downloading packetevents to load, but 2.0 does not seem to have a plugin jar?

**Comment by DeltaLimit** [comment]
> PacketEvents on it's own is a plugin, simply compile it and put it in your plugins folder. Your method most likely is having issues with internals of packet events

sorry i read wrong

**Comment by DeltaLimit** [comment]
But packetevents2 only exists in github action now, I want to automatically download updates when packetevents is updated, it seems that there is no way to do this

**Comment by DeltaLimit** [comment]
My clients don't need a plugin that needs to be updated every day
Only one plugin needs it
I tried built-in, but my obfuscator will obfuscate packetevents and may lose performance

**Comment by Tofaa2** [comment]
Then don't obfuscate packet events iirc it is illegal to distribute it and obfuscate, u might wanna not quote me and listen to retrooper himself though. Obfuscation is a bad idea, simply download the jar normally from the artifacts built, there is a spigot artifact for pacnet events that ones a plugin

**Comment by amnoah** [comment]
> My clients don't need a plugin that needs to be updated every day Only one plugin needs it I tried built-in, but my obfuscator will obfuscate packetevents and may lose performance

PacketEvents is licensed under GPLv3. Under GPLv3 any project depending on it/using it must also be GPLv3. GPLv3 allows the customer to receive full source code upon request.

You have no reason to obfuscate unless you plan on not following the license - which is illegal.

Switching to ProtocolLib, Atlas, HamsterAPI. etc won't help - they're all GPLv3. This is because the BukkitAPI is GPLv3.

Thus, don't expect support for illegal activity here.

**Comment by retrooper** [comment]
> But packetevents2 only exists in github action now, I want to automatically download updates when packetevents is updated, it seems that there is no way to do this

We have a jenkins page https://ci.codemc.io/job/retrooper/job/packetevents/ in your case you'd likely want the jar with "spigot" in it. But these people are correct. You're most likely trying to violate the license. (whether intentionally or not)
Just like with Bukkit, and all those other projects, a contributor has the power to DMCA or take legal-action. Me as a project owner can't do anything about it.

**Comment by DeltaLimit** [comment]
My original intention is not to confuse packetevents, but to load it as a normal plugin, but it needs to be updated dynamically, so as to save my customers from the trouble of plugin update frequency. I'll try to investigate how to use packetevents without violating GPLv3. Anyway, thank you all for your replies, I appreciate your kindness.

**Comment by DeltaLimit** [comment]
> > My clients don't need a plugin that needs to be updated every day Only one plugin needs it I tried built-in, but my obfuscator will obfuscate packetevents and may lose performance
> 
> PacketEvents is licensed under GPLv3. Under GPLv3 any project depending on it/using it must also be GPLv3. GPLv3 allows the customer to receive full source code upon request.
> 
> You have no reason to obfuscate unless you plan on not following the license - which is illegal.
> 
> Switching to ProtocolLib, Atlas, HamsterAPI. etc won't help - they're all GPLv3. This is because the BukkitAPI is GPLv3.
> 
> Thus, don't expect support for illegal activity here.

btw BukkitAPI is LGPL

**Comment by MWHunter** [comment]
Bukkit is GPL.  CraftBukkit is LGPL - which is illegal and why it was taken down.  You are using Bukkit - not CraftBukkit.

**Comment by DeltaLimit** [comment]
> Bukkit is GPL. CraftBukkit is LGPL - which is illegal and why it was taken down. You are using Bukkit - not CraftBukkit.

Ok, thank you <3
