### ISSUE TITLE
PacketType.Play.Server.PLAYER_INFO broken in 1.19.3

### ISSUE THREAD

**Issue by kaxlabs** [retrooper/packetevents#519]
**Describe the bug**
```java
@Override
public void onPacketSend(PacketSendEvent event) {
    if (event.getPacketType() == PacketType.Play.Server.PLAYER_INFO) {
    // code here never runs
```

**Software brand**
Current: git-Purpur-1884 (MC: 1.19.3)*
Previous: git-Purpur-1857 (MC: 1.19.2)
* You are running the latest version

**Plugins**
![image](https://user-images.githubusercontent.com/19924741/210906395-1a667c18-4c34-4f6d-90a6-2755295d478a.png)

**How To Reproduce**
Extend PacketListenerAbstract and use code snippet above on a server running 1.19.3 with latest packetevents 2.0.0 and latest ProtocolLib (Build #608).

**Expected behavior**
PLAYER_INFO packet type is found in 1.19.3.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by MWHunter** [comment]
https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/protocol/packettype/clientbound/ClientboundPacketType_1_19_3.java

It is now PLAYER_INFO_UPDATE and PLAYER_INFO_REMOVE, both have wrappers

**Comment by retrooper** [comment]
Yeah. Essentially what changed is in PlayerInfoUpdate you can send an “EnumSet” of actions which will all be sent to the list of profiles. So you should process all of them as it might not be just one. If you’re sending the packet, specify the actions using EnumSet.of(…)
