### ISSUE TITLE
SystemChatMessage diconnects from Velocity

### ISSUE THREAD

**Issue by nightlyDuck** [retrooper/packetevents#520]
**Describe the bug**
An error of sending a message to the player appears. (SystemChatMessage packet)

**Software brand**
Velocity 3.2.0-SNAPSHOT, build 216 (error is also observed after the build 187)

**Plugins**
Only PacketEvents 2.0.0-SNAPSHOT (last build from commit 239cc09 with applied 516 PR)

**How To Reproduce**
1. Join on server with Minecraft 1.19.2 (any 1.19 version)
2. Write code which send message to player
3. Execute command

**Screenshots**

![image](https://user-images.githubusercontent.com/102286502/211081368-96a0c2d3-d3a4-43c4-871c-fb1948504fd2.png)
![image](https://user-images.githubusercontent.com/102286502/211081128-e42e09aa-6c8d-498e-9f69-ef8b501bfc31.png)

**Comment by nightlyDuck** [comment]
> invocation.source() what does this return

This is an analogue of CommandSender from BukkitAPI

**Comment by Snowiiii** [comment]
okay and what Minecraft versions is the Server on ?

**Comment by nightlyDuck** [comment]
> okay and on what Minecraft versions is the Server on ?

PacketEvents detects Velocity server version as 1.19.3

**Comment by nightlyDuck** [comment]
That's why I say that the problem appeared after Velocity added support for 1.19.3

**Comment by MWHunter** [comment]
works for me on both a 1.19.2 and 1.19.3 server connecting from a 1.19.3 client

**Comment by retrooper** [comment]
Sending packets on proxies is in 2.0.1
