### ISSUE TITLE
SpigotReflectionUtil.getEntityById not working in 1.19.3

### ISSUE THREAD

**Issue by Snowiiii** [retrooper/packetevents#525]
**Describe the bug**
If using the Interact Entity Packet and try to convert the Entity id to a Bukkit Entity using SpigotReflectionUtil.getEntityById(((Player) event.getPlayer()).getWorld(), interact.getEntityId());
its always returning null

**Software brand**
This server is running Paper version git-Paper-378 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: ec9dba8)

**Plugins**
ViaVersion, ViaBackwards,ViaRewind

**How To Reproduce**
use SpigotReflectionUtil.getEntityById(((Player) event.getPlayer()).getWorld(), interact.getEntityId()); in 1.19.3

**Expected behavior**

**Comment by KaspianDev** [comment]
can confirm this too, same applies for 1.19.4

**Comment by KaspianDev** [comment]
Also happens on 1.20.1

**Comment by retrooper** [comment]
I might not be able to do anything about it. Minecraft really doesn't like us accessing their entity list asynchronously no matter how we try to bypass their async catchers. In many cases you don't even need to access the entire entity object, if you need to probably cache it yourself with the bukkit events.
