### ISSUE TITLE
[BUG] PacketEvents caught an unhandled exception while calling your listener 

### ISSUE THREAD

**Issue by paul-eff** [retrooper/packetevents#526]
**Describe the bug**
Error randomly popped up while server was idling. No players online for 10-15 hours, no updates/restarts/etc.
The StackTrace comes from the AntiPopup plugin, [KaspianDev](https://github.com/KaspianDev) (the developer) closed my issue and told me to report it to you.

**Server information:**
 - Operating System: Ubuntu 20.04
 - Server Software: Paper
 - Server Version: 371
 - Plugin list: AntiPopup, DriveBackupV2, dynmap, WorldEdit

**Latest log file**
GitHub Gist [here](https://gist.github.com/paul-eff/7d9b31052b7141cebc7e1bab9493eed0)

**Comment by Izibane** [comment]
https://github.com/retrooper/packetevents/issues/523 is same issue @retrooper @MWHunter

**Comment by MWHunter** [comment]
fixed by https://github.com/retrooper/packetevents/commit/d16ad2154d0e13551bf399230e074823b54be5d2
