### ISSUE TITLE
Fix Velocity Support

### ISSUE THREAD

**Issue by ammodev** [retrooper/packetevents#531]
**Describe the bug**
Currently there seems to be many issues when using PE with velocity. 

**Software brand**
Paper: 1.19.3 connected to velocity
Velocity: 1.19.3 - API Always latest
PE: latest 2.0 available

**Plugins**
None but a proxy plugin shading PE. 

**How To Reproduce**
- [ ] Getting kicked when dying

**Expected behavior**
A working velocity PE.

**Comment by ammodev** [comment]
I might take a look into this myself once I have some spare time with university if nobody has the time to fully test velocity first.

**Comment by wordandahalf** [comment]
For what it's worth, we have no issues with the 2.0 branch and ViaVersion in front of 1.19.2 backends.

**Comment by retrooper** [comment]
Probably fixed
