### ISSUE TITLE
Intermittent EncoderException

### ISSUE THREAD

**Issue by SlimeDog** [retrooper/packetevents#533]
This issue was exposed by AntiPopup 5.3, which (per [build.gradle](https://github.com/KaspianDev/AntiPopup/blob/master/build.gradle)) uses PacketEvents 2.0.0. It may be related to changed in the 2023-01-28 update. I do not remember it occurring prior to 2023-01-28, when I updated AntiPopup.

Reference: https://github.com/KaspianDev/AntiPopup/issues/37

### Describe the bug

**Intermittent** `EncoderException` in AntiPopup. It occurs intermittently on server restart. It also occurs intermittently after server restart.

No players are connected.

### To Reproduce

- Start server
- Read log

### Expected behavior

(Relatively) clean start-up

### Operating System

CentOS Linux release 7.9.2009 (Core)

### Server Software

Spigot 1.19.3-3647 or Paper 1.19.3-386

### Server Version

1.19.3

### Proxy Type

None

### Plugin List

```
Lots. See attached log file.
```

### Server logs

https://whitedog.straight8.com/drops/ap-latest.log
https://whitedog.straight8.com/drops/ap2-latest.log

**Comment by SlimeDog** [comment]
I was subsequently able to produce this error without SwimmingHorses installed. So it is not an interaction event, but strictly an AntiPopup/PacketEvents issue. See

https://whitedog.straight8.com/drops/ap2-latest.log

**Comment by introvertism** [comment]
I'm getting this same error with GrimAnticheat. seems very random when it happens

**Comment by MWHunter** [comment]
https://github.com/retrooper/packetevents/commit/0c4709ac575e8f206ad8d448de65119ea4bc83a1
