### ISSUE TITLE
Invisible feature for NPC

### ISSUE THREAD

**Issue by MachineBreaker** [retrooper/packetevents#545]
**Is your feature request related to a problem? Please describe.**
I was doing an NPC KillAura check but i can't make the NPC invisible

**Describe the solution you'd like**
A method to handle the invisibility state of the NPC

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
None

**Additional context**
None

**Comment by VidTu** [comment]
```java
Player player = ...; // Your player
int npcEntityId = ...; // Your NPC entity ID
PacketEvents.getAPI().getPlayerManager().sendPacket(player, new WrapperPlayServerEntityMetadata(npcEntityId, Collections.singletonList(new EntityData(0, EntityDataTypes.BYTE, 0x20)))); // Make it invisible
PacketEvents.getAPI().getPlayerManager().sendPacket(player, new WrapperPlayServerEntityMetadata(npcEntityId, Collections.singletonList(new EntityData(0, EntityDataTypes.BYTE, 0x00)))); // Make it visible again
```
You can edit a lot of [metadata](https://wiki.vg/Entity_metadata) via this packet. Be aware that most of metadata (with some exceptions like this) is version-dependent.

**Comment by MachineBreaker** [comment]
Thanks for that!

**Comment by MachineBreaker** [comment]
After using the code, the server throws an exception
https://pastebin.com/yyuNWDYF
I tried changing the data type of BYTE to INT but the client crashes with this crash report:

The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte

(Im on a 1.8.8 server)

**Comment by VidTu** [comment]
oh, you should probably explicitly cast `0x20` to byte so it looks like this `(byte) 0x20`:
```java
PacketEvents.getAPI().getPlayerManager().sendPacket(player, new WrapperPlayServerEntityMetadata(npcEntityId, Collections.singletonList(new EntityData(0, EntityDataTypes.BYTE, (byte) 0x20))));
```

**Comment by MachineBreaker** [comment]
> oh, you should probably explicitly cast `0x20` to byte so it looks like this `(byte) 0x20`:
> 
> ```java
> PacketEvents.getAPI().getPlayerManager().sendPacket(player, new WrapperPlayServerEntityMetadata(npcEntityId, Collections.singletonList(new EntityData(0, EntityDataTypes.BYTE, (byte) 0x20))));
> ```

It worked, thanks
