### ISSUE TITLE
Committing to using ViaVersion mappings

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#554]
Right now updating is a pain in the ass every time because we have to copy viaversion's mappings to our own format.  Why not just use viaversion's format for all mappings, so we can update faster?

**Comment by retrooper** [comment]
Unfortunately this cannot happen since it seems like ViaVersion's 1.8 item mappings seem to be inaccurate? Does anyone know where I can find their 1.8 item mappings? https://github.com/ViaVersion/Mappings/tree/main/mappings

**Comment by AbhigyaKrishna** [comment]
We don't need to do this anymore.
