### ISSUE TITLE
remove large parts of SpigotReflectionUtil

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#569]
We shouldn't maintain this in 2.0 when we don't use a lot of it.  That's not the purpose of a packet API.

**Comment by RobuxGenDev** [comment]
Keep yourself safe.

**Comment by RobuxGenDev** [comment]
This is not an enhancement, This is a deterioration. - catt

**Comment by MWHunter** [comment]
I still don't see why we should take the maintenance burden of this when we are moving away from reflection.

It is preventing functionality like adding mojang mapping support.

**Comment by Aseeef** [comment]
> 

Out of curiosity, how are existing spigot reflection utils preventing adding mojang mapping support?

**Comment by MWHunter** [comment]
every mapping changes with mojang mappings.  To properly add mojang mapping support we need to add every single mapping's equivalent.  Less mappings means less work to support mojang mappings.

**Comment by MWHunter** [comment]
I don't want to do this without an equivalent.  For example, SpigotReflectionHelper.getEntityId should be replaced with the ability to process packets synchronously... which is impossible without hacky code as we need bytebuffers rather than NMS objects... so there would be a heavy performance penalty.  I don't know what to do, 2.0's design isn't great.  PE 1.8 somehow has better design.
