### ISSUE TITLE
Exception /2/

### ISSUE THREAD

**Issue by molor** [retrooper/packetevents#573]
**Describe the bug**
Happened randomly for me: https://paste.gg/p/anonymous/14a63976b8a54bca998039c48cf71991

**Software brand**
git-Paper-499 (MC: 1.19.4)

**Plugins**
ProtocolLib, LuckPerms, Essentials, MobArena, GrimAC, WorldEdit, WorldGuard, Vault, OpenInv, dynmap, Chunky

**How To Reproduce**
I don't know. And I don't know what the other player was doing. For me, it's happened once and randomly.

**Additional context**
Sorry if this was already reported earlier.

**Comment by molor** [comment]
Is there anyone alive and interested in fixing bugs?..

Another exception: https://paste.gg/p/anonymous/45484ef33847469c8038101b29f621fd
Appeared in console/logs three times immediately after a new player connected to the server and was teleported by plugin.

**Comment by MWHunter** [comment]
This project is provided as is and you are not entitled to any support.
