### ISSUE TITLE
WrapperPlayServerSystemChatMessage

### ISSUE THREAD

**Issue by Symmettry** [retrooper/packetevents#574]
**Describe the bug**
when trying to wrap a System_Chat_Message packet, it throws an error
WrapperPlayServerSystemChatMessage wrapper = new WrapperPlayServerSystemChatMessage(event);

**Software brand**
Paper 1.19.4

**Plugins**
PlugManX, ViaVersion

**How To Reproduce**
*Example:*
1. add code for onPacketSend() in a plugin and try to wrap the SYSTEM_CHAT_MESSAGE in Play.Server and it throws a GSON error

**Expected behavior**
should wrap the packet and be able to be used

**Screenshots**

**Additional context**

**Comment by retrooper** [comment]
Without the error we can't do anything. Can you test it again and send the error if the issue persists?

**Comment by retrooper** [comment]
Closed for nothing, cause I believe to have fixed GSON errors relating chat packets.
