### ISSUE TITLE
Ability to register custom packet types

### ISSUE THREAD

**Issue by hinoobers** [retrooper/packetevents#582]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Some method like registerPacketType(id), to make it possible to read custom packet types that have been implemented on the clientside, yet not on serverside, currently sending custom packets is possible via PacketEvents, but not receiving them. You will get an error like "Unable to map..."

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
Forking PacketEvents & doing it myself

**Additional context**
My implementation (and probably the easiest), is when player registers the custom packet type, have it add the id to some sort of the list, and then when you try to read it, just check the list.
That's just a theory, and might need some changes.

**Comment by MWHunter** [comment]
Why not use plugin messages?  that's what the packet is for.

**Comment by hinoobers** [comment]
> Why not use plugin messages? that's what the packet is for.
"if i use plugin messages i'd have to convert everything to bytes
also for other plugins tracking plugin messages, that's gonna get confusing
and maybe annoying
and might also have some performance issues if a plugin is storing or handling those packets
also some anti crash plugins limit plugin message packets"

**Comment by retrooper** [comment]
Sorry, gonna have to deny this. Would require a rewrite of the packet type system. Please just use plugin messages, you can use Spigot API or our packet wrappers. Java or netty has some API to serialize your data types into bytes, just search it up.
