### ISSUE TITLE
Strange client disconnection errors

### ISSUE THREAD

**Issue by wordandahalf** [retrooper/packetevents#587]
**Describe the bug**
When teleporting between dimensions or dying (what seems to be anything that requires the re-sending of world data after joining) causes the client to disconnect with different packet-related errors. Worlds have been re-generated and don't seem to be the cause of the error.

**Software brand**
- Velocity 3.2.0-SNAPSHOT (`git-e364e2c7-b250`)
- Pufferfish (`git-Pufferfish-71`)
- PacketEvents `2.0`, latest commit (`7539aa3`)

**Plugins**
Velocity has an internal plugin with shaded PacketEvents. Issue occurs if and only if PacketEvents is initialized:
```kotlin
// Initialize PacketEvents
val packetEvents = VelocityPacketEventsBuilder
    .build(server, container)

packetEvents.settings.also {
    it.debug(true)
    it.checkForUpdates(false)
    it.bStats(false)
}

PacketEvents.setAPI(packetEvents)
packetEvents.also { it.init() }
```
The Pufferfish backend has no plugins.

**Screenshots**
With player in the Overworld, running `execute in minecraft:the_nether run tp @s 0 200 0` causes
![image](https://github.com/retrooper/packetevents/assets/10679776/f72fb093-27ed-4325-97a4-eccf68819c20)

With player in the Nether, running `execute in minecraft:overworld run tp @s 0 200 0` causes The same disconnection message occurs when running this command in the Overworld but targeting The End, or vice versa.
![image](https://github.com/retrooper/packetevents/assets/10679776/9baf6bb4-7a0f-4811-bb66-6ca34bae0ee2)

Dying in the Overworld causes
![image](https://github.com/retrooper/packetevents/assets/10679776/9e3a9500-55d6-4cd0-8b9f-2a4dd86ad8f9)

**Comment by wordandahalf** [comment]
I'll be doing some investigation to see if I can get to the bottom of it.

**Comment by wordandahalf** [comment]
By using an unobfuscated Fabric development environment, the disconnection messages can made human-readable:
1) in the first screenshot, `y` resolves to `net.minecraft.util.crash.CrashException`
2) in the two subsequent screenshots, `vy` resolves to `ScreenHandlerPropertyUpdateS2CPacket`.

**Comment by MWHunter** [comment]
Probably something with https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/manager/InternalPacketListener.java

**Comment by wordandahalf** [comment]
For what it's worth, this error mysteriously stopped occurring. I'll re-test the procedure with `2.0.0` and see if anything interesting happens, otherwise I'll just close this issue.

**Comment by wordandahalf** [comment]
It's started occurring again, this time with 1.20.2 and b48a91b on `2.0`.

**Comment by wordandahalf** [comment]
> It's started occurring again, this time with 1.20.2 and [b48a91b](https://github.com/retrooper/packetevents/commit/b48a91bcee40805bf24a4dad7dfa12e6ae7445c0) on `2.0`.

I've tested using the latest built artifact from Jenkins. If I comment out lines 129 - 140 in `InternalPacketListener`, the issue does resolve. I'll see if the wrapper for the respawn packet has a small issue.

**Comment by retrooper** [comment]
Decoding issues on velocity should have been fixed by now.
