### ISSUE TITLE
NPC updatePing method doesn't work

### ISSUE THREAD

**Issue by jonesdevelopment** [retrooper/packetevents#595]
**Describe the bug**
`npc.updateTabPing(11);` throws `java.lang.IllegalArgumentException: Packet does not exist on this protocol version!` because in NPC.java line 213 is checking `isOlderThanOrEquals(ServerVersion.V_1_19_3)` instead of `isNewerThanOrEquals(ServerVersion.V_1_19_3)`

**Software brand**
Pufferfish version git-Pufferfish-73 (MC: 1.19.4)

**Plugins**
ViaVersion, ViaRewind, ViaBackwards

**How To Reproduce**
- Create an NPC
- Try to set the tablist ping on a 1.19.4 server

**Expected behavior**
Don't throw an exception and set the tab ping

**Screenshots**
![image](https://github.com/retrooper/packetevents/assets/73846784/0f9de278-2c92-458d-8cf8-fced5c76232b)
It should be `isNewerThanOrEquals(ServerVersion.V_1_19_3)` here.

![image](https://github.com/retrooper/packetevents/assets/73846784/d5d548f4-7fbb-4a76-a5c2-78d26260dd2a)
`updateGameMode(GameMode gamemode)` works.

**Additional context**
/

**Comment by retrooper** [comment]
Why didn't you directly make a PR?

**Comment by retrooper** [comment]
Thank you, fixed in https://github.com/retrooper/packetevents/commit/65a984e805bb5e3eaae84dd7a99e5a3f2b90bfa5
