### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by PenguThePenguin** [retrooper/packetevents#600]
Change this to 1.7+:

![image](https://github.com/retrooper/packetevents/assets/57046639/4b1726ed-25e3-44a2-ae64-06dac2efca7b)

**Comment by AbhigyaKrishna** [comment]
It is 1.8+. 1.7 support was dropped when 1.18 came out iirc.

**Comment by PenguThePenguin** [comment]
why was it?

**Comment by PenguThePenguin** [comment]
Oh 
![image](https://github.com/retrooper/packetevents/assets/57046639/ddfd6e52-e313-4f1e-9e8d-ebe793368df4)

**Comment by AbhigyaKrishna** [comment]
There were too many changes between these version and it wasn't worth supporting that old version.

**Comment by PenguThePenguin** [comment]
thanks
