### ISSUE TITLE
Throwables caught by callEvent, which can stall out chat or possibly the server

### ISSUE THREAD

**Issue by mbax** [retrooper/packetevents#603]
**Describe the bug**
Throwables are caught by callEvent, eating things like `OutOfMemoryError`, which can lock up chat if it happens on the chat thread.

**Software brand**
Not particularly relevant, but I found a log ostensibly from Paper.

**Plugins**
Sorry! Not my log.

**How To Reproduce**
1. Run out of heap space during packet processing of a chat message. Yeah, sorry, good luck.
2. Server keeps going without chat working.

**Expected behavior**
Not eating the error.

**Screenshots**
No. 😄 

**Log**
https://mclo.gs/02cMfkd

**Source of trouble**
https://github.com/retrooper/packetevents/blob/800ffafb9628c3d99ddb7e6c0a2a597a706d05aa/api/src/main/java/com/github/retrooper/packetevents/event/EventManager.java#L53

**Additional context**
Java is magic.

**Comment by MWHunter** [comment]
Change it to catch Exception rather than Throwable

**Comment by mbax** [comment]
Apparently forgot to paste the link earlier - really thought I did - so I have edited the post to include the link.

**Comment by AoElite** [comment]
Fixed 756add003f7bac3cac7864ec76f8982a39de7c5a
