### ISSUE TITLE
Retrieving Chunk Data causes player to be kicked

### ISSUE THREAD

**Issue by micartey** [retrooper/packetevents#605]
**Describe the bug**
When I try to create a `WrapperPlayServerChunkData` I get kicked for the following reason:

```
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
```

**Software brand**
I tried Purpur and plain Spigot for 1.20.1
(Using the spigot version)

**Plugins**
None, just mine.

**How To Reproduce**
1. Filter outgoing packets for `CHUNK_DATA`
2. Create a `WrapperPlayServerChunkData` (you don't even need to access the object)
3. Join the server
4. Never see the world as you will be disconnected.

**Expected behavior**
Not getting kicked, being able to create the `WrapperPlayServerChunkData` object and read the values

**Additional context**
```java
    @Override
    public void onPacketSend(PacketSendEvent event) {
        System.out.println(event.getPacketType().getName());

        try {
            if (event.getPlayer() == null)
                return;

            Player receiver = (Player) event.getPlayer();
            readPacketsOutbound(receiver, event);
        } catch (Throwable throwable) {
            Logger.EXCEPTION.log("packet_handler", throwable);
            throwable.printStackTrace();
        }
    }

    private void readPacketsOutbound(Player player, PacketSendEvent event) {
        if (!event.getPacketType().equals(PacketType.Play.Server.CHUNK_DATA))
            return;
            
        WrapperPlayServerChunkData packet = new WrapperPlayServerChunkData(event);
    }
```

**Comment by micartey** [comment]
Using the following version works. Somewhere in between, somebody broke something.

```
implementation 'com.github.retrooper.packetevents:spigot:756add0'
```

**Comment by BrightSteel** [comment]
Seeing this issue as well on paper 1.20.1

**Comment by retrooper** [comment]
Paper 1.20.1 and it is working fine. I cannot reproduce.


```java
@Override
public void onPacketPlaySend(PacketPlaySendEvent event) {
        if (event.getPacketType() == PacketType.Play.Server.CHUNK_DATA) {
                WrapperPlayServerChunkData chunkData = new WrapperPlayServerChunkData(event);
                System.out.println("cx: " + chunkData.getColumn().getX() + ", cz: " + chunkData.getColumn().getZ());
        }
}
```

![image](https://github.com/retrooper/packetevents/assets/49798017/e9365492-43e4-4d98-adf6-36dea0cca75c)

**Comment by micartey** [comment]
@BrightSteel @retrooper what versions of Minecraft where you running? I was running lunar 1.20.1. The internal error might be client side. I didn't see anything in the logs though. 

I am currently on vacation so I cannot provide additional information until next weekend.

**Comment by retrooper** [comment]
I ran vanilla 1.20.1!

**Comment by micartey** [comment]
I think I also tried vanilla as well. Do you mind sharing your project so we can see what we did differently? Are you using packet events externally?

**Comment by BrightSteel** [comment]
I can try to narrow down what is happening. It's not client dependent, I was running the same plug-in on one server and had no issues, but was met with this kick error on my other server. 

The one that did have issues was a bungeecorded server with custom biomes (not sure if that could be relevant).

**Comment by micartey** [comment]
This is not bungeecord depending. It happened to my localhost server and I don't use bungee or any other proxy

**Comment by retrooper** [comment]
> I think I also tried vanilla as well. Do you mind sharing your project so we can see what we did differently? Are you using packet events externally?

It isn’t dependent on whether or not you used it externally or not. But if you believe so you may look at our wiki page which has depending on pre built PacketEvents which you should follow carefully. 

Furthermore, you should be the one sharing your project so that your mistake can be identified.

**Comment by BrightSteel** [comment]
Hmm, so I've tried it now with no additional plugins and am still seeing this error on newest version of paper. @retrooper Are we registering our listeners incorrectly? You seem to be getting a PacketPlaySendEvent to override, but I am just using the PacketListenerAbstract class as my listener like so:

```
PacketEvents.getAPI().getEventManager().registerListener(new PacketListenerAbstract() {
            @Override
            public void onPacketSend(PacketSendEvent event) {}
}
```

Also are you sure you tested with the latest version of paper 1.20.1 and latest Packet Events? This was not an issue on previous versions of paper for me and/or previous versions of this plugin.

**Comment by BrightSteel** [comment]
So registering it like so causes the kick for me:
`PacketEvents.getAPI().getEventManager().registerListener(new PacketListenerAbstract() {
            @Override
            public void onPacketSend(PacketSendEvent event) {
                if (event.getPacketType() == PacketType.Play.Server.CHUNK_DATA) {
                    WrapperPlayServerChunkData chunkData = new WrapperPlayServerChunkData(event);
                    System.out.println("cx: " + chunkData.getColumn().getX() + ", cz: " + chunkData.getColumn().getZ());
                }
            }
        });`

**Comment by retrooper** [comment]
> Hmm, so I've tried it now with no additional plugins and am still seeing this error on newest version of paper. @retrooper Are we registering our listeners correctly? You seem to be getting a PacketPlaySendEvent to override, but I am just using the PacketListenerAbstract class as my listener like so:
> 
> ```
> PacketEvents.getAPI().getEventManager().registerListener(new PacketListenerAbstract() {
>             @Override
>             public void onPacketSend(PacketSendEvent event) {}
> }
> ```
> 
> Also are you sure you tested with the latest version of paper 1.20.1 and latest Packet Events? This was not an issue on previous versions of paper for me and/or previous versions of this plugin.

Yes I am sure I used the latest Paper 1.20.1 build at the time that I sent that screenshot. Can I see your whole project? And are you sure you are using **Paper** 1.20.1?

**Comment by retrooper** [comment]
Probably fixed.
