### ISSUE TITLE
Missing yaw attribute in WrapperPlayServerHurtAnimation class

### ISSUE THREAD

**Issue by CubBossa** [retrooper/packetevents#606]
**Describe the bug**
The `WrapperPlayServerHurtAnimation` class does have an attribute for the yaw that describes where the attacker stands relative to the attacked. A setter and a constructor parameter are missing though.

**Comment by retrooper** [comment]
And where is that attribute in the protocol?

**Comment by retrooper** [comment]
Where is this yaw attribute?

**Comment by retrooper** [comment]
I have added the constructors, getters and setters.
