### ISSUE TITLE
1.20.2 

### ISSUE THREAD

**Issue by ghost** [retrooper/packetevents#612]
Im not gonna lie, where is 1.20.2? 😄

**Comment by CloudeLecaw** [comment]
I hope Version 6.3 will also include the option to block reporting for skin and name.

Currently:
Tested on 1.20.1 with 1.20.2 client (viaversion) the players have the option to report names and skin while chat is blocked fine by Antipopup.

**Comment by CloudeLecaw** [comment]
> > I hope Version 6.3 will also include the option to block reporting for skin and name.
> > Currently: Tested on 1.20.1 with 1.20.2 client (viaversion) the players have the option to report names and skin while chat is blocked fine by Antipopup.
> 
> Doesn't really involve packet events, if you want to make a plugin that does that using packet events go ahead, but building politics into the plugin would be kinda dumb.
> 
> You can use freedom chat to disable 1.20.2 chat reporting: https://github.com/ocelotpotpie/FreedomChat

wtf?
i dont know what your translate told you, that your talking about politcs.  well never might. i was asking for addition and no
FreedChat is a Chatt plugin so no option

**Comment by retrooper** [comment]
The PR has been merged, all that is left is to add support for 1.20.2 on proxies.

**Comment by booky10** [comment]
As 1.20.2 support has been released for a while, this should probably be closed
