### ISSUE TITLE
WrappedBlockState.getByGlobalId() cloning

### ISSUE THREAD

**Issue by LeeGodSRC** [retrooper/packetevents#617]
**Is your feature request related to a problem? Please describe.**
Not sure if this is discussed before,
`WrappedBlockState.getByGlobalId()` is cloning a WrappedBlockState every single time, which can be a very expensive for large reading process while we are not modifying the block state at all.

**Describe the solution you'd like**
Actually just make it an immutable object so all hassle fixed.

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
We can cache it ourselves or do something to handle it but it's also used internally such as BaseChunk and we can't avoid that.

**Comment by LeeGodSRC** [comment]
> ```
> boolean hasClonedData = false;
> ```
> 
> We don't need to clone it, cloning is legacy code. When you modify a WrappedBlockState for the first time - it clones itself to ensure that the pallet doesn't get corrupted.

I see, so this .clone() here is no longer needed right?
```
    @NotNull
    public static WrappedBlockState getByGlobalId(ClientVersion version, int globalID) {
        if (globalID == 0) return AIR; // Hardcode for performance
        byte mappingsIndex = getMappingsIndex(version);
        return BY_ID.get(mappingsIndex).getOrDefault(globalID, AIR).clone(); <--
    }
```

**Comment by MWHunter** [comment]
Yes

**Comment by MWHunter** [comment]
Nevermind, the clone is still needed.  You could add another method to get a WrappedBlockState and just do getReadOnlyBlockData and put deprecated on it.
