### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by SladeHazard** [retrooper/packetevents#620]
**Describe the bug**
Anticheat starts spamming console whenever any plugin that relies on packetevents is installed on the server..

**Software brand**
1.12.2 Paper

**Plugins**
Verus

**How To Reproduce**
Install a plugin like ZNPC or ClientDetector both relying on packetevents, and use Verus anticheat. the console will spam constantly

**Expected behavior**
No spam

**Error Link**
https://hastebin.com/share/ocokuwejax.css

Please ignore ChatItem and RecipesRemover, for some reason the stacktrace contains every plugin using NMS, the error still persists without those plugins installed

**Comment by SladeHazard** [comment]
https://hangar.papermc.io/Loving11ish/ClientDetector
https://github.com/Pyrbu/ZNPCsPlus

**Comment by retrooper** [comment]
Their netty handler probably assumes the packets are instances of "Packet" without checking if it is an instance of "Packet". In simple terms they are casting without using instanceof. Please tell "Verus" to correct it in their handler, thanks.

**Comment by SladeHazard** [comment]
> Their netty handler probably assumes the packets are instances of "Packet" without checking if it is an instance of "Packet". In simple terms they are casting without using instanceof. Please tell "Verus" to correct it in their handler, thanks.

![image](https://github.com/retrooper/packetevents/assets/45261094/110cc0f0-5319-4cc7-a6bb-e931ad03fb71)
