### ISSUE TITLE
Wrong PacketListener priority order

### ISSUE THREAD

**Issue by zhusun890** [retrooper/packetevents#624]
**Describe the bug**
The sort of PacketListenerPriority was reversed when an event's being called.
[com.github.retrooper.packetevents.event.EventManager.java, line 47](https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/event/EventManager.java)
`"for (byte priority = PacketListenerPriority.LOWEST.getId(); priority <= PacketListenerPriority.MONITOR.getId(); priority++) {"`

**Software brand**
All version.

**Plugins**
None

**How To Reproduce**
1. I have nothing to write here

**Expected behavior**
It seems the for-each starts from the "LOWEST" priority and process listeners with this priority FIRST, and actually it should process MONITOR priority listeners first.

**Comment by TrollsterCooleg** [comment]
This isn't a bug, but exactly how it's meant to work. Lowest priority means it has the lowest ability to decide the final result, going up to monitor which is meant to be able to "monitor" whatever the final state of the event is AFTER all the other listeners have processed. This is also consistent with spigot's event priority system: [EventPriority spigot javadocs](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/EventPriority.html)

The comments also demonstrate that this was the intended behavior.
