### ISSUE TITLE
1.20.2 server crash

### ISSUE THREAD

**Issue by SkirmisLTU** [retrooper/packetevents#628]
**Describe the bug**
My server crashed, multiple times, Grim support says it can be PacketEvents fault.

**Software brand**
Proxy: (fork of bungeecord) XCord 1.56 ; Spigot: Purpur 1.20.2 build 2095

**Plugins**
Bukkit Plugins: (62): AdvancedPortals, AdvancedRegionMarket, BanItem, BetterShulkerBoxes, BuycraftX, ChatFilter, ChatManager, Citizens, ClansLite, ClearLag, CMI, CMILib, CommandPanels, CommandWhitelist, CoreProtect, DamageReduction, DecentHolograms, *DiscordUtils, DropEdit2, ExcellentCrates, FastAsyncWorldEdit, Grim, HeadDatabase, IllegalStack, InventoryRollbackPlus, ItemEdit, ItemTag, JPremium, LiteBans, LuckPerms, MineResetLite, *MVdWPlaceholderAPI, MyCommand, NexEngine, PlaceholderAPI, Plan, PlayerVaults, PlugManX, PolarLoader, PremiumVanish, ProtocolLib, PvPManager, SelectionVisualizer, Shopkeepers, Skellett, Skript, *skript-placeholders, *skUtilities, spark, TAB-Bridge, TradeMe, *TSetSpawn, Vault, ViaBackwards, ViaVersion, VoidGen, VotifierPlus, VotingPlugin, Vulcan, WG-GUI, WizardDamageReduction, WorldGuard, WorldGuardExtraFlags

**How To Reproduce**
O am not 100% sure if it's correct, I can't really reproduce it myself, but I happens when my players join.
1. Join with the 1.16.4 Minecraft client.
2. Watch the server crash

**Expected behavior**
Everything working fine, no crashing

**Logs**
https://mclo.gs/9iScQzZ (the second part of the error is where it crashes, warning part can happen without crash, but you might be interested in both parts)

**Additional context**
I hope there is a way to fix this...

**Comment by SamB440** [comment]
Polar specifically states in its [docs](https://docs.polar.top/general/compatibility):
**Incompatible software**
- PacketEvents
- Any anticheat running on the same server instance as Polar

**Comment by SkirmisLTU** [comment]
I tried running it without Polar and Vulcan; same result, so they're not the problem.

**Comment by SkirmisLTU** [comment]
I finally found a way to replicate it. 
Plugins - GrimAC, JPremium, ProtocolLib, spark, ViaBackwards, ViaVersion

Server version: Purpur 1.20.2 build 2095
Client: 1.20.2
Logs: https://mclo.gs/ND2RbOV
Bungee: XCord 1.56 (it's probably the same with any bungee)

Grim configuration: 
[config.txt](https://github.com/retrooper/packetevents/files/13720111/config.txt)
(rename it to `config.yml` if you're planning to use it)


Reproduce steps:
1. Join the server
2. Leave the server
3. Join the server again
4. Watch it crash

(!) I believe that `enable-post-packet: true` config option makes it crash

**Comment by SamB440** [comment]
Can be closed, not a PE issue.
