### ISSUE TITLE
WrapperPlayServerChunkData does not have setters for other values.

### ISSUE THREAD

**Issue by FinalBoolean** [retrooper/packetevents#631]
**Describe the bug**
The wrapper for CHUNK_DATA only has setters for Column and not the rest of the values.

**Software brand**
Pufferfish 1.20.2

**Plugins**
ViaVersion, WorldGuard, Essentials.

**How To Reproduce**
Send a WrapperPlayServerChunkData and it should return a null pointer exception.

**Expected behavior**
Should have setters for WrapperPlayServerChunkData

**Screenshots**
![image](https://github.com/retrooper/packetevents/assets/41921648/04c0e941-f1bf-47e1-830d-8f9cdb00d310)

**Additional context**
None

**Comment by booky10** [comment]
Fixed by #715
