### ISSUE TITLE
Error on 350k lines

### ISSUE THREAD

**Issue by StKillReal** [retrooper/packetevents#635]
**Describe the bug**
The latgest error in console I've ever seen
https://pastebin.com/3D5wPdeT

**Software brand**
![image](https://github.com/retrooper/packetevents/assets/60330193/0f262492-ca27-4e74-87be-5fed1d66431b)

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/60330193/fafe5f4f-efe5-4b39-a2b3-ef8bbb717b04)

**How To Reproduce**
Install the latest version of grimAC and start the server

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/retrooper/packetevents/assets/60330193/1ccaaa1c-9c9e-467d-bf1a-20f153191b3a)

**Additional context**
![image](https://github.com/retrooper/packetevents/assets/60330193/685c3fad-cf22-4bb0-b19f-bfdea78c2b2b)

**Comment by retrooper** [comment]
Seems like it was dealt with.
