### ISSUE TITLE
latest paper breaks packet events

### ISSUE THREAD

**Issue by ThrowerWay** [retrooper/packetevents#637]
They added an override to asNMSCopy that takes a list of itemstacks instead of single itemstack, packetevents calls this method with null which then causes an NPE

https://github.com/PaperMC/Paper/commit/2c3ccb80f0dacc8566242a87c53f665cae3b8c7f#diff-d9fc9c55998599c470b26fd6657b13f40a7532c895a4cea140469090c43faec3R275

**Comment by molor** [comment]
Can confirm. Stack trace example: https://pastebin.com/raw/bb9wVVK8

**Comment by MWHunter** [comment]
CRAFT_ITEM_STACK_AS_NMS_COPY = Reflection.getMethod(CRAFT_ITEM_STACK_CLASS, "asNMSCopy", ItemStack.class);

This seems like the more proper fix

**Comment by MWHunter** [comment]
Should be fixed after https://github.com/retrooper/packetevents/commit/f6c554da02296a4b26261ff6e7d295aeaf5a9cf0
