### ISSUE TITLE
NullPointerException: type cannot be null

### ISSUE THREAD

**Issue by molor** [retrooper/packetevents#638]
**Describe the bug**
https://pastebin.com/raw/uRuzVNq8

**Software brand**
Paper 1.20.4

**Plugins**
ProtocolLib, Essentials, MobArena, GrimAC, ChunkyBorder, Chunky, LuckPerms, Orebfuscator, OpenInv, Vault, WorldEdit, WorldGuard, dynmap

**How To Reproduce**
This exception is appear randomly.

**Expected behavior**
No exception, like was before we updated our server from Paper 1.20.1 to 1.20.4

**Comment by MWHunter** [comment]
Duplicate https://github.com/retrooper/packetevents/issues/637

**Comment by molor** [comment]
Hi @MWHunter, happy HY! Just want to clarify: stack traces in #637 and here are different. Are this issue really a duplicate?

**Comment by MachineBreaker** [comment]
This type of exceptions is mostly caused by ProtocolLib side, i got a bunch of my clients with that exception and downgrading ProtocolLib fixed it (Probably won't work for you since you're at 1.20.4)
