### ISSUE TITLE
Sending entity packets and repeat WrapperPlayServerEntityEquipment does not display on the client

### ISSUE THREAD

**Issue by Tofaa2** [retrooper/packetevents#641]
**Describe the bug**
WrapperPlayServerEntityEquipment doesnt show equipment after first time? First time it equips the entity with it but resending it with another list of equipment it just doesnt bother? Also idk if there's something wrong with the EntityDataTypes.COMPONENT during serialization because it kind of doesnt show the entities name

**Software brand**
EntityLib test plugin, compiled and tested on 1.20.1 paper

**Comment by retrooper** [comment]
@booky10 I haven't confirmed this yet, but any idea how or why?
