### ISSUE TITLE
Vector3i::subtract adds instead of subtracting

### ISSUE THREAD

**Issue by joshuaprince** [retrooper/packetevents#646]
**Describe the bug**
`Vector3i::subtract()` should return a new vector with the provided components subtracted, but it **adds** the provided components instead:

https://github.com/retrooper/packetevents/blob/e7dcb4c96ead2abc460f883d442316445336ce9a/api/src/main/java/com/github/retrooper/packetevents/util/Vector3i.java#L204-L206

Floating-point Vector types correctly subtract:
https://github.com/retrooper/packetevents/blob/e7dcb4c96ead2abc460f883d442316445336ce9a/api/src/main/java/com/github/retrooper/packetevents/util/Vector3d.java#L153-L155

(snipped the rest of the issue template since it's not relevant)

**Comment by retrooper** [comment]
Fixed ✔️
