### ISSUE TITLE
bStats doesn't work when PE is shaded

### ISSUE THREAD

**Issue by cheaterSK** [retrooper/packetevents#652]
**Describe the bug**
When you shade PE into a Velocity plugin and have bStats on, it crashes, because it tries to cast the main class into PacketEventsPlugin.

**Software brand**
Velocity 3.2.0, but other software is worth testing too

**Plugins**
None besides the one with shaded PE.

**How To Reproduce**
1. Shade PE into your plugin
2. Turn on bStats

**Expected behavior**
The plugin should start normally.

**Comment by retrooper** [comment]
I'll assume this is fixed.
