### ISSUE TITLE
IllegalArgumentException when sending packets

### ISSUE THREAD

**Issue by Skyslycer** [retrooper/packetevents#653]
**Describe the bug**
When sending a packet, an equipment packet specifically, the following error happens:
https://paste.skyslycer.de/WHFup

**Software brand**
Pufferfish 1.20.4

**Plugins**
Not sure as it's a customer but the issue should occur with just HMCWraps (PE is shaded)

**How To Reproduce**
1. Use HMCWraps
2. Start the floating preview 

**Expected behavior**
It should work... I guess?

**Comment by booky10** [comment]
This should already be resolved by f6c554da02296a4b26261ff6e7d295aeaf5a9cf0, which isn't released yet

**Comment by Skyslycer** [comment]
Here's a similar one: https://paste.skyslycer.de/d3rTD

**Comment by Skyslycer** [comment]
Do you happen to know when it will release?

**Comment by retrooper** [comment]
Released!
