### ISSUE TITLE
Netherrite Armor Not Detected as Damageable Item

### ISSUE THREAD

**Issue by Bram1903** [retrooper/packetevents#667]
**Describe the bug**
Netherrite Armor is not being detected as a damageable item when using `ItemStack#isDamageableItem`, which results in logic being wrongly executed in plugins depending on that boolean.

**Software brand**
Paper 1.20.4

**Plugins**
Empty Development Server

**How To Reproduce**
Steps to reproduce the behaviour:
1. Listen for an compatible packet `PacketType.Play.Server.ENTITY_EQUIPMENT` as example.
2. Retrieve the Equipment list out of the packet by using the provided wrapper.
3. Loop through this list of equipment, and get the ItemStack out of it.
4. Add an if/else statement on the item stack, to check if the item is damageable, and add logging.
5. Join the game and equip multiple different items, to test that `ItemStack#isDamageableItem` is working in normal circumstances. 
6. Now equip any Netherrite armor, and the log will indicate the item isn't damageable.

Code example: 
```java
equipmentList.forEach(equipment -> {
    ItemStack itemStack = equipment.getItem();
    
    // Here the netherite armor is present when logging
    
    if (itemStack.isDamageableItem()) {
        // Doesn't regonize the netherite armor as damageable item
    }
});
```

**Expected behaviour**
The expected behaviour is that Netherrite armor is also being identified as a damageable item.

**Screenshots**
![image](https://github.com/retrooper/packetevents/assets/70259613/4289c385-ff59-401a-9f14-ed04fc0c2dd7)

**Additional context**
This issue probably has to do with the fact that Netherrite Armor is not receiving a maximum durability in the `com.github.retrooper.packetevents.protocol.item.type.ItemTypes` class through `#setMaxDurability`.

Example of other armor:
![image](https://github.com/retrooper/packetevents/assets/70259613/a7d5bdfe-c4ae-4053-91ca-bdcb6692cc9f)

Example of Netherrite armor:
![image](https://github.com/retrooper/packetevents/assets/70259613/1ddc9d6c-e025-44fd-9568-370e9c960473)

**Comment by AoElite** [comment]
Fixed 72944a00c0608473997e9aceaebd5517ddd8600b
