### ISSUE TITLE
WrapperPlayServerSpawnPlayer Packet does not work for higher client versions.

### ISSUE THREAD

**Issue by IWolfZZ** [retrooper/packetevents#675]
**Describe the bug**
A clear and concise description of this bug is that the WrapperPlayServerSpawnPlayer does not work for higher client versions. This is also a issue when using the WrapperPlayServerSpawnEntity on newer server versions with 1.17 - 1.20 client versions.

**Software brand**
Spigot 1.8.8
PacketEvents Version: 2.2.0

**Plugins**
ViaVersion, ViaBackwards, ViaRewind, TestPlugin

**How To Reproduce**
1. Use 1.17 client version or higher to experience this issue.
2. Spawn a player with the WrapperPlayServerSpawnPlayer on a 1.8 server at your players location.
3. The wrapper will not show a player once you send the packet.

**Expected behavior**
To see a player spawned when you send the wrapper.

**Comment by jtJava** [comment]
Wouldn't this be a ViaVersion issue? Test this with a 1.8.8 Client on a 1.8.8 Server

**Comment by IWolfZZ** [comment]
> Wouldn't this be a ViaVersion issue? Test this with a 1.8.8 Client on a 1.8.8 Server

I have tested it both with and without ViaVersion installed on the 1.8.8 server. In either case, it would work regardless on a 1.8 client version, as the main issue seems to be that clients from versions 1.17 to 1.20 cannot see the player. Which I have tested it on a 1.20.4 server with no ViaVersion installed, and the results are that the player does not show to the client.

I have also just tested it with the latest commit of PacketEvents.

**Comment by Tofaa2** [comment]
Modern versions spawn a player using PlayerInfoUpdate, not SPAWN_PLAYER.

**Comment by booky10** [comment]
The spawn_player packet is completely gone on modern versions, you have to use the spawn_entity packet instead.

**Comment by IWolfZZ** [comment]
Seemed to get the issue fixed. Thanks to the people that helped
