### ISSUE TITLE
[feature request] Change the gson library to fastjson2

### ISSUE THREAD

**Issue by DxrkCat** [retrooper/packetevents#677]
**Is your feature request related to a problem? Please describe.**
No, this is related to the idea of improving performance in json moments.

**Describe the solution you'd like**
https://github.com/alibaba/fastjson2 - This library is actively supported and fully stable, but its performance is better than gson, you can see by benchmarks
https://github.com/fabienrenaud/java-json-benchmark - benchmark tests (gson vs fastjson2)
**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
-

**Additional context**
-

**Comment by retrooper** [comment]
We're fine with what we have right now, and we use adventure for chat processing which uses gson anyway.
