### ISSUE TITLE
/give command throwing warning - SYSTEM_CHAT_MESSAGE 

### ISSUE THREAD

**Issue by xMrAfonso** [retrooper/packetevents#679]
**Describe the bug**
When listening to the system chat message packet and modifying it, if I use the vanilla /give command, it throws a warning. This warning is not thrown in any other system messages that I have tried.

**Software brand**
Paper 1.20.4 - Latest

**Plugins**
Vault, PlaceholderAPI and my own plugin. (PacketEvents is shaded)

**How To Reproduce**
1. Listen to the system chat message packet.
2. Use the vanilla /give command.
3. [This](https://paste.helpch.at/osokeqiqud.rb) warning will pop up.

**Expected behavior**
Not to throw any warnings?

**Comment by Skyslycer** [comment]
Can you share your listener code?

**Comment by xMrAfonso** [comment]
```java
@Override
public void onPacketPlaySend(PacketPlaySendEvent e) {
	if (!config.getOrDefault("listeners.system-messages", true) ||
		e.getPacketType() != PacketType.Play.Server.SYSTEM_CHAT_MESSAGE) return;

	Player player = (Player) e.getPlayer();
	WrapperPlayServerSystemChatMessage packet = new WrapperPlayServerSystemChatMessage(e);
	packet.setMessage(handler.processComponent(packet.getMessage(), player));
}
```
`handler.processComponent()` simply parses the component with minimessage and placeholders. From what I spoke with someone in discord, it appears to be an issue with parsing in PacketEvents between Json Chat Components and NBT Chat Components.
