### ISSUE TITLE
Latest ViaVersion breaks grabbing user client version

### ISSUE THREAD

**Issue by KaspianDev** [retrooper/packetevents#680]
**Describe the bug**
Since probably [this](https://modrinth.com/plugin/viaversion/version/4.10.0-24w06a-SNAPSHOT+218) or a bit earlier build of via PE errors when trying to get the user version with following message:
`Unable to grab ViaVersion client version for player!`

**Software brand**
Paper 1.20.4

**Plugins**
AntiPopup (shades PE), ViaVersion

**How To Reproduce**
1. Use User#getClientVersion method
2. The message appears

PS: Might be a good idea to use PacketEvent's version grabber as fallback to prevent these in future

**Comment by jordoncodes** [comment]
> **Describe the bug** Since probably [this](https://modrinth.com/plugin/viaversion/version/4.10.0-24w06a-SNAPSHOT+218) or a bit earlier build of via PE errors when trying to get the user version with following message: `Unable to grab ViaVersion client version for player!`
> 
> **Software brand** Paper 1.20.4
> 
> **Plugins** AntiPopup (shades PE), ViaVersion
> 
> **How To Reproduce**
> 
> 1. Use User#getClientVersion method
> 2. The message appears
> 
> PS: Might be a good idea to use PacketEvent's version grabber as fallback to prevent these in future

try using the [latest ViaVersion snapshot](https://hangar.papermc.io/ViaVersion/ViaVersion) from hangar with PE 2.2.1, this seems to work for me.

**Comment by ArionOwO** [comment]
I'm also experiencing the "Unable to grab ViaVersion client version for player!" spam with the latest dev build of viaversion/viabackwards, also i've tried 1.20.2 and 1.20.4 latest versions of paper.

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/5502c4a434d1f2ddeea310b306dfef43aa44a33f
