### ISSUE TITLE
SpigotConversionUtil#fromBukkitWorld(World) not working on 1.20.4

### ISSUE THREAD

**Issue by jordoncodes** [retrooper/packetevents#685]
**Describe the bug**
On a 1.20.4 server, SpigotConversionUtil.fromBukkitWorld(world) returns a Dimension with id 0, no NBT and type of OVERWORLD no matter the dimension.

**Software brand**
Paper 1.20.4

**Plugins**
(my custom plugin used for this), PacketEvents (not shaded)
also tested with ViaVersion + VB + VR

**How To Reproduce**
1. Join a 1.20.4 server
2. Send a respawn packet tot the player using SpigotConversionUtil#fromBukkitWorld(World) for the world.
3. profit

**Expected behavior**
A valid respawn packet is sent.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by retrooper** [comment]
Have you tried it recently on recent commits?
