### ISSUE TITLE
TileEntityType enum is not relevant anymore

### ISSUE THREAD

**Issue by AbhigyaKrishna** [retrooper/packetevents#688]
**Describe the bug**
TileEntityType enum mapping is not relevant anymore for newer versions. The mapping has to loaded from version mapping file.

**Software brand**
Minecraft 1.20+

**Plugins**
None

**How To Reproduce**
None

**Expected behavior**
The TileEntityType id should be mapped according to versions.

**Screenshots**
TileEntityType id for sign is 7 now
![image](https://github.com/retrooper/packetevents/assets/71663979/ca928bb9-6de9-4678-bf8f-e5a2678c4408)

**Additional context**
This is should be resolved after mapping compression pr #648 is accepted

**Comment by booky10** [comment]
https://github.com/retrooper/packetevents/blob/427a305b611e2fccf6e0fa58e73c67b293194dc1/api/src/main/java/com/github/retrooper/packetevents/protocol/world/blockentity/BlockEntityTypes.java
this was resolved with the 1.20.5 update in #658

**Comment by booky10** [comment]
The enum has been replaced with #658
