### ISSUE TITLE
WrapperPlayServerDeclareCommands deserialization error

### ISSUE THREAD

**Issue by Nononitas** [retrooper/packetevents#700]
**Describe the bug**
When having luckperms installed I get a ArrayIndexOutOfBound exception when trying to wrap a declare packet.
I used the wrapper on the bungeecord, but most likely same issue will occur on spigot/velocity, as it is the same handling.

[error](https://pastebin.com/k1K2yVQi)

**Software brand**
Paper 1.20.4 and Waterfall 

**Plugins**
LuckPerms, Essentials, Multiverse-Core. ProtocolLib Vault, ViaBackwards, ViaVersion

**Plugins Bungee**
LuckPerms, Protocolize

**How To Reproduce**
1. Make listener in bungee for declare commands and try wrapping it.
2. Install LuckPerms
3. Have an 1.20.4 backend mc server
4. Join with 1.19.3
5. See error

**Comment by Nononitas** [comment]
When joining with 1.20.4 this error occurs

https://pastebin.com/tbWf8FUw

**Comment by xGinko** [comment]
I get the same ArrayIndexOutOfBoundsException when trying to use WrapperPlayServerDeclareCommands on paper/purpur 1.16.5

**Comment by F3F5** [comment]
same problem
