### ISSUE TITLE
Optimization and two features

### ISSUE THREAD

**Issue by ShadowOfHeaven-Me** [retrooper/packetevents#706]
You already know.
I have constant packets, but PE doesn't support that. You need to duplicate a PacketWrapper if you want to send the constant contents mutliple times.
I also need to send a lot of packets "silently" (like User#sendPacketsSilently), but since the silent context is not cached, it's pretty inefficient.
Also add a PacketWrapper for MapData.
Have all reflection in SpigotReflectionUtil as static final.
When invoking the packet listeners, have them all be be an ordered array, which you could override each time a new listener is added/removed. Create a variable with the array, so like PacketListener[] array = LISTENERS; which I think will prevent any funny actions when overriding occurs during reading. Just make sure to have that array be volatile. This'll make this internal implementation about ~7 times faster.

**Comment by retrooper** [comment]
I think the constant packets idea is a good suggestion. Good idea and it'll definitely be considered. Whilst developing my minecraft server implementation I did encounter this and understand why you suggested it.

**Comment by retrooper** [comment]
With listeners, optimizations have been done for the upcoming release, I think the current solution is fine.

**Comment by ShadowOfHeaven-Me** [comment]
You can use my method's explanation to add the missing WrapperServerPlayMapData:
```
public static ByteBuf createBuffer(int mapId, byte[] pixels) {
        ByteBuf buffer = NettyUtils.buffer();
        ByteBufHelper.writeVarInt(buffer, PACKET_ID);//packed id
        ByteBufHelper.writeVarInt(buffer, mapId);//map id
        ByteBufHelper.writeByte(buffer, 3);//scale
        ByteBufHelper.writeBoolean(buffer, false);//has icons/locked
        ByteBufHelper.writeBoolean(buffer, false);//locked/tracking positions

        //Only difference in protocol after 1.8.8 is between these two versions (
        //https://wiki.vg/index.php?title=Protocol&oldid=17753#Map_Data 1.19
        //https://wiki.vg/index.php?title=Protocol&oldid=18067#Map_Data 1.19.2
        if (serverVersion.isOlderThanOrEquals(ServerVersion.V_1_19))//the array is not optional on 1.19 and below
            ByteBufHelper.writeVarInt(buffer, 0);//just say that the length is 0, so that we don't have to provide the array (my implementation, you can visit the site for that)

        ByteBufHelper.writeByte(buffer, 128);//updated columns
        ByteBufHelper.writeByte(buffer, 128);//updated rows
        ByteBufHelper.writeByte(buffer, 0);//x offset
        ByteBufHelper.writeByte(buffer, 0);//z offset
        ByteBufHelper.writeVarInt(buffer, pixels.length);//byte array's length, so here 16384 (128x128, since the offsets are 0)
        ByteBufHelper.writeBytes(buffer, pixels);//write the byte array (map's pixels)
        return buffer;
    }
```

**Comment by retrooper** [comment]
What does this have to do with this issue though? Thanks? Please make a new issue so we can organize and gather everything.

**Comment by ShadowOfHeaven-Me** [comment]
got it
