### ISSUE TITLE
WrapperPlayServerUpdateLight and LightData

### ISSUE THREAD

**Issue by LeeGodSRC** [retrooper/packetevents#714]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to update lights for version prior to 1.18.

**Describe the solution you'd like**
Move light data away from WrapperPlayServerChunkData (trustEdges, blockLightMask, skyLightMask... etc) into a LightData class
Create another wrapper called WrapperPlayServerUpdateLight and include LightData.

**Comment by booky10** [comment]
resolved by your pr
