### ISSUE TITLE
PacketEvents non-shaded prevents connections

### ISSUE THREAD

**Issue by jtJava** [retrooper/packetevents#719]
**Describe the bug**
When using latest PacketEvents for Velocity, any sort of connection is prevented. The server will not respond to pings or direct connections. No error in console besides the following possibly unrelated message which does not happen every time.
```
[06:21:52 INFO] [packetevents]: Injecting packetevents...
[06:21:52 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Software brand**
Velocity 3.3.0-SNAPSHOT-385

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/37258614/6e19a695-b616-4463-919b-976722d6d0de)

**How To Reproduce**
*Example:*
1. Join with any version and any client
2. Disconnected with the message "Disconnected"

**Expected behavior**
Able to ping/join server

**Comment by jtJava** [comment]
I happened to delete the PacketEvents jar before taking the screenshot but you can see every other plugin.

**Comment by Teslicek** [comment]
I have exactly the same issue.

![image](https://github.com/retrooper/packetevents/assets/87967222/bdfa434c-d478-4601-93df-8b37ef1df2cb)

The console just outputs this, it doesnt allow anyone to join. When I remove PacketEvents from proxy, it works just fine.

When I use Velocity #359 compared to Velocity #385, it works fine (but the lower version doesnt support 1.20.5).

**Comment by retrooper** [comment]
Try on latest commit, but I just tested it now to work. (Maybe since we recently supported 1.20.5/1.20.6)

**Comment by Teslicek** [comment]
Yes, the latest commit works, thanks.
