### ISSUE TITLE
1.20.5 Support

### ISSUE THREAD

**Issue by BurkenDev** [retrooper/packetevents#720]
Plugin does not work with the latest velocity properly. The unsigned chat message popup is still there and you can't login when you use the old version of the plugin.

Please fix an velocity and 1.20.5 plugin asap.

**Comment by Tofaa2** [comment]
1.20.5 is not supported yet or officially released.

**Comment by LeeGodSRC** [comment]
https://github.com/retrooper/packetevents/pull/658

**Comment by AoElite** [comment]
1.20.5 is still being worked on just FYI

**Comment by retrooper** [comment]
Expect an official release very soon.
