### ISSUE TITLE
Console Spam - ViaVersion

### ISSUE THREAD

**Issue by agiskagldsf** [retrooper/packetevents#721]
**Describe the bug**
packetevents spams the console with "[packetevents] Unable to grab ViaVersion client version for player!"

**Software brand**
Purpur 1.20.2

**How To Reproduce**

1. Start the server with latest version of viaversion
2. packetevents starts spamming the console

**Expected behavior**
no console spam

**Screenshot''

![viaversion](https://github.com/retrooper/packetevents/assets/125828498/2f43ee43-265d-4b90-98c1-731d0ef0e8cb)

Edit:
Sorry that I wrote that the problem was solved (I thought I had solved it :3)
Please fix this error ASAP

**Comment by SamB440** [comment]
Update, this was fixed in https://github.com/retrooper/packetevents/pull/692
