### ISSUE TITLE
Cannot cancel packets on Bungeecord and Velocity

### ISSUE THREAD

**Issue by Rubenicos** [retrooper/packetevents#723]
**Describe the bug**
Using `PacketSendEvent#setCancelled(true)` make the player don't receive any packet before that, causing a disconnection after timeout or any random error.

**Software brand**
Waterfall 1.20 build 577
Velocity 3.3.0-SNAPSHOT

**Additional context**
For some reason, sending a regular `KeepAlive` packet (by changing last used wrapper) instead of `#setCancelled(true)` fixes it.
Maybe that alternative using KeepAlive instead of cancel packet can be implemented directly on packetevents for Bungeecord and Velocity.

**Comment by retrooper** [comment]
Please elaborate on your issue? Show us what you tried with code and explain what you wanted to happen. Cancellation of packets generally works on our end so there was likely a misunderstanding of what is going on.

**Comment by retrooper** [comment]
Join our discord server in order for us to have a more fluid and personalized conversation about the matter. If that is not possible, please reopen the issue, and we shall discuss further.
