### ISSUE TITLE
Dropping support for "stupid" versions

### ISSUE THREAD

**Issue by ThrowerWay** [retrooper/packetevents#726]
Would you be against dropping support for stupid versions of the game? ~
i.e. any version that is not 1.8.8, 1.12.2, 1.20.x?
Would reduce bloat a lot and those 3 versions make up 99.9% of non dead servers.

Even then, its kinda a stretch to call 1.12 relevant in 2024, 1.12 was for 2b2t and 2b2t clones, but since 2b2t has updated 1.12 is not really relevant.

**Comment by Anthony01M** [comment]
Some gamemodes are kept intentionally on old versions in some servers (bedwars is a primary example);
Plus you are forgetting that a lot of the plugins would like to keep support for old versions and many would switch from PacketEvents if old versions support was dropped due to this.

**Comment by OakLoaf** [comment]
> Would reduce bloat a lot and those 3 versions make up 99.9% of non dead servers.

Where are you getting this "99.9%" statistic from? I personally run 1.20 but as Anthony said it would definitely turn people away from PacketEvents as a library if that many versions were dropped

**Comment by retrooper** [comment]
I understand your point, but before actively going to make this change in a PR, wait for an official response. That way no time is wasted. You can certainly lead your own fork if you deem this change as necessary, Thank you for the suggestion, but I do not support the idea and would therefore have to close the PR.
