### ISSUE TITLE
Reference in some way the fields accessed via reflection

### ISSUE THREAD

**Issue by necessaryafter** [retrooper/packetevents#730]
**Is your feature request related to a problem? Please describe.**
Yes, because the current method of searching for fields via reflection is quite costly for the machine.

**Describe the solution you'd like**
Reference in memory, even using weak references, previously accessed fields

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
Nothing

**Additional context**
![image](https://github.com/retrooper/packetevents/assets/97325014/26a6b95c-1efc-4f5e-bf34-1cd9aceed964)

**Comment by jtJava** [comment]
What classes are you referencing

**Comment by AoElite** [comment]
@necessaryafter All the places these reflection util methods are being used are caching the field. So, this isn't really relevant.
