### ISSUE TITLE
WrapperPlayServerChunkData prevents clients from connecting on 1.20.6

### ISSUE THREAD

**Issue by joshuaprince** [retrooper/packetevents#739]
**Describe the bug**
Using WrapperPlayServerChunkData on CHUNK_DATA packets kicks all connecting players with a protocol error backed by `IndexOutOfBoundsException`.

**Software brand**
Spigot 1.20.6, PacketEvents 2.0 branch rev e40dfe35

**Plugins**
Only PacketEvents (test server)

**How To Reproduce**
```java
            @Override
            public void onPacketPlaySend(PacketPlaySendEvent event) {
                if (event.getPacketType().equals(PacketType.Play.Server.CHUNK_DATA)) {
                    new WrapperPlayServerChunkData(event);
                }
            }
```
Join the server.

Client disconnects with Network Protocol Error.

**Expected behavior**
Client should connect and load into the world.

**Screenshots**
Not relevant

**Additional context**
Client logs: https://mclo.gs/Rzwac22
Server logs: https://mclo.gs/Yqt071s

**Comment by booky10** [comment]
as already mentioned on discord, this is caused by the 1.20.5+ server not sending registries the client already knows of (e.g. dimension types), so packetevents thinks the world height is set to 256 blocks

**Comment by LeeGodSRC** [comment]
> as already mentioned on discord, this is caused by the 1.20.5+ server not sending registries the client already knows of (e.g. dimension types), so packetevents thinks the world height is set to 256 blocks

Does something like this fixes the issue?
```java
                if (worldNBT != null) {
                    user.setMinWorldHeight(worldNBT.getNumberTagOrNull("min_y").getAsInt());
                    user.setTotalWorldHeight(worldNBT.getNumberTagOrNull("height").getAsInt());
                } else {
                    if (event.getServerVersion().isNewerThanOrEquals(ServerVersion.V_1_20_5)) {
                        user.setMinWorldHeight(-64);
                        user.setTotalWorldHeight(320);
                        return;
                    }
                    PacketEvents.getAPI().getLogger().warning(
                            "No data was sent for dimension " + dimension + " to " + user.getName());
                }
```

**Comment by booky10** [comment]
That doesn't fix the issue, thats just a workaround. Another workaround would be to discard the contents of the known-packs packet sent during configuration phase:
```java
if (event.getPacketType() == PacketType.Configuration.Client.SELECT_KNOWN_PACKS) {
    WrapperConfigClientSelectKnownPacks packet = new WrapperConfigClientSelectKnownPacks(event);
    packet.getKnownPacks().clear();
}
```

**Comment by booky10** [comment]
A partial workaround  for this has been added with #747
