### ISSUE TITLE
Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: net.kyori.adventure.text.Component

### ISSUE THREAD

**Issue by scarfacered** [retrooper/packetevents#757]
**Describe the bug**
https://pastebin.com/raw/BucH08Ks

**Software brand**
Paper 1.20.1

**Plugins**
Latest Grim with 6c3b66ef8438c119476ce4cc51a3277d39fb3a84, ViaVersion, ViaBackwards

Also reported in the Discord by someone else: https://discord.com/channels/721686193061888071/844238390567370813/1236277549731024936

Could be caused by server adventure version?

**Comment by AbhigyaKrishna** [comment]
Please share whole server log.
