### ISSUE TITLE
Requesting that WrapperPlayServerDamageEvent should be implemented

### ISSUE THREAD

**Issue by Real-MTR** [retrooper/packetevents#771]
please help me i need it

**Comment by Zowpy** [comment]
PacketType.Play.Server.DAMAGE_EVENT

**Comment by Real-MTR** [comment]
ty

**Comment by booky10** [comment]
Resolved in https://github.com/retrooper/packetevents/commit/3c557037188819458d04b6bd94756a71a819eaf0
