### ISSUE TITLE
ProtocolManager#getUser(Object channel) generates a ClassCastException

### ISSUE THREAD

**Issue by Lukadcf** [retrooper/packetevents#777]
**Describe the bug**
I tried to convert a channel into a player using the code below (which works) but I still got an exception.

`Object channel = PacketEvents.getAPI().getPlayerManager().getChannel(player);`
`User user = PacketEvents.getAPI().getProtocolManager().getUser(channel);`
`Player player2 = Bukkit.getPlayer(user.getUUID());`

Exception: java.lang.ClassCastException: class io.netty.channel.socket.nio.NioSocketChannel cannot be cast to class org.bukkit.entity.Player (io.netty.channel.socket.nio.NioSocketChannel and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @4e515669)

**Software brand**
paper-1.20.4-493

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/156549307/21ceb70e-4134-4ac6-8dbb-044b24767b0b)

**How To Reproduce**
Run this to see error: PacketEvents.getAPI().getProtocolManager().getUser(channel);

**Expected behavior**
I expected to not get an exception because its written in [the javadocs](https://packetevents.github.io/javadocs/com/github/retrooper/packetevents/manager/protocol/ProtocolManager.html#getUser(java.lang.Object)) that I can convert a Channel into a User
And it works but I still get an exception and it would bad for finding actual errors when I get spammed with exceptions all the time.

**Screenshots**
![image](https://github.com/retrooper/packetevents/assets/156549307/372c8f18-468a-4501-883e-3c10b049575c)
![image](https://github.com/retrooper/packetevents/assets/156549307/a02dfc86-133a-4f3b-bee4-e2cdd1be4ddd)
![image](https://github.com/retrooper/packetevents/assets/156549307/ecf58915-0683-47d1-8e34-8a8e279529eb)

**Comment by booky10** [comment]
The stacktrace doesn't match with your code. You call `ProtocolManager#getUser` in your provided code, but the stacktrace errors at `PlayerManager#getUser`

**Comment by Lukadcf** [comment]
Weird cause removing that one line prevented the exception

**Comment by retrooper** [comment]
Boils down to wrong usage, if possible join our discord so we can have a more fluid conversation. Also sharing more code helps. Booky pointed it out pretty well. If joining the discord is not possible, re-open the issue.
