### ISSUE TITLE
late-bind 1.8.8

### ISSUE THREAD

**Issue by ghost** [retrooper/packetevents#780]
**Describe the bug**
https://pastebin.com/L4dLX3cs

**Software brand**
Paper 1.8.8

**Plugins**
Plugins (1): packetevents

**How To Reproduce**

**Example**
    1. Enable late-binding in spigot.yml.
    2. Start the server.
    3. Stop the server.

**Comment by UntouchedOdin0** [comment]
lol, 1.8.8 issues as always.

**Comment by F3F5** [comment]
> lol, 1.8.8 issues as always.
if you don't like something go fuck yourself

**Comment by AbhigyaKrishna** [comment]
Could you try reproducing it with the latest snapshot build?

**Comment by retrooper** [comment]
No longer reproducible it seems.
