### ISSUE TITLE
Method #ItemStack.getEnchantments always returns empty list

### ISSUE THREAD

**Issue by Suzuuki** [retrooper/packetevents#792]
The problem occurs when getting a list of enchantments for an item; the list is always empty. On version packetevents 2.2.1 everything works, but on the latest version the problem already appears

**Comment by booky10** [comment]
Which server version are you running on?

**Comment by Suzuuki** [comment]
I tested on Tuinity 1.16.5 and Purpur 1.20.5 and it didn't work in both cases.
