### ISSUE TITLE
Add autoRead/autoWrite channel control to user object

### ISSUE THREAD

**Issue by VenixPLL** [retrooper/packetevents#798]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem

**Describe the solution you'd like**
Be able to set autoRead/autoWrite channel flags from user object.

**Describe alternatives you've considered to solve your solution without
us adding this as a feature?**
Getting the channel using user.getChannel() and casting it into Nio/Epoll SocketChannel and setting the flag manually

**Additional context**
No Additional context

This enchancement can be used to make more complex packet mechanics and make the developer not worry about client sending the packet too early. autoRead lock for channel can be used to wait for something to finish before reading the next packet.

**Comment by booky10** [comment]
whats autowrite?

**Comment by VenixPLL** [comment]
> whats autowrite?

Automatic writes into netty pipeline, when autowrite is turned off, writing into the buffer does not 'flush' the packet down the pipeline and you can write the buffer with 3-4 packets and then flush it

Automatic reads locks the reading from channel, you can just stop reading any more packets from client,
You can lock the channel when client connects and not receive anything for 2-3 seconds, then unlock and receive handshake/loginstart (just an example)

This can be used to timeout a client or wait for something to finish before reading the next packet
You just have to be carefull to not lock it for too long.

**Comment by retrooper** [comment]
Very netty specific feature. What prevents you from simply using netty directly? The channel is literally inside the user object.
