### ISSUE TITLE
Players respawn instantly after dying

### ISSUE THREAD

**Issue by joshuaprince** [retrooper/packetevents#816]
**Describe the bug**
With only packetevents installed, the first time a player dies during a session, they respawn instantly after only seeing the death screen for a moment. Dying again works as expected, but logging out and back in resets the issue.

Removing packetevents fixes the problem.

**Software brand**
Paper 1.20.6-134
Vanilla 1.20.6 client
packetevents dev build 426 (6a3b18af)

**Plugins**
Only packetevents

**How To Reproduce**
1. Join the server
2. /kill or die another way
3. Do it again, and it behaves as expected

**Expected behavior**
Death screen should appear.

**Screenshots**
[2024-06-03 22-59-36.webm](https://github.com/retrooper/packetevents/assets/16515311/f2433252-7066-4b61-8316-477de080782c)

**Additional context**
N/A

**Comment by booky10** [comment]
Not sure how this would happen without any packetevents listener, but there is indeed an issue

https://github.com/retrooper/packetevents/blob/6a3b18aff945cc615af420f9f776151892303aaf/api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerJoinGame.java#L206
