### ISSUE TITLE
[Bug] Bungee Pipeline Injection & Exception disabling plugin packetevents

### ISSUE THREAD

**Issue by Bram1903** [retrooper/packetevents#818]
**Describe the bug**
When setting up a Bungeecord proxy with one of the latest snapshots, upon joining the server (without any plugins other than PacketEvents) you get a `NullPointerException`. This doesn't seem to be the case in older versions but is consistent across newer versions. Besides that, and I am including this bug in the same bug report as I think they are related, when you close the proxy you get `Exception disabling plugin packetevents`. 

**Software brand**
Bungeecord (Latest Snapshot)

**Plugins**
Only the PacketEvents plugin

**How To Reproduce**
1. Join Server (Bug 1)
2. Close the proxy (Bug 2)

**Expected behavior**
Well, an injection without errors. Packet wise everything seems to work fine. Besides that when shutting down the proxy I don't expect a shutdown error.

**Screenshots**
Login Bug:
![image](https://github.com/retrooper/packetevents/assets/70259613/e097c42d-1af5-47fa-8974-eec4de7b92f1)

Bungeecord Shutdown Bug:
![image](https://github.com/retrooper/packetevents/assets/70259613/95aab8bd-a87b-4313-9d14-2dee9df92e80)

**Comment by Nunchakin** [comment]
same

**Comment by retrooper** [comment]
https://github.com/retrooper/packetevents/commit/7a342a8c21cfa7f8acebdceb7cf8a3ad63219b0f

**Comment by Nononitas** [comment]
![Screenshot 2024-06-21 191449](https://github.com/retrooper/packetevents/assets/47149720/58131275-bb57-458d-8f91-a962b6f203a9)
Now this excpetion occurs when trying to join

**Comment by Bram1903** [comment]
> fixed in latest commit

Yeah, we know haha, that's why those commits have been made :-)
