### ISSUE TITLE
TileEntityType ID descrepancy with WrapperPlayServerBlockEntityData

### ISSUE THREAD

**Issue by Summiner** [retrooper/packetevents#826]
**Describe the bug**
While using WrapperPlayServerBlockEntityData you must provide a Tile Entity Type for the entity data, however this packet gets the id from the entry list value which seems to be different between versions leading to IDs not being valid in certain versions.

**Software brand**
Paper 1.20.4

**Plugins**
Only my plugin used to test this bug.

**How To Reproduce**
Create an instance of WrapperPlayServerBlockEntityData and provide valid data for a sign (will be used in this example) as seen in the screenshot below and set the TileEntityType to that of a sign
![image](https://github.com/retrooper/packetevents/assets/77811772/6af1e3ec-d3c1-4a41-ab5a-7f0c3ac29fa3)
Log the packet to the console to view the data easily like below
![image](https://github.com/retrooper/packetevents/assets/77811772/c240f56c-0d80-44d5-b1e7-69e186cf5b2f)
Trigger the event that initializes the code above then compare the logged data to the data sent when creating a real sign
After this you will see that the type and native packet ID are different from what they should be
(Left is the correct version and right is the incorrect version provided from TileEntityType.SIGN)
![image](https://github.com/retrooper/packetevents/assets/77811772/80a1a700-fa3c-4ffc-8136-73ed9a7df4fc)
![image](https://github.com/retrooper/packetevents/assets/77811772/76d49ec5-992f-4f53-9a22-c8096033f21c)
When changing the example to use TileEntityType.STRUCTURE_BLOCK on 1.20.4 it will set the data correctly unlike using TileEntityType.SIGN because the structure block has the ID the sign should, you can also see in the two comparison screenshots that the mappings are incorrect for the correct version aswell while the IDs are displayed correctly.

**Expected behavior**
The expected behavior in the case of this version would be that TileEntityType.SIGN would have the ID of 7 instead of 9 leading to the data being set correctly for the sign.

**Comment by booky10** [comment]
You can use `BlockEntityTypes.SIGN.getId(PacketEvents.getAPI().getServerManager().getVersion().toClientVersion())` in the constructor as a workaround until #828 is merged
