### ISSUE TITLE
Jenkins no longer shades libraries into jars

### ISSUE THREAD

**Issue by libraryaddict** [retrooper/packetevents#834]
As of build [#437](https://ci.codemc.io/job/retrooper/job/packetevents/437/) which was from this commit https://github.com/retrooper/packetevents/commit/f53e73ed9a2d9487003ca6c90280fe6e7b0b5c6e, [Jenkins](https://ci.codemc.io/job/retrooper/job/packetevents/) no longer shades the required libraries in, which results in plugin jars that cannot load.

Or to rephrase, optimizations in the project's structure has streamlined the final output of the jenkin jars and decreased their size by up to 95% which is a huge savings in storage and networking cost at the small expense of usability.

Replacing jenkins with Github actions as a download source isn't a good replacement as it requires users to be logged in to download artifacts which makes this impossible to automate without requiring server owners to setup a github account, or by having the plugin developer inject their own personal token with every jar.

[Github artifacts not downloadable anonymously issue here.](https://github.com/actions/upload-artifact/issues/51)

Adding to that, non-automated downloads from github is not user friendly for identifying the right file to download, which is in a zip which can further confuse users.

As a download source, [jenkins ](https://ci.codemc.io/job/retrooper/job/packetevents/)is still very much in demand.

**Comment by AbhigyaKrishna** [comment]
Jenkins now contain correct jars with shaded libraries.
