### ISSUE TITLE
PacketEvents failed to eject the injection handler.

### ISSUE THREAD

**Issue by andrewkm** [retrooper/packetevents#839]
Paper version 1.20.6-147-ver/1.20.6@e41d44f
Vulcan 2.8.8

Was told to complain here regarding this error on server stop lol.
`[Server thread/ERROR]: [Vulcan] PacketEvents failed to eject the injection handler! Please reboot!`

Am aware it's harmless and could be ignored, but it kind of screws with our error/warn tracking, and seeing it more and more lately is pretty annoying. Hopefully it can be addressed somehow, even though Vulcan is still on 1.8 (?)

**Comment by retrooper** [comment]
You correctly pointed out that the error is trivial, I will make sure that it does not happen in future versions of your software "Vulcan". But I'll leave you with some even better news. Vulcan stated that they are planning on updating to PacketEvents 2.0 very soon.
