### ISSUE TITLE
Cannot invoke "com.github.retrooper.packetevents.protocol.nbt.NBTCompound.getCompoundListTagOrNull(String)" because the return value of "com.github.retrooper.packetevents.protocol.nbt.NBTCompound.getCompoundTagOrNull(String)" is null

### ISSUE THREAD

**Issue by LOLYAYDEV** [retrooper/packetevents#840]
**Describe the bug**
When I try to listen For a Packet I get this Error:
https://mclo.gs/J0KfSOx

**Software brand**
The plugin and My plugin Are on Velocity 3.3 And the Backend is a Paper 1.20.6 Server

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/118024018/55987fb4-fe7b-41f1-b1bd-e78591c0bda1)

**How To Reproduce**
My Code:

```
public class vanish extends PacketListenerAbstract {
    public vanish() {
        super(PacketListenerPriority.LOW);
    }

    @Override
    public void onPacketReceive(PacketReceiveEvent event) {
        //Cross-platform user
        User user = event.getUser();
        if (event.getPacketType() == PacketType.Play.Server.ENTITY_MOVEMENT || event.getPacketType() == PacketType.Play.Server.ENTITY_HEAD_LOOK) {
            user.sendMessage(Component.text("§7§l[§1§lETERNALUTILS§7§l] §3§lYou cannot use vanish."));
            event.setCancelled(true);
        }

            }


}
```

**Expected behavior**
Allow me to Listen for Packets and Not giving Error

**Screenshots**
![image](https://github.com/retrooper/packetevents/assets/118024018/3534a38f-b22d-4b09-8b6f-da986cf1f586)
![image](https://github.com/retrooper/packetevents/assets/118024018/24003a22-27e8-40f5-898a-3561771725d4)

**Additional context**
I added It as a Dependency in The Main class And Grandle

**Comment by booky10** [comment]
Generally, don't pass `§`-codes into `Component#text`
Thats not how components work

**Comment by LOLYAYDEV** [comment]
Yes I know everyone Tells me this but thats how I got used to

**Comment by booky10** [comment]
Does it work without abusing legacy color codes?

**Comment by LOLYAYDEV** [comment]
No it doesnt even trigger iz. Ive used legacy colors bwfoe in velocity and stuff so it works but the code isnt even triggert

**Comment by LOLYAYDEV** [comment]
So what to do? Wait for a fix ig

**Comment by booky10** [comment]
which plugins/datapacks do you have installed on your backend server and which version are you trying to connect with?
