### ISSUE TITLE
User send message is broken in latest 2.3.1 commit

### ISSUE THREAD

**Issue by SquareCodeFX** [retrooper/packetevents#862]
**Describe the bug**
User send message is broken in latest 2.3.1 commit no exceptions

**Software brand**
Spigot 1.8.8

**Plugins**
Just this plugin with packetevents 2.3.1

**How To Reproduce**
use user.sendMessage("Test")

**Expected behavior**
Just sens a message

**Screenshots**
I checked if the respone os null or something
![image](https://github.com/retrooper/packetevents/assets/37747818/4ba97b31-ac42-415a-946d-cafd0a6cc204)

**Additional context**
I used

 PacketEvents.setAPI(SpigotPacketEventsBuilder.build(Sierra.getPlugin()));
        PacketEvents.getAPI().getSettings()
            .fullStackTrace(true)
            .kickOnPacketException(
                Sierra.getPlugin().getSierraConfigEngine().config().getBoolean("kick-on-packet-exception", true))
            // .reEncodeByDefault(false)
            .checkForUpdates(true)
            .debug(false);
        PacketEvents.getAPI().load();

**Comment by retrooper** [comment]
What about getAPI().init() inside onEnable?

**Comment by SquareCodeFX** [comment]
I did that after this. This was just for settings measures

**Comment by retrooper** [comment]
Fixed in https://github.com/retrooper/packetevents/commit/b07461340e495ab427c6086b7bde5a6dbfd522ec
