### ISSUE TITLE
Can't access Velocity server due to LimboAPI and PacketEvents 2.4.0

### ISSUE THREAD

**Issue by TheFaik** [retrooper/packetevents#873]
I can't connect to 1.21 server because of LimboAPI library which is needed for LimboAuth+LimboFilter+LimboReconnect plugins. Please solve this...

**Comment by booky10** [comment]
See #841 and #853

**Comment by TheFaik** [comment]
> See #841 and #853

Unfortunately it doesn't help... I installed the Dev version of LimboAPI to support PakcetEvents, but the player still can't enter the server

**Comment by booky10** [comment]
Yeah, there is no fix for this currently
I just wanted to link to these related issues

**Comment by UserNugget** [comment]
@TheFaik, you should use both [LimboAPI](https://github.com/Elytrium/LimboAPI/actions/runs/9866763699) and [PacketEvents](https://github.com/retrooper/packetevents/actions/runs/9866774682) from actions and enable `save-uncompressed-packets` in the LimboAPI config (if you disabled it earlier) to make PacketEvents work.

**Comment by TheFaik** [comment]
> > Unfortunately it doesn't help... I installed the Dev version of LimboAPI to support PakcetEvents, but the player still can't enter the server
> 
> @TheFaik, you should use both [LimboAPI](https://github.com/Elytrium/LimboAPI/actions/runs/9866763699) and [PacketEvents](https://github.com/retrooper/packetevents/actions/runs/9866774682) from actions and enable `save-uncompressed-packets` in the LimboAPI config (if you disabled it earlier) to make PacketEvents work.

Всё равно не могу зайти на сервер. Я создал пустой Velocity сервер и итог тот же, я даже попытался использовать новые актуальные новые версии, но всё безуспешно. Я прошу ещё раз починить это...

**Comment by TheFaik** [comment]
> > Unfortunately it doesn't help... I installed the Dev version of LimboAPI to support PakcetEvents, but the player still can't enter the server
> 
> @TheFaik, you should use both [LimboAPI](https://github.com/Elytrium/LimboAPI/actions/runs/9866763699) and [PacketEvents](https://github.com/retrooper/packetevents/actions/runs/9866774682) from actions and enable `save-uncompressed-packets` in the LimboAPI config (if you disabled it earlier) to make PacketEvents work.

Unfortunately it doesn't help... I installed the Dev version of LimboAPI to support PakcetEvents, but the player still can't enter the server

**Comment by TheFaik** [comment]
> > К сожалению, это не помогает... Я установил Dev-версию LimboAPI для поддержки PakcetEvents, но игрок все равно не может зайти на сервер.
> 
> @TheFaik, вам следует использовать как [ LimboAPI ](https://github.com/Elytrium/LimboAPI/actions/runs/9866763699) , так и [ PacketEvents ](https://github.com/retrooper/packetevents/actions/runs/9866774682) из действий и включить `save-uncompressed-packets` в конфигурации LimboAPI (если вы отключили его ранее), чтобы PacketEvents работал.

К сожалению это тоже не помогает. Я всё равно не могу зайти на сервере. Пишет, что время превышено. 
Я даже поставил на чистый Veloctity сервер и итог тот же. Попытался использовать последние сборки LimboAPI и PacketEvents и итог тот же - не могу зайти на сервер. Ни каких ошибок, ничего абсолютно... Прошу ещё раз перепроверить, а лучше пофиксить это, ведь плагин Pl-Hide-Pro работает с помощью PacketEvents, а отказываться от LimboFilter, LimboAuth и LimboReconnect, как-то не хочется....

**Comment by TheFaik** [comment]
> > Unfortunately it doesn't help... I installed the Dev version of LimboAPI to support PakcetEvents, but the player still can't enter the server
> 
> @TheFaik, you should use both [LimboAPI](https://github.com/Elytrium/LimboAPI/actions/runs/9866763699) and [PacketEvents](https://github.com/retrooper/packetevents/actions/runs/9866774682) from actions and enable `save-uncompressed-packets` in the LimboAPI config (if you disabled it earlier) to make PacketEvents work.

Проблема так и остаётся открытой! Я сделал точно так, как вы и сказали, но результат такой же - игроки  не могут зайти.

**Comment by TheFaik** [comment]
> > Unfortunately it doesn't help... I installed the Dev version of LimboAPI to support PakcetEvents, but the player still can't enter the server
> 
> @TheFaik, you should use both [LimboAPI](https://github.com/Elytrium/LimboAPI/actions/runs/9866763699) and [PacketEvents](https://github.com/retrooper/packetevents/actions/runs/9866774682) from actions and enable `save-uncompressed-packets` in the LimboAPI config (if you disabled it earlier) to make PacketEvents work.

Will LimboAPI support be added to PacketEvents 2.5.0?

**Comment by TheFaik** [comment]
![изображение](https://github.com/user-attachments/assets/7f694ae6-18e2-421f-9330-6626ebacbae4)

**Comment by booky10** [comment]
Is apparently fixed by LimboAPI when activating "compatibility-mode"
https://github.com/Elytrium/LimboAPI/issues/146#issuecomment-2351046083
