### ISSUE TITLE
ChunkData IllegalStateException

### ISSUE THREAD

**Issue by ipavdev** [retrooper/packetevents#878]
**Describe the bug**
Everytime I try to send a ChunkData packet I get this error: https://pastebin.com/ZzTeK3gT

**Software brand**
git-Purpur-2133 (MC: 1.20.4)* and 2.4.0 packetevents.

**Test Code**
https://pastebin.com/AXhh46Hk (The same issue happens even when tileEntities isn't null, forgot to change that)
 
Same error occurs with [this code too](https://github.com/Kooperlol/Blockify/blob/blockchanges/src/main/java/codes/kooper/blockify/managers/BlockChangeManager.java#L225)

**Comment by booky10** [comment]
Are you sure your provided stacktrace has anything to do with the described issue?
https://github.com/Kooperlol/Blockify/blob/blockchanges/src%2Fmain%2Fjava%2Fcodes%2Fkooper%2Fblockify%2Fprotocol%2FChunkLoadAdapter.java#L25

**Comment by KoutaChan** [comment]
Those codes probably aren't sending chunks correctly. Please try this code and see if it fixes the issue: https://pastebin.com/meSKWSRp

**Comment by ipavdev** [comment]
Seems like that worked, I guess it was just my code.
