### ISSUE TITLE
Client kick when wrapping event

### ISSUE THREAD

**Issue by Lukadcf** [retrooper/packetevents#884]
**Describe the bug**
Client gets kicked when it receives a ENTITY_SOUND_EFFECT packet from throwing a trident and it gets wrapped in WrapperPlayServerEntitySoundEffect 

**Software brand**
paper-1.20.4-493.jar

**Plugins**
![image](https://github.com/retrooper/packetevents/assets/156549307/63676b87-d6fb-4f22-ac98-a386a7609b04)

**How To Reproduce**
```
@Override 
    public void onPacketSend(PacketSendEvent event) {
        if (event.getPacketType() == PacketType.Play.Server.ENTITY_SOUND_EFFECT) {
            WrapperPlayServerEntitySoundEffect packet = new WrapperPlayServerEntitySoundEffect(event);
        }
```
And throw a trident

**Expected behavior**
To not kick the client

**Screenshots**
![image](https://github.com/retrooper/packetevents/assets/156549307/9b921496-3ea0-4dff-ac87-dee6542436fe)

**Extra Information**
This probably happens with any sound but I can't find another way to trigger this event naturally.

**Comment by booky10** [comment]
Update packetevents and test again

**Comment by Lukadcf** [comment]
Fixed 👍
