### ISSUE TITLE
Can a rule be added to allow players with specific names to bypass packet events injection?

### ISSUE THREAD

**Issue by Chaostarts** [retrooper/packetevents#892]
Due to some plugins relying on packetevents, some players such as Fakeplayer's bots and Bedrock players are unable to enter the game
The will lost connection: PacketEvents 2.0 failed to inject

Can a rule be added to allow players with specific names, such as those with".", to bypass packet event injection?

This will solve many problems with my server. Thanks！

**Comment by jtJava** [comment]
PacketEvents already has support,
 for this, the channel class needs to be named FakeChannel or SpoofedChannel.
https://github.com/retrooper/packetevents/blob/4524b4289cc1912363faf873ee81034105924f1e/api/src/main/java/com/github/retrooper/packetevents/util/FakeChannelUtil.java#L21

**Comment by jonesdevelopment** [comment]
> Can a rule be added to allow players with specific names, such as those with".", to bypass packet event injection?

Bedrock players don't always use `.` as a prefix.

Additionally, packetevents shouldn't fail to inject when you join with Bedrock in the first place.

**Comment by retrooper** [comment]
@jtJava is correct.
