### ISSUE TITLE
EncoderException error

### ISSUE THREAD

**Issue by tommasov03** [retrooper/packetevents#895]
**Describe the bug**
When users connect to the server with 1.21 they are kicked out with this error from the launcher:
![image](https://github.com/user-attachments/assets/f9e0d5d4-ee19-4713-a693-b0a15ea14093)

while this is the error on the bungeecord console:
[12:52:22 INFO]: [tommasov03] disconnected with: EncoderException : com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 114 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.21 @ io.netty.handler.codec.MessageToByteEncoder:125

This doesn't happen with versions lower than 1.21.

**Software brand**
FlameCord 2.1.8 as a bungeecord proxy and USpigot 1.1.6 (1.20.1) for backend servers.

**Plugins**
Bungeecord plugin:
ajQueuePlus-2.7.0.jar, apollo-bungee-1.1.4.jar, Badlion-ModApi-Bungee 2.1.6.jar, BetterStreams-1.0.jar, BotSentry-9.6.1-THANATOS-SpigotMC.jar, BungeBroadcast-2.0.jar, CleanMOTD 0.2.8.jar, CleanPing 1.6.1.jar, EnderSS-universal-1.1.2.jar, floodgate-bungee 109.jar, Infinity-Filter_Forward.jar, JPremium-CLEARED-1.23.0.jar, LiteBans 2.15.1.jar, LowHostingAB-1.5.3.jar, LuckPerms-Bungee-5.4.137.jar, Maintenance-4.2.1.jar, MineStore-0.3.2.jar, MultiLobby 7.1.2.jar, Nameless-Plugin-BungeeCord-3.4.0.jar, packetevents-bungeecord-2.4.1-SNAPSHOT.jar, Pl-Hide-Pro-2.10.3.jar, Plan-5.6-build-2883.jar, ReportDiscordPlus-4.2.jar, ScarletAntiKillBoost-2.0.jar, SkinsRestorer 15.2.0.jar, StaffChecker-3.0.jar, UHCMaintenance-bungee-1.0.jar, UltraStaffChatPro-2.0.18.jar, VulcanBungee-1.0.6.jar

**How To Reproduce**
1. Have packetevents installed in both bungeecord and server backends;
2. Enter with 1.21;
3. See the error on the bungeecord launcher and console.

**Screenshots**
![image](https://github.com/user-attachments/assets/9ca7b301-1495-4cd3-89fa-fe75f55eeaa5)

**Additional context**
The backend servers are on 1.20.1 with viaversion and have the same version of packetevents installed as bungeecord (packetevents-spigot-2.4.1-SNAPSHOT). Not all launchers have this problem.

**Comment by linsaftw** [comment]
Hey man I would like to know what is missing in flamecord that might be causing this because packet types are basically untouched in flamecord and I think the error itself is incomplete if there is a way to get the full log or a debug mode it would be very useful to get the information i need to fix as the Packet ID mappings are unchanged from Waterfall to FlameCord.

**Comment by MotikaCraft-TheJoshua** [comment]
I have exact same problem when using:
- FlameCord 2.1.8 (as proxy)
- PacketEventsAPI 2.5.0-SNAPSHOT, build#554 (on both proxy and subserver)
- Dionysus 1.12.2 (as subserver)

The error for me is happening when trying to connect from Bedrock Client v1.20.81 (i made sure that my Geyser/Floodgate installed on proxy and Floodgate only on subserver, are up to date and they support up to v1.21.30, from v1.20.80/1)
![image](https://github.com/user-attachments/assets/d2f95f2e-63f5-46eb-9b58-6c7b13857773)

**Comment by liquidman228** [comment]
Same issue here with the latest Flamecord and the latest Packetevents. Any solution?

**Comment by booky10** [comment]
Please report this issue to Flamecord, we can't fix issues with closed-sourced software

**Comment by linsaftw** [comment]
Just a heads up. I was not able to replicate the error and PacketEvents + PlHidePro seems to be working fine.

I tested FlameCord 2.2.9 + PacketEvents Development Build
I also tested FlamePaper 1.8 Dionysus 1.12 and Purpur 1.21
Also tested with 1.8-1.21 clients
No issue whatsoever

![image](https://github.com/user-attachments/assets/1d3f5335-4595-4041-a00f-6f114ba96279)
![image](https://github.com/user-attachments/assets/676c59af-b714-40d8-8d7b-ea86b7776fb2)
![image](https://github.com/user-attachments/assets/fc6cb883-00c1-46a6-9d35-f50ba2adffd1)
![image](https://github.com/user-attachments/assets/e8db975a-b00f-425a-91de-72bdeaec7cae)
![image](https://github.com/user-attachments/assets/3a4f4a2c-0872-4aa0-9955-eb23b906c266)
