### ISSUE TITLE
enchantment is null (1.21)

### ISSUE THREAD

**Issue by Mineopo** [retrooper/packetevents#904]
**Describe the bug**
Whenever an enchantment book is dropped, the server kicks players within range of the book and throws a message:
"
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null
"
The solution is to remove the book using the kill @e[type=minecraft:item] command in the terminal.

**Software brand**
Paper 1.21 และ Velocity 3.3.0-SNAPSHOT (git-09f687e5-b413)

**Plugins**
Paper 1.21 Plugin : 
Paper Plugins:
- AuthMeVelocity
Bukkit Plugins:
- AuraMobs, AuraSkills, AuthMe, AuthMeTitles, BetterEconomy, Citizens, CMILib, CrunchSiegeWeapons, DoubleDoors, fast-leaf-decay
 FastAsyncWorldEdit, FlagsH, GravesX, GSit, Images, Jobs, LagFixer, Lands, LibsDisguises, LuckPerms, Multiverse-Core, packetevents, PlaceholderAPI, ProtectionStones, ProtocolLib, SkinsRestorer, TextOverPlayer, Vault, ViaBackwards, ViaVersion, WorldGuard

Velocity Plugin : luckperms, authmevelocity, authmevelocity-lastserver-addon, floodgate, geyser, skinsrestorer, spark, tab, viaversion, viabackwards

**How To Reproduce**

*Example:*
Whenever an enchantment book is dropped, the server kicks players within range of the book
And I saw it pop up in the terminal.
"
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null
"

**Screenshots**
![สกรีนช็อต 2024-08-03 104712](https://github.com/user-attachments/assets/787fa9c5-b9db-4bb1-be80-22b520c3a611)

**Comment by HaHaWTH** [comment]
Looks like the same error #869 , did u installed custom enchant plugins?

**Comment by booky10** [comment]
See above comment, this will be fixed with #866
