### ISSUE TITLE
"enchantment" is null

### ISSUE THREAD

**Issue by Razorxd1993** [retrooper/packetevents#908]
**Describe the bug**
"enchantment" is null

**Software brand**
Purpur 1.21

**Plugins**
![image](https://github.com/user-attachments/assets/4e060a2d-71e4-4330-86b9-a485b3fc14b9)

**How To Reproduce**
as soon as you go near an item that is enchanted (item frame etc) you are kicked off the server.
ExcellentEnchants is used, before the update to 1.21 everything ran smoothly.

**Expected behavior**
as soon as you go near an item that is enchanted (item frame etc) you are kicked off the server.
ExcellentEnchants is used, before the update to 1.21 everything ran smoothly.

**Screenshots**
![image](https://github.com/user-attachments/assets/6d198953-ad42-48e6-8e1d-236afbb1fa99)

**Comment by retrooper** [comment]
A fix will be deployed very soon.
