### ISSUE TITLE
ChunkData Packet Bug in 1.12.2

### ISSUE THREAD

**Issue by Kr1S-D** [retrooper/packetevents#910]
**BUG DESCRIPTION**
I'm trying to modify the chunks that are sent from the server to the player using a Packet Listener for the PacketType.Play.Server.CHUNK_DATA packet, to test the actual functioning of this system, I wanted to try to create a fake chunk full of diamond blocks from 0 to 255, however only a part of this chunk was sent to the player as I wanted.
Apparently the BaseChunks are null if it is all air, therefore to complete what I wanted to do I had to create them using the appropriate method, however the chunks created in this way in the column create graphical bugs to the client.

The first of these bugs is that the light is not updated correctly (but it could have depended on me), the second which is the most serious is that when the player interacts with a real block the chunk sent by the server becomes that block (I don't know how to make it clear so I will send a video for this)

**Software brand**
Paper 1.12.2 for the server, and 1.12.2 for client (no viaversion installed)

**Plugins**
My PLugin and PacketEvents

**My Code**
```
javapublic class ChunkDataListener implements PacketListener {
    private FakeChunk fakeChunk = new FakeChunk(FakeWorld.createEmptyWorld(null), new ChunkLocation(0, 0));

    public ChunkDataListener() {
        fakeChunk.generateColumns(FakeWorld.createEmptyWorld(null), Material.DIAMOND_BLOCK);
    }

    @Override
    public void onPacketSend(PacketSendEvent event) {
        long a = System.currentTimeMillis();

        if (PacketType.Play.Server.CHUNK_DATA == event.getPacketType()) {
            WrapperPlayServerChunkData data = new WrapperPlayServerChunkData(event);

            Column column = data.getColumn();
            int chunkSize = 16;

            int chunkX = column.getX();
            int chunkZ = column.getZ();
            if (fakeChunk.getLocation().getX() == chunkX && fakeChunk.getLocation().getZ() == chunkZ) {

                for (int i = 0; i < column.getChunks().length; i++) {
                    BaseChunk chunk = column.getChunks()[i];

                    if (chunk == null) {
                        chunk = column.getChunks()[i] = BaseChunk.create(); //Something wrong here
                    }
                    int baseChunkY = i * chunkSize; // Calculate base Y coordinate for this chunk

                    for (int x = 0; x < chunkSize; x++) {
                        for (int z = 0; z < chunkSize; z++) {
                            for (int y = 0; y < chunkSize; y++) {
                                int realY = baseChunkY + y;

                                IFakeBlock blockAt = fakeChunk.getBlockAt(x, realY, z);
                                if(blockAt == null) {
                                    Logger.debug("Null block at " + x + " " + realY + " " + z);
                                    continue;
                                }

                                chunk.set(x, y, z, NMS.getBlockID(blockAt.getType()));
                            }
                        }
                    }
                }

                long b = System.currentTimeMillis() - a;
                Logger.debugBroadCast("Took " + b + "ms");
            }
        }
    }
}
```

**VIDEO**
https://youtu.be/8Apwe_s4C0o

*NOTE*
Small note, the chunk part that you see in the video is the minecraft one that does not have this bug, I also generated an entire world of stone chunks but up to y 50 so as to always have pre-created chunks

**Comment by booky10** [comment]
> The first of these bugs is that the light is not updated correctly

Packetevents sadly doesn't have a light calculation engine, you will need to either write your own, find some constant value which fits your usecase or use the server light engine to light your custom chunks. This is not the fault of packetevents.

> the second which is the most serious is that when the player interacts with a real block the chunk sent by the server becomes that block

You will need to intercept interactions sent by the player and either cancel them or handle the properly. This is not the fault of packetevents either.
This server doesn't know about the chunk you sent the player, so it tries to "correct" the players view by removing the blocks the player clicked on.
