### ISSUE TITLE
error with the latest dev build

### ISSUE THREAD

**Issue by Z3r0xh** [retrooper/packetevents#922]
Describe the bug
console spam

Software brand
NullcordX 3.8.8

Plugins
image

How To Reproduce
Just place the latest dev build and wait for the users to enter

Expected behavior

Screenshots
Full server log (https://mclo.gs/N6KAVQf)

Additional context

NullcordX now accepts event packets, currently back to 2.4.1

**Comment by rafi67000** [comment]
update to latest dev build

**Comment by Z3r0xh** [comment]
> update to latest dev build

This was in build #530

**Comment by booky10** [comment]
fixed with #927
