### ISSUE TITLE
Bug that kick player when load an dropped item with enchants on versions +1.21

### ISSUE THREAD

**Issue by OMarcoGPO** [retrooper/packetevents#925]
**Describe the bug**
Using the excellentEnchants plugin, when I drop an item with a customenchant, and any player load this item, the player will be kicked with the following error:
![image](https://github.com/user-attachments/assets/a9a0af7d-4350-4796-81a5-d74f13dd3fc8)

(will not send error to console)

**Software brand**
Paper 1.21

**Plugins**
Probably this plugins can be the problem:
ExcellentEnchants, nigthcore, Viaversion, protocolib

**How To Reproduce**
Using the plugins that I mencioned, drop an item that have been enchanted with a custom enchant of excellentenchants
The bug will happen

**Expected behavior**
The enchant item should not kick players when is loaded

**Comment by rafi67000** [comment]
update to latest dev build please

**Comment by booky10** [comment]
see comment above, this has already been fixed
