### ISSUE TITLE
Wrapped BlockPlace issue with getDirection function

### ISSUE THREAD

**Issue by EthoIRL** [retrooper/packetevents#93]
stacktrace: https://pastebin.com/ZQXgm6xg
video: https://streamable.com/e78plf

**Comment by retrooper** [comment]
Hey, what version of PacketEvents are you on? This have been fixed a long time ago in the dev commits/builds.

**Comment by EthoIRL** [comment]
> 
> 
> Hey, what version of PacketEvents are you on? This have been fixed a long time ago in the dev commits/builds.

Latest version on spigot (1.7.9)
![image](https://user-images.githubusercontent.com/58352929/104882265-a3134100-5917-11eb-9898-1976b882dfc2.png)

**Comment by EthoIRL** [comment]
Issue has already been fixed in the dev branch

**Comment by retrooper** [comment]
Yep I was just typing this ->
I'd say update to the current latest 1.8 dev commit/build.
It does have API changes, a tutorial already exists on the 1.8 API even though it is not released.
We planned to release it sooner, but are delaying it so we can have a detailed guide ready

**Comment by retrooper** [comment]
If you want a pre-build jar of the dev commits, join the discord server and see #dev-builds discord channel.

**Comment by terrarier2111** [comment]
There are no functions in java btw
