### ISSUE TITLE
1.21.1 Console error

### ISSUE THREAD

**Issue by ghost** [retrooper/packetevents#930]
**Describe the bug**
Console error. Nothing happens ingame, that i know.

**Software brand**
Paper 1.21.1 + Currently newest packetevents dev build

**Plugins**
ProtocolLib

**How To Reproduce**
*Example:*
1.21.1 paper, newest dev packetevents, newest dev protocollib

**Expected behavior**
No console error

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://pastebin.com/aWS78wXC)

**Additional context**
Nothing

**Comment by booky10** [comment]
> Currently newest packetevents dev build

This has been fixed with #927 - are you sure you're using the latest packetevents build?

**Comment by ghost** [comment]
I re-uploaded the file now. Maybe my browser downloaded a cached file. Gonna run tests now!

**Comment by ghost** [comment]
Seems fixed. Thank you!
