### ISSUE TITLE
Isseus with [1.21] Enchants.

### ISSUE THREAD

**Issue by darkwolfie37** [retrooper/packetevents#937]
**Describe the bug**
Players are kicked once someone holds an enchanted item.

![image](https://github.com/user-attachments/assets/22f8d58e-c935-4cd8-b84e-8866f2f42f82)

**Software brand**
![image](https://github.com/user-attachments/assets/918d7550-c312-4b99-8c8c-42a90eb1600a)

**Plugins**
![image](https://github.com/user-attachments/assets/e4afe2c2-8092-4f8e-b5a0-91bd21f278e7)

**How To Reproduce**
*Example:*
1. Join a 1.21 server with ViaVersion (assuming they use apart of your code) and grab an enchanted item.
2. Have a second player or yourself. 
3. Hold item (if  a second player) and the Second player should get kicked for the error above, or drop the item and watch yourself get kicked.

**Expected behavior**
I believe that it is not supposed to  kick the user.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by retrooper** [comment]
Have you tried updating PacketEvents to the latest dev build on [Jenkins](https://ci.codemc.io/job/retrooper/job/packetevents/)

**Comment by darkwolfie37** [comment]
> Have you tried updating PacketEvents to the latest dev build on [Jenkins](https://ci.codemc.io/job/retrooper/job/packetevents/)

I will let the owner know, i dont have file access to the server.

**Comment by darkwolfie37** [comment]
Datapack Enchants is what is causing this error. After removing the enchants from one of our datapacks, it seems to fix the issue!
