### ISSUE TITLE
"this.monsterSpawnLightLevel" is null

### ISSUE THREAD

**Issue by Z3r0xh** [retrooper/packetevents#945]
Describe the bug
Spam in console

Software brand
NullcordX 3.8.8
lobby pandaSpigot last build
backends UniverseSpigot 1.21

Plugins
Proxy:
![image](https://github.com/user-attachments/assets/19398910-44b2-4af9-b1ae-c6857361965a)
Lobby:
![image](https://github.com/user-attachments/assets/6f931b3c-a5ed-4ddc-ba8e-acb1707b228b)
Survival:
![image](https://github.com/user-attachments/assets/89bb6645-7d77-460c-9674-0b6e41510402)

https://mclo.gs/pGTstyZ

Build #544

**Comment by retrooper** [comment]
This was already fixed in https://github.com/retrooper/packetevents/commit/ca725b68a546a4eeaf9b8d8d5f42e15ceb0ded22

**Comment by retrooper** [comment]
Use the latest build on [Jenkins](https://ci.codemc.io/job/retrooper/job/packetevents/)

**Comment by Z3r0xh** [comment]
> This was already fixed in [ca725b6](https://github.com/retrooper/packetevents/commit/ca725b68a546a4eeaf9b8d8d5f42e15ceb0ded22)

This is not a fix, the test I am sending you is from today with the latest dev build available
