### ISSUE TITLE
[Bug] WrappedPacketOutChat doesn't seem to be working properly in v1.8-pre-3

### ISSUE THREAD

**Issue by True-cc** [retrooper/packetevents#95]
I do
```java
WrappedPacketOutChat chat = new WrappedPacketOutChat(e.getNMSPacket());
String msg = chat.getMessage();
System.out.println("Msg:" + msg);
```

and I get two different results depending in the environment I'm in. If I launch my server in a terminal, I get
![image](https://user-images.githubusercontent.com/38010540/107468140-54bf1f80-6b1c-11eb-96ba-ea13ac260aa6.png)
but if I launch it in my IDE (IntelliJ) I get
![image](https://user-images.githubusercontent.com/38010540/107468260-859f5480-6b1c-11eb-9b3e-fe3e92e5ad90.png)
Both times I get the message in game. This is super weird. Any idea why this is happening?

**Comment by True-cc** [comment]
This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[packetevents] You are on a dev or pre released build of PacketEvents. Your build: (1.7.9.3) | Latest released build: (1.7.9)

**Comment by True-cc** [comment]
Update: It's Java version dependent. My IDE is running the command `/home/shoghi/.jdks/liberica-1.8.0_252/bin/java -Dfile.encoding=UTF-8 -jar /.../spigot-1.12.2.jar` 
which is 
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode
```
whereas in my terminal I'm running `java -jar spigot-1.12.2.jar` which is 
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

**Comment by retrooper** [comment]
Are you just trying to detect whenever a player sends a message? If yes, use the WrappedPacketInChat in PacketPlayReceiveEvent. Sending a message to a player in WrappedPacketOutChat can create a big loop, as you end up sending the packet whenever the packet is sent, which will just keep going and break stuff lol. WrappedPacketInChat is strictly when the player sends a message.

**Comment by retrooper** [comment]
Seems like it creates and endless loop on my server lol. Don't do what you just did please :rofl: LMK How the WrappedPacketInChat works out.

**Comment by retrooper** [comment]
> Update: It's Java version dependent. My IDE is running the command `/home/shoghi/.jdks/liberica-1.8.0_252/bin/java -Dfile.encoding=UTF-8 -jar /.../spigot-1.12.2.jar`
> which is
> 
> ```
> openjdk version "1.8.0_252"
> OpenJDK Runtime Environment (build 1.8.0_252-b09)
> OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode
> ```
> 
> whereas in my terminal I'm running `java -jar spigot-1.12.2.jar` which is
> 
> ```
> openjdk version "11.0.9.1" 2020-11-04
> OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
> OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
> ```
> 
> Edit: `-Dfile.encoding=UTF-8` doesn't do anything.

Hmmm.. Well PacketEvents uses JDK 8. Not sure why this happens.

**Comment by True-cc** [comment]
Update: I did a bit of my own testing.
```java
public String getMessage(WrappedPacketOutChat chat) { // This works on Java 8
    final Object iChatBaseObj = chat.readObject(0, iChatBaseComponentClass);

    try {
        Object contentString = Reflection.getMethod(iChatBaseComponentClass, String.class, 0).invoke(iChatBaseObj);
        return contentString.toString();
    } catch (IllegalAccessException | InvocationTargetException e) {
        e.printStackTrace();
    }
    return null;
}

public String getMessage1(WrappedPacketOutChat chat) { // This works on Java 11
    final Object iChatBaseObj = chat.readObject(0, iChatBaseComponentClass);

    try {
        Object contentString = Reflection.getMethod(iChatBaseComponentClass, String.class, 1).invoke(iChatBaseObj);
        return contentString.toString();
    } catch (IllegalAccessException | InvocationTargetException e) {
        e.printStackTrace();
    }
    return null;
}```

**Comment by retrooper** [comment]
What the fuck

**Comment by True-cc** [comment]
> What the fuck

indeed
