### ISSUE TITLE
Faild to decode packet 'clientbound/minecraft:damage_event'

### ISSUE THREAD

**Issue by Z3r0xh** [retrooper/packetevents#958]
Software brand
NullcordX 3.8.8
lobby pandaSpigot last build
backends UniverseSpigot 1.21

PacketEvents build [#552]

Plugins
Proxy:
![image](https://github.com/user-attachments/assets/1cbf5111-a578-4ebd-a6de-8e14f4ebe651)

How To Reproduce
Just entering through the proxy and this error appears,

Sometimes it lets it play for a while but it ends up appearing

Expected behavior
some players get kick with this problem

**Screenshots**
![image](https://github.com/user-attachments/assets/b8f9b6ce-b937-4339-bc79-cda679c2598a)

**Comment by booky10** [comment]
This should have been fixed in packetevents now - if this still occurs, please post a new stacktrace
