### ISSUE TITLE
because "enchantment" is null

### ISSUE THREAD

**Issue by dol4iua** [retrooper/packetevents#963]
**Describe the bug**
[21:24:49] [Server thread/INFO]: Endemic_345[/IP:PORT] logged in with entity id 1637 at ([world]-21328.30000001192, 67.0, 17681.69999998808)
[21:24:49] [Server thread/INFO]: Endemic_345 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null
Kick players with this messegs.
After i update https://www.spigotmc.org/resources/excellentenchants-%E2%AD%90-75-vanilla-like-enchantments.61693/ to lates version.
(on version 4.1.0 all works)

**Kick all playes.**

**Software brand**
Please let us know what software you are using.
Version of PE- packetevents-spigot-2.5.0-SNAPSHOT
Core - PurPur 1.21.1 - purpur-1.21.1-2291

**Plugins**
Paper Plugins: (1):
  - HuskSync
 Bukkit Plugins: (61):
 - AdvancedBan, AdvancedTeleport, ajAntiXray, AnimatedScoreboard, AnvilColors, AutomaticBroadcast, BansWebhook, BlueSlimeCore, Brewery, ChunkSpawnerLimiter
Chunky, Citizens, ConditionalEvents, CooldownsX, CoreProtect, Craftorithm, DecentHolograms, DeluxeMenus, DiscordSender, eShulkerBox
Essentials, EssentialsGeoIP, ExcellentEnchants, FastAsyncWorldEdit, floodgate, GSit, HeadDrop, InvisibleItemFrames, JDALibLoaderBukkit, LibsDisguises
LuckPerms, Multiverse-Core, MythicMobs, nightcore, Orebfuscator, packetevents, PlaceholderAPI, Plan, PlasmoVoice, PlayerPoints
ProtocolLib, PvPManager, SCore, Shopkeepers, SimpleClans, SimplePortals, SkinsRestorer, sleep-most, squaremap, TAB-Bridge
Themis, ThemisToDiscord, TrParticles, UltimateChat, Vault, ViaBackwards, ViaVersion, WorldBorder, WorldEditSelectionVisualizer, WorldGuard
WorldGuardExtraFlags

**How To Reproduce**
After i update https://www.spigotmc.org/resources/excellentenchants-%E2%AD%90-75-vanilla-like-enchantments.61693/ to lates version.
(on version 4.1.0 all works)

**Comment by booky10** [comment]
Are you using the latest packetevents build?

**Comment by Z3r0xh** [comment]
Sorry for the ping, I was just saying that I keep getting the same error from some players. Some can play worse by TPing or moving fast and it kicks them out of the server. Others can't even get into the proxy.
![image](https://github.com/user-attachments/assets/a1a54a7d-f1b3-4205-8339-77e69fd416e2)

**Comment by dol4iua** [comment]
![image](https://github.com/user-attachments/assets/d74d0d45-ae81-483c-b998-cf68c293f872)

**Comment by Z3r0xh** [comment]
> ![image](https://private-user-images.githubusercontent.com/24779133/360901004-d74d0d45-ae81-483c-b998-cf68c293f872.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTIzMDEsIm5iZiI6MTcyNDQxMjAwMSwicGF0aCI6Ii8yNDc3OTEzMy8zNjA5MDEwMDQtZDc0ZDBkNDUtYWU4MS00ODNjLWI5OTgtY2Y2OGMyOTNmODcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDExMjAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MTY5YzBmMjU1YTU3Y2IzNTJiNTY4Y2E1N2Y3ZTYzY2JlYzNkODcyYmYyMWZiYmVhNDY5NGZlYjY1YTIzZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aYAfncHqSV9aFNTAVjrfSRhHvqJH6snpyJn9FKPF7ho)

I'm using the latest dev build, every day I check the builds in jenkins and download them. But I keep getting the same error.

**Comment by thesquidghost** [comment]
<img width="1014" alt="Screenshot 2024-08-23 at 1 13 33 PM" src="https://github.com/user-attachments/assets/94bbcfa9-c27d-4166-8a75-126ff1ad6570">
just wanted to report that I also am getting this after updating a handful of plugins.

**Comment by mahon91** [comment]
Same problem here : 
![image](https://github.com/user-attachments/assets/f8557dbf-5c73-40f5-87cc-686df41e9246)

**Comment by mahon91** [comment]
Here are a few clarifications:

When I find an enchanted book in a chest, if I try to open the chest, I get kicked from the server.

If I put an enchanted book in my inventory, it's even worse—I can no longer rejoin the server.

**Comment by MrMcyeet** [comment]
I'm seeing this, too, when using either ecoenchants or excellent enchants

**Comment by Keviro** [comment]
This still happens with version `2.5.0+e105770dd-SNAPSHOT`

```[packetevents] You are running a development build of PacketEvents. Your build: (2.5.0+e105770dd-SNAPSHOT) | Latest release: (2.4.0)```

**Comment by MeoNguOfficial** [comment]
I have same error too

**Comment by LadyHaley** [comment]
I am also getting the same error
```[15:30:17 INFO]: LadyHaley lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null```

**Comment by booky10** [comment]
@thesquidghost @mahon91 @MrMcyeet @MeoNguOfficial @LadyHaley 
Please ensure you all are using the latest build of packetevents, this issue should not be related to problems with ecoenchants

---

@dol4iua @Z3r0xh @MrMcyeet please test if #972 fixes your problems
download to packetevents build: https://github.com/retrooper/packetevents/actions/runs/10613644385/artifacts/1869331529

**Comment by LadyHaley** [comment]
I looked into why I even had the plugin, the libsdisguise dev build seems to be downloading what its labeling as 
packetevents-spigot-2.5.0-SNAPSHOT if that helps with the influx of entries at all
Also for the record, in case it matters, I am not using EcoEnchants, I am using Excellent Enchants

**Comment by booky10** [comment]
use the latest build from jenkins, this issue should be fixed
