### ISSUE TITLE
AN ERROR FOR PACKT EVENT WHEN I USE EXCELLENT ENCHANTMENTS

### ISSUE THREAD

**Issue by MeoNguOfficial** [retrooper/packetevents#970]
**Describe the bug**
I use Excellent Enchantments for add more enchant, but error, and it kick me:

`[02:08:38] [Server thread/INFO]: MeoNgu2 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null`

Full log: 
[2024-08-29-2.log.gz](https://github.com/user-attachments/files/16791080/2024-08-29-2.log.gz)

**Software brand**
I use Leaf 1.21.1

**Plugins**
![image](https://github.com/user-attachments/assets/29bf9da0-7f74-400c-a1c4-fab96b2c0ed8)

**How To Reproduce**
Watch this video

https://github.com/user-attachments/assets/825c5a78-1f16-49ce-940e-bc46d2f363b8

**Expected behavior**
I can't find packet event config file

Please help me to fix it. Thanks so much

**Comment by MeoNguOfficial** [comment]
Additional info: I use Packet  event Devbuild
![image](https://github.com/user-attachments/assets/4d504fbc-c91d-4f77-b30f-c423ff547bce)

**Comment by booky10** [comment]
Duplicate, same issue as https://github.com/retrooper/packetevents/issues/963
