### ISSUE TITLE
error on proxy

### ISSUE THREAD

**Issue by matteo00788** [retrooper/packetevents#977]
why packetevent bungee doesn't support xcord?

------------------------------------------------------------------------------------------------------------------------------------------------------
I have a problem with packetevent bungee

https://pastebin.com/w49RpjaG  this error was sent to the proxy console

------------------------------------------------------------------------------------------------------------------------------------------------------

Encoder Exception: Java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "io.github.retrooper packetevents.injector CustomPipelineUtil BUNGEE PACKET_ENCODE_BYTEBUF" is null @ io.netty.handler.codec.MessageToByteEncoder:-1

this is what appears to the player

------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by booky10** [comment]
> why packetevent bungee doesn't support xcord?

Disabling pipeline merging in xcord's config should fix this.

We can't add proper support for proprietary software we don't even have access to.

**Comment by matteo00788** [comment]
is alredy disable

**Comment by booky10** [comment]
see message on discord, contact xcord
