### ISSUE TITLE
IndexOutOfBoundsException error from Matrix plugin when handling packets

### ISSUE THREAD

**Issue by v4r1n** [retrooper/packetevents#987]
**Describe the bug**
When a player clicks in the interface window (such as a container window), the Matrix plugin catches an exception and throws an `IndexOutOfBoundsException`

**Expected Behavior**
The server should process the click event correctly, and the player should interact with the container without issues.

**Actual Behavior**
Instead of processing the click event, the server throws an `IndexOutOfBoundsException`, causing the player to be disconnected with the error message "Internal Exception: `io.netty.handler.codec.DecoderException`"

**Steps to Reproduce**
1. Have a player open a container window on the server.
2. Attempt to interact with the container (e.g., click on an item).
3. The exception occurs and the player gets disconnected.

**Software brand**
Beckend: PaperMC 1.21.1-69-925c3b9
Proxy: Velocity 3.3.0-SNAPSHOT (git-3c23ee75-b430)

**Plugins**
Matrix v7.10.3
packetevents v2.5.0+99acbe496-SNAPSHOT

**Screenshots**
#1
![image](https://github.com/user-attachments/assets/3ad5bc85-2bc8-4682-8a40-651583da8a33)
#2
![image](https://github.com/user-attachments/assets/112005ab-8581-4016-b96f-1e071ae8ec73)

**Additional context**
Include any other helpful information, such as server logs (like the one you provided), or configuration files that may help reproduce the issue.

**Comment by jtJava** [comment]
You should provide a full stacktrace

**Comment by v4r1n** [comment]
> You should provide a full stacktrace

What do I have to do?

**Comment by booky10** [comment]
You need to send the full error

**Comment by v4r1n** [comment]
Because of the ecoenchants plugin, when clicking on an item with this plugin's special enchantment, the player will be kicked out of the server.

video: https://github.com/user-attachments/assets/f74bd110-f16f-416f-8feb-352b7ec6cc6e
latest.log: https://paste.helpch.at/waxuhopexe.makefile

**Comment by booky10** [comment]
i cant reproduce the issue shown in your video with the latest packetevents build
have you ensured your matrix version is up-to-date?

**Comment by booky10** [comment]
closing because of no response
