### ISSUE TITLE
1.20.4 support

### ISSUE THREAD

**Issue by comonier** [retrooper/packetevents#988]
if you try take a map from a boat chest (connected in a 1.20.4 version) you will be kicked from the server
![image](https://github.com/user-attachments/assets/fd06a9a8-ecbd-4fc1-b80f-5ea98d6ce4d4)
not happens on 1.20.1

the server is 1.21 using packetevents 1.21 compatible
the server have viaversion / viabackwards 
i am trying do it  on 1.20.4 and it not works
works on other versions

**Comment by booky10** [comment]
please provide reproduction steps (e.g. which map causes this error) or at least the full stacktrace of the shown error message

**Comment by comonier** [comment]
> please provide reproduction steps (e.g. which map causes this error) or at least the full stacktrace of the shown error message

![image](https://github.com/user-attachments/assets/d0af477b-93c7-4ce9-b40f-c8c9e4a65c01)
if you try to click on that icon (any mouse button) you will be kicked from the server
doesnt matter if the map is on a chest or my inventory, the event that kick the player is just click on map.
i change my minecraft verion to 1.21, so i get the map inside the chest to my inventory, close minecraft and i back to version 1.20.4 so just trying move the map inside my inventory make me get kicked again.

The server owner told me that change my minecraft version to play on server cause that plugin cant be configurated to not kick players, and just not works with 1.20.4 version.

but i play in other server that only accept 1.20.4 so i need to close minecraft always to play on a different server while it still with bug.

![image](https://github.com/user-attachments/assets/6bc5d8de-9c5c-4f49-a869-4e26b8b98cfd)

He said that it would be difficult for you to support an old version of the game, and that I could lose my hope but hope dies last so I came to try.

![image](https://github.com/user-attachments/assets/f96a43f3-e8f1-4a71-93c9-372c2b31cce4)
you can found it on sunken boats chests.

**Comment by comonier** [comment]
issue still on versions 1.20.1 | 1.20.2 | all 1.20.*  (only works on 1.20.6)
